### PR TITLE
[lte][agw] Adding SGW IPv4 S1U endpoint address as EPC config

### LINKED ISSUE #3908: (Orc8r) Configuration support for AGW S1-U end point

### PR DESCRIPTION
**Pull request by ardzoht**
Signed-off-by: Alejandro Rodriguez <alexrod@fb.com>

## Summary

- This adds a EPC config on Orchestrator to override `SGW_IPV4_ADDRESS_FOR_S1U_S12_S4_UP` on spgw.conf template.
- In the case that the value on EPC config is not set or is empty, the value from `spgw.yml` iface IP will be taken.

## Test Plan

- Tested with local AGW and Orchestrator setup, validating that adding the value on EPC config overrides the value on `spgw.conf` template file:

```
        # S-GW binded interface for S1-U communication (GTPV1-U) can be ethernet interface, virtual ethernet interface, we don't advise wireless interfaces
        SGW_INTERFACE_NAME_FOR_S1U_S12_S4_UP    = "eth1";
        SGW_IPV4_ADDRESS_FOR_S1U_S12_S4_UP      = "192.168.128.33/24";
        SGW_IPV4_PORT_FOR_S1U_S12_S4_UP         = 2152;                         # INTEGER, port number, PREFER NOT CHANGE UNLESS YOU KNOW WHAT YOU ARE DOING
```

Test case for empty cloud EPC config value:
```
        # S-GW binded interface for S1-U communication (GTPV1-U) can be ethernet interface, virtual ethernet interface, we don't advise wireless interfaces
        SGW_INTERFACE_NAME_FOR_S1U_S12_S4_UP    = "eth1";
        SGW_IPV4_ADDRESS_FOR_S1U_S12_S4_UP      = "192.168.60.142/24";
        SGW_IPV4_PORT_FOR_S1U_S12_S4_UP         = 2152;                         # INTEGER, port number, PREFER NOT CHANGE UNLESS YOU KNOW WHAT YOU ARE DOING
```

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by mpgermano — APPROVED** [review]
LGTM

**Comment by ulaskozat** [comment]
Did you test the negative case, where config in orc8r is missing?

**Review by ulaskozat — APPROVED** [review]
LGTM. Please also include the result of negative test case where orc8r does not supply the config.

**Review by pshelar — APPROVED** [review]
LGTM

**Pull request merged**
