### PR TITLE
docs: Fixing typo in cloudstrapper_install.md

### PR DESCRIPTION
**Pull request by geetikabatra**
This change fixes the typo in `Deploying Magma via Cloudstrapper`

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by Neudrino — CHANGES_REQUESTED** [review]
Could we combine those multiple one word changes in one PR please. E.g. https://github.com/magma/magma/pull/12863

**Comment by geetikabatra** [comment]
Sure!

**Comment by geetikabatra** [comment]
Closing this one as this is updated in https://github.com/magma/magma/pull/12863

**Comment by geetikabatra** [comment]
Closing this one as this is updated in https://github.com/magma/magma/pull/12863

**Pull request closed without merging**
