### PR TITLE
[WIP]: Magma Domain Proxy

### PR DESCRIPTION
**Pull request by xbend**
[WIP]: Magma Domain Proxy

## Summary
This PR is a proposal of a merge of Domain Proxy development into Magma codebase.

As discussed in a community meeting with @talkhasib , @hcgatewood, @jpad-freedomfi, @aswin-alexander, @bbarritt and others, this PR is a first step of discussion on how to include the ongoing development of vendor neutral Domain Proxy code into Magma's codebase.

The PR consists of a few commit's, each commit intended to target a specific section of magma code and its ownership.
Please review and comment if this division makes logical sense. We could either proceed with having one PR with such commits, or we can issue individual PRs per each section/domain.

Currently we have 5 commits in this PR:
1) Helm charts integration - this development has already been reviewed by @hcgatewood 
2) Orchestrator deployment integration
3) Domain Proxy: AGW side - integration with AGW/enodebd (LTE module) based on Baicells 436Q eNB
4) Domain Proxy: ORC8R side - domain proxy microservices that interact with AGW/enodebd and SAS server
5) Github workflows

The Domain Proxy part presented here, with minor alternations done due to rebase onto magmas master, has been fully tested in a local lab - helm, deployment, DProxy in orc8r interface with AGW, Baicells 436Q eNB able to be fully configured.

The code is now capable of acquiring and maintaining a SAS grant on behalf of a Baicells 436Q and fully configure it for transmission via TR069.

### CODE REVIEW

**Comment by xbend** [comment]
As this is still a draft, please ignore the failing CI for now.
As first step, we would like to get if this commit/PR division is the correct way to proceed with the actual merge activities.

**Comment by hcgatewood** [comment]
The set of commits seems like a reasonable way to break things up -- my only input is let's have 1 PR per commit (and ideally a couple PRs for the larger commits), that way we can separate the review process and not have all the different codeowners tripping over each other

**Comment by jpad-freedomfi** [comment]
FYI, @talkhasib this is per our discussion Monday. How/who should be picking reviewer?

**Comment by xbend** [comment]
@hcgatewood 
There is no problem in constructing separate PRs per codeowner's domains. 
My concern is that during merge process into master, the PR's only make sense/work IF merged together. We could even opt for a final squash merge, so that nobody will accidentally pick dependent commits.

Within one PR, you can still conduct reviews by selecting an individual commit and only comment on that piece of code - that should provide distinction for codeowners and have a cohesive review for the entire Domain Proxy feature.

If you still think that separate PRs is the way to go, we will proceed with that approach. Please confirm.

**Comment by hcgatewood** [comment]
> @hcgatewood There is no problem in constructing separate PRs per codeowner's domains. My concern is that during merge process into master, the PR's only make sense/work IF merged together. We could even opt for a final squash merge, so that nobody will accidentally pick dependent commits.
> 
> Within one PR, you can still conduct reviews by selecting an individual commit and only comment on that piece of code - that should provide distinction for codeowners and have a cohesive review for the entire Domain Proxy feature.
> 
> If you still think that separate PRs is the way to go, we will proceed with that approach. Please confirm.

Yes, this needs to be in separate PRs

**Comment by xbend** [comment]
@hcgatewood 
Understood. Closing this PR. We will issue separate PRs per mentioned sections/domains.

**Pull request closed without merging**
