### PR TITLE
docs: Adds installation support for Ubuntu

### PR DESCRIPTION
**Pull request by sanchezfdezjavier**
## Summary

- Changed `docs/readmes/basics/prerequisites.md` to add Ubuntu support of Magma installation (previously, only guide for macOS users).

## Test Plan

I spun up several VM's reproducing the installation process that I describe in the document.

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by hcgatewood — APPROVED** [review]
Looks great, thanks for adding!

Please also add a note in the beginning of the `## Development Tools` section detailing something to the effect of: development can occur from multiple OS's, where macOS and Ubuntu are explicitly supported, with additional polish for macOS support

**Comment by sanchezfdezjavier** [comment]
@hcgatewood Anytime! From Canonical we thought it will be handy to have an Ubuntu guide. 
Btw, I've already addressed your comments and tackled the PR issues.

**Comment by sanchezfdezjavier** [comment]
@hcgatewood When will we see the changes taking effect on the website?
And many thanks for merging the PR!

**Comment by Neudrino** [comment]
Thanks for the guide, @sanchezfdezjavier ! This is very helpful for everybody not having a Mac.
I can already see the changes online at https://docs.magmacore.org/docs/next/basics/prerequisites. 😉

**Pull request merged**
