### PR TITLE
[CI][OAI] Fix when the PR title contains a # character.

### PR DESCRIPTION
**Pull request by rdefosse**
## Summary

Simple check.

## Test Plan

Ran on PR #5192 -> [OK](https://jenkins-oai.eurecom.fr/job/MAGMA-MME-production/86/artifact/build_results_magma_oai_mme.html)

## Additional Information

- [ ] This change is backwards-breaking

Signed-off-by: Raphael Defosseux <raphael.defosseux@openairinterface.org>

### CODE REVIEW

**Comment by rdefosse** [comment]
MAGMA-OAI-TESTS

**Review by mattymo — APPROVED** [review]

**Review by tmdzk — APPROVED** [review]

**Review by 119Vik — APPROVED** [review]

**Comment by rdefosse** [comment]
MAGMA-OAI-TESTS

**Comment by rdefosse** [comment]
MAGMA-OAI-TESTS

**Review by ulaskozat — APPROVED** [review]
LGTM

**Pull request merged**
