### PR TITLE
orc8r Hello servicer as external

### PR DESCRIPTION
**Pull request by sabithaatla**
## Summary

This PR deals with the segregation of Hello external gRPC servicers implementation.
These changes are part of the ongoing work which details the distinction between Orc8r-internal gRPC endpoints vs. external, gateway-oriented gRPC endpoints.
Moved hello.go implementation to southbound folder.
Verified existing UT cases.

## Test Plan

All testcases completed succesfully

### CODE REVIEW

**Review by emakeev — CHANGES_REQUESTED** [review]
Please see my previous comments on feg 'segregation' PRs.
This doesn't seem to do anything useful.

**Comment by sabithaatla** [comment]
> Please see my previous comments on feg 'segregation' PRs. This doesn't seem to do anything useful.

This PR was raised as part of discussion made with @hcgatewood . Please find the reference doc [RemoveGatewayAccess toOrc8r-InternalEndpoints](https://drive.google.com/file/d/1NO6Qd6rU80xPh0Sb0mKWlSfDt0JbeVIT/view)

**Comment by sabithaatla** [comment]
> > Please see my previous comments on feg 'segregation' PRs. This doesn't seem to do anything useful.
> 
> This PR was raised as part of discussion made with @hcgatewood . Please find the reference doc [RemoveGatewayAccess toOrc8r-InternalEndpoints](https://drive.google.com/file/d/1NO6Qd6rU80xPh0Sb0mKWlSfDt0JbeVIT/view)

Closing this PR and opened a new PR [Hello_Servicer_External](https://github.com/magma/magma/pull/11180)

**Comment by sabithaatla** [comment]
> > > Please see my previous comments on feg 'segregation' PRs. This doesn't seem to do anything useful.
> > 
> > 
> > This PR was raised as part of discussion made with @hcgatewood . Please find the reference doc [RemoveGatewayAccess toOrc8r-InternalEndpoints](https://drive.google.com/file/d/1NO6Qd6rU80xPh0Sb0mKWlSfDt0JbeVIT/view)
> 
> Closing this PR and opened a new PR [Hello_Servicer_External](https://github.com/magma/magma/pull/11180) as Repo has issues with Checks

**Pull request closed without merging**
