### PR TITLE
feat(ci): Remove useless pipelines

### LINKED ISSUE #14616: Remove the dummy package workflow
In #14500, a new workflow magma-push-dummy-package.yml was introduced as a workaround to enable GPG signing for all releases in artifactory.

- Remove the workflow again.
- Ask Linux Foundation to delete the uploaded hello-world packages from all releases. To find them, look for hello_2.10-2ubuntu2_amd64.deb in subfolders of
  - https://linuxfoundation.jfrog.io/ui/native/magma-packages-prod/pool/
  - https://linuxfoundation.jfrog.io/ui/native/magma-packages-test/pool/

### PR DESCRIPTION
**Pull request by tmdzk**
Signed-off-by: tmdzk <timodzik@gmail.com>

feat(ci):Remove useless pipelines

## Summary

https://github.com/magma/magma/issues/14616 

## Test Plan

Make sure it disappears

### CODE REVIEW

**Review by nstng — APPROVED** [review]
lgtm, should we still ask LF to delete the uploaded dummy packages?

**Comment by nstng** [comment]
@tmdzk can you have a look at the failing required check?

**Comment by tmdzk** [comment]
> @tmdzk can you have a look at the failing required check?

Just saw that, will go on Monday

**Comment by nstng** [comment]
renamed commit to pass semantic title check (+ rebased on master)

**Pull request merged**
