### PR TITLE
docs: Magma cdr availability proposal

### LINKED ISSUE #11636: Magma cdr availability proposal
Currently Magma doesn’t support any kind of CDR files for any scenarios. By implementing this proposal Magma will have full support for standard 3GPP CDRs for inbound roaming scenario and core CDR functionality for outbound roaming scenario. 

The objective is to extend Magma to support Call Data Records (CDR). The charging information is passed through a chain of logical charging functions. At the end of this process, CDR files are generated by the network, which are then transferred to the CDR client/network operator's Billing Domain for the purpose of subscriber billing and/or inter-operator accounting.

Design proposal - https://github.com/magma/magma/pull/11637

### PR DESCRIPTION
**Pull request by Arsenii-Oganov**
Signed-off-by: Arsenii Oganov <arsenii@freedomfi.com>

## Summary

proposal to bring CDRs support to Magma

Issue created: https://github.com/magma/magma/issues/11636

### CODE REVIEW

**Comment by themarwhal** [comment]
@Arsenii-Oganov Is there a proposal GitHub issue about this? It would be great if you could link it in the doc.

**Comment by Arsenii-Oganov** [comment]
@themarwhal yes, it was created and mentioned in PR - Issue created: https://github.com/magma/magma/issues/11636

**Comment by themarwhal** [comment]
> @themarwhal yes, it was created and mentioned in PR - Issue created: #11636

Can we add a link to the issue inside the proposal document so that it is easily accesible?

**Comment by Arsenii-Oganov** [comment]
@themarwhal done

**Review by electronjoe — APPROVED** [review]

**Comment by ekowtaylor** [comment]
@Arsenii-Oganov  do you still plan to move forward with this change? There are few checks failing like linting that need to be addressed. Let me know how I can help.

**Comment by Arsenii-Oganov** [comment]
@ekowtaylor I made changes, fixed my issue, but some new strange thing appears (not in my file)

**Comment by ekowtaylor** [comment]
Are you talking about this error? [Markdown insync check](https://github.com/magma/magma/runs/5449618833?check_suite_focus=true)

**Comment by Arsenii-Oganov** [comment]
> Are you talking about this error? [Markdown insync check](https://github.com/magma/magma/runs/5449618833?check_suite_focus=true)

yes

**Comment by ardzoht** [comment]
@Arsenii-Oganov this proposal needs Testing plan and Roadmap schedule as required from the TSC grant review guidelines: https://wiki.magmacore.org/display/TSC/TSC+Grant+Review

**Comment by Arsenii-Oganov** [comment]
> @Arsenii-Oganov this proposal needs Testing plan and Roadmap schedule as required from the TSC grant review guidelines: https://wiki.magmacore.org/display/TSC/TSC+Grant+Review

@ardzoht this was added to the https://github.com/magma/grants/issues/20

**Pull request merged**
