### PR TITLE
fix(agw): Modified code to port spgw's state contexts to protobuf structure

### PR DESCRIPTION
**Pull request by rsarwad**
## Summary
fix(agw): Modified code to port spgw's state contexts to protobuf structure
## Test Plan
Executed unit test cases and s1ap sanity test suite

### CODE REVIEW

**Review by LKreutzer — COMMENTED** [review]
Why does the `spgw_state_converter_test` need to be removed?

**Comment by rsarwad** [comment]
> Why does the `spgw_state_converter_test` need to be removed?
The previous code used to convert C structure to proto structure while writing to DB and vice-versa while reading from DB. This PR will have instance of protobuf structure itself, so doesn't involve conversion between C structure to proto structure. Tests within file, spgw_state_converter_test used to validate the conversion logic.

**Review by LKreutzer — CHANGES_REQUESTED** [review]
There are LSan and ASan errors in the SPGW procedures tests:
```
 //lte/gateway/c/core/oai/test/spgw_task:spgw_procedures_dedicated_bearer_test FAILED in 18.6s
  /var/tmp/bazel/execroot/__main__/bazel-out/k8-fastbuild/testlogs/lte/gateway/c/core/oai/test/spgw_task/spgw_procedures_dedicated_bearer_test/test.log
//lte/gateway/c/core/oai/test/spgw_task:spgw_procedures_session_test     FAILED in 12.5s
  /var/tmp/bazel/execroot/__main__/bazel-out/k8-fastbuild/testlogs/lte/gateway/c/core/oai/test/spgw_task/spgw_procedures_session_test/test.log
//lte/gateway/c/core/oai/test/spgw_task:spgw_procedures_test             FAILED in 15.6s
  /var/tmp/bazel/execroot/__main__/bazel-out/k8-fastbuild/testlogs/lte/gateway/c/core/oai/test/spgw_task/spgw_procedures_test/test.log
//lte/gateway/c/core/oai/test/spgw_task:spgw_procedures_with_injected_state_test FAILED in 3 out of 3 in 21.6s
  Stats over 3 runs: max = 21.6s, min = 21.5s, avg = 21.6s, dev = 0.0s
```

Please make sure that they are passing with `bazel test --config=asan` and `bazel test --config=production` or `--config=lsan`.

**Review by LKreutzer — APPROVED** [review]
Bazel changes lgtm

**Comment by panyogesh** [comment]
@rsarwad : I hope this PR is not required. Can we close it. Idea is to clean up list for upcoming release.

**Comment by panyogesh** [comment]
@rsarwad : We are planning to mark this as closed. I hope it should be fine.

**Comment by Sathyaj27** [comment]
Closing this PR

**Pull request closed without merging**
