### PR TITLE
docs: Format Markdown files in Magma

### LINKED ISSUE #14348: Apply linter autoformat to all documentation
Run formatter on all documentation (see if changes in <=1.8 makes sense). Make sure all looks fine. Create a PR and describe change process - manual changes vs formatter changes.

### PR DESCRIPTION
**Pull request by LKreutzer**
Signed-off-by: Lars Kreutzer <lars.kreutzer@tngtech.com>

## Summary

- Resolves #14348
- When modifying `.md` files in PRs the GitHub workflow can detect errors that are not fixed by the `make precommit_fix` command, because they concern files outside of the `docs/` folder, like `readme.md` files.
- Here [markdownlint](https://github.com/DavidAnson/markdownlint) is run on the entire magma folder.
  - Changes to the versioned docs and the proposals folder are excluded.
  - This can be achieved by going to `docs/readmes/docker-compose.yml` and modifying the file to be:
```
version: "3.7"

services:
  readmes:
    volumes:
      - ./../../:/readmes
    image: magma_readmes
``` 
  - Furthermore the `docs/readmes/.markdownlint.yaml` file needs to be copied to the repository root.
  - Unwanted changes were reverted manually.   
  - In the file `orc8r/cloud/helm/orc8r/charts/nms/README.md` the line 
```
- NMS Dashboard should be reachable via `https://<nginx_svc>`.
```
was modified manually because the link here should be set as code, as otherwise the angled brackets can never satisfy the markdown linter settings.
- :warning:  There is a very long list of errors that markdownlint cannot fix automatically. See [output.txt](https://github.com/magma/magma/files/10401420/output.txt) for the output - this is what the linter check complains about on this PR below and should be very close to the output of this [workflow run](https://github.com/magma/magma/actions/runs/3902021570/jobs/6664574769).

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by LKreutzer** [comment]
There seems to be a difference in configurations between the GitHub workflow and the changes.

**Comment by LKreutzer** [comment]
To get this PR merged it may be easier to wait for the PR https://github.com/magma/magma/pull/14823 to be merged first to accelerate the review process.

**Comment by LKreutzer** [comment]
> :warning:  There is a very long list of errors that markdownlint cannot fix automatically. See [output.txt](https://github.com/magma/magma/files/10401420/output.txt) for the output - this is what the linter check complains about on this PR below and should be very close to the output of this [workflow run](https://github.com/magma/magma/actions/runs/3902021570/jobs/6664574769).

I could not get markdownlint to fix all the remaining errors that its check can find. There are probably too many errors to go through all of them manually. I will create a follow-up issue to keep this in mind, perhaps a future version of the tool can fix more errors.

**Review by maxhbr — APPROVED** [review]
LGTM

**Review by wolfseb — APPROVED** [review]
lgtm

**Review by mpfirrmann — APPROVED** [review]

**Review by xbend — APPROVED** [review]
LGTM

**Review by nstng — APPROVED** [review]

**Review by ajahl — APPROVED** [review]

**Review by Neudrino — APPROVED** [review]

**Pull request merged**
