### PR TITLE
chore(ci): Consolidate Python versions

### PR DESCRIPTION
**Pull request by voisey**
## Summary

Makes the Python versions in the GitHub workflows consistent and the same as the version installed in the magma test VM.

## Test Plan

- [x] CI

### CODE REVIEW

**Review by sebathomas — APPROVED** [review]
Thanks for the clean-up!

**Review by LKreutzer — APPROVED** [review]
Just to make sure that nothing breaks could you start a run on this branch at your fork for the LTE and CWF integ tests?

**Review by nstng — APPROVED** [review]
LGTM - but I did not try all changes manually. Some of the included jobs run afaik only on master.  Please monitor them after the merge.

**Comment by voisey** [comment]
@LKreutzer I've just rebased, but before that the CWF and LTE integ tests passed on my fork:
- CWF: https://github.com/voisey/magma/actions/runs/2622072094
- LTE: https://github.com/voisey/magma/actions/runs/2622072847

@nstng I agree about monitoring them, but looking through some of those that don't run on master but are modified here, I see that some are failing consistently. In particular,
- AGW docker load test: https://github.com/magma/magma/actions/workflows/agw-docker-load-test.yaml
- amis-workflow: https://github.com/magma/magma/actions/workflows/amis-workflow.yml
- Testim check: https://github.com/magma/magma/actions/workflows/testim-workflow.yml

I.e. I won't be able to tell whether this breaks them. What should we do about them?

**Pull request merged**
