### PR TITLE
fix(mme): Skip UE Ctxt Rel timer for S1 Handover

### LINKED ISSUE #11770: [TVM CI Sanity] S1 handover - HO Cancel due to HO Required Timeout -> Pushing Crash Report to Sentry
Issue: S1 handover - HO Cancel due to HO Required Timeout

Scenario: (S1-HO - Ping Pong Scenario)

- UE attach to Source enodeb
- UE moves from Source to Target eNodeb successfully
- UE again Moves Back from Target eNodeb to Source eNodeb (Failled)
-  S-eNodeb initiates "HO Required" to AGW
- AGW Supposed to send "HO Request" to Target eNodeb for HO Resource Allocation, but AGW Fails to initiate "HO request" 
- As there is no resonse for 10 sec TVM eNodeb sends the "HO_Cancel" which crash the AGW services, 

Following are the Observations in mme, syslog and pcaps.

Occurrence start build:
Magma build - 1.7.0-1645602044-5f7c8911

Occurrence Time Stamp: 00:20:28

mmelog: ue context retrival failing
Screen Shot 2022-02-23 at 3 07 48 PM

syslog: sctpd crash
Screen Shot 2022-02-23 at 3 06 06 PM

pcap:  no response in AGW for HO Required with HO request as Context retrieval is failing.
Screen Shot 2022-02-23 at 2 46 23 PM

[s1_handover_01_220223_002014-1.pcapng.zip](https://github.com/magma/magma/files/8128413/s1_handover_01_220223_002014-1.pcapng.zip)
[mmeLog_regression_220223.txt.zip](https://github.com/magma/magma/files/8128414/mmeLog_regression_220223.txt.zip)
[syslog_regression_220223.txt.zip](https://github.com/magma/magma/files/8128415/syslog_regression_220223.txt.zip)

### PR DESCRIPTION
**Pull request by ssanadhya**
Signed-off-by: Shruti Sanadhya <ssanadhya@fb.com>

## Summary

The changes in #11245 added a UE context release request timer. This timer should not be started when UE context release command is sent to source eNB in S1 Handover. This change fixes the issue by adding a check.

This should also fix https://github.com/magma/magma/issues/11770

## Test Plan
1. Bug fix
Before the change, `test_s1_handover.py` was failing since UE was removed right after first handover.
After the change, `test_s1_handover.py` succeeds.

2. LTE integration test
make integ_test

### CODE REVIEW

**Review by ardzoht — APPROVED** [review]
lgtm

**Comment by ulaskozat** [comment]
Can you put more context here? Why do we not need this timer for successful s1 handover?

**Comment by ssanadhya** [comment]
> Can you put more context here? Why do we not need this timer for successful s1 handover?

The changes in #11245 introduced a timer for UE context release command to make sure that UE context is released if the eNB does not send a UE context release complete. 

In the case of S1 handover, the Ue context release command is sent to source eNB  and the Ctxt release timer is started for the same. When the source eNB sends the UE Ctxt Release Complete, it is ignored but the timer is not stopped. When the timer expires, the UE context is deleted, even though the UE is connected to the target eNB, leading to failure while detaching. In this particular scenario, the timer should not be started, since we do not want to clean the UE context if it is moved to target eNB. 

Attaching log in [mme_log_ho_fail_11245.log](https://github.com/magma/magma/files/8130114/mme_log_ho_fail_11245.log) for more clarity.

**Comment by ssanadhya** [comment]
@rsarwad , these chages are passing all LTE integration tests in my local setup. Could you please merge these changes with the changes in #11245 and create a new PR?

**Comment by ssanadhya** [comment]
Closing this PR since #11245 has been reverted in #11771 . These changes will be captured in new version of #11245 .

**Pull request closed without merging**
