### PR TITLE
fix(mme): Replace insecure rand() with getrandom() for TMSI generation

### PR DESCRIPTION
**Pull request by jorgevargasmor**
## Summary

This PR addresses the vulnerability related to predictable TMSI generation in Magma's Mobility Management Entity (MME). It replaces the current insecure method with a more robust approach, enhancing user privacy and security.

## Test Plan

Validate the new TMSI generation method.

## Security Considerations

The new TMSI generation method using `getrandom()` enhances security by providing unpredictable TMSI values, mitigating the risk of tracking user associations by adversaries.

### CODE REVIEW

**Review by panyogesh — APPROVED** [review]
Changes are fine. Please fix the issue reported in build-container job.

**Comment by lucasgonze** [comment]
Let's discuss the fallback to rand() on line 414. Can an attacker force one of these error conditions?

```
EAGAIN The requested entropy was not available, and getrandom()
              would have blocked if the GRND_NONBLOCK flag was not set.

       EFAULT The address referred to by buf is outside the accessible
              address space.

       EINTR  The call was interrupted by a signal handler; see the
              description of how interrupted [read(2)](https://www.man7.org/linux/man-pages/man2/read.2.html) calls on "slow"
              devices are handled with and without the SA_RESTART flag
              in the [signal(7)](https://www.man7.org/linux/man-pages/man7/signal.7.html) man page.

       EINVAL An invalid flag was specified in flags.

       ENOSYS The glibc wrapper function for getrandom() determined that
              the underlying kernel does not implement this system call.
```

**Comment by mehul-jindal** [comment]
Hi @jorgevargasmor please sync `jorgevargasmor:jorge-fix-TMSI-generation` with `master` and replay/rebase the changes of the latest commit on top of it. While committing please use the following command to resolve the remaining failing CI jobs.
```bash
git commit --signoff -s -m "fix(mme): Replace insecure rand with getrandom for TMSI generation"
```

**Comment by jordanvrtanoski** [comment]
The change in this PR was already implemented in a different approach. Closing the PR wit "wont-merge"

**Pull request closed without merging**
