### PR TITLE
chore(mme): Deletes dead code as_messages.c and defns in as_message.h

### PR DESCRIPTION
**Pull request by electronjoe**
Closees #11566.

Discovered as un-compilable during Bazel build effort for MME.

## Test Plan

CI tests which include `make build_oai` and `make test_oai`.

Signed-off-by: Scott Moeller <electronjoe@gmail.com>

### CODE REVIEW

**Comment by electronjoe** [comment]
@ulaskozat The one failing MME test appears to be a flake, I've observed it in ~6 PRs in this set and I can regularly re-run and achieve success.

**Comment by ulaskozat** [comment]
@lionelgo @ssanadhya what is the purpose of MMEprocess.c? These seem to be used by that code?

**Comment by ulaskozat** [comment]
> @ulaskozat The one failing MME test appears to be a flake, I've observed it in ~6 PRs in this set and I can regularly re-run and achieve success.

There is an open task assigned to me to reduce the flakes.

**Comment by ssanadhya** [comment]
> @lionelgo @ssanadhya what is the purpose of MMEprocess.c? These seem to be used by that code?

@ulaskozat , MMEprocess.c is also dead code which @electronjoe is planning to clean up.

**Review by ssanadhya — APPROVED** [review]
LGTM

**Comment by ulaskozat** [comment]
> > @lionelgo @ssanadhya what is the purpose of MMEprocess.c? These seem to be used by that code?
> 
> @ulaskozat , MMEprocess.c is also dead code which @electronjoe is planning to clean up.

shall we include that clean up in this PR?

**Pull request merged**
