### PR TITLE
Prototype PR to enable Docker Build of MME env

### PR DESCRIPTION
**Pull request by electronjoe**
Exploring docker build for MME Docker environment - in support of Issue #5043

### CODE REVIEW

**Comment by rdefosse** [comment]
MAGMA-OAI-TESTS

**Comment by rdefosse** [comment]
MAGMA-OAI-TESTS

**Comment by rdefosse** [comment]
MAGMA-OAI-TESTS

**Comment by rdefosse** [comment]
MAGMA-OAI-TESTS

**Comment by rdefosse** [comment]
@electronjoe 

I was doing some maintenance on our OAI Jenkins server and I had to kill the pending job.

Sorry about it.
Raphael

**Comment by electronjoe** [comment]
Merged Dockerfile.ubuntu20.04 with this capability as part of GH Actions GCC Warnings annotations PR.

**Pull request closed without merging**
