### PR TITLE
Update setup_deb.md

### PR DESCRIPTION
**Pull request by shanku9**
sh agw_install.sh 
logs >>>>
Need to check if both interfaces are named eth0 and eth1
agw_install.sh: 33: agw_install.sh: [[: not found
agw_install.sh: 33: agw_install.sh: [[: not found
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-4.9.0-12-amd64

bash agw_install.sh 
logs >>
Need to check if both interfaces are named eth0 and eth1
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-4.9.0-12-amd64
Found initrd image: /boot/initrd.img-4.9.0-12-amd64
Found linux image: /boot/vmlinuz-4.9.0-9-amd64

### CODE REVIEW

**Comment by tmdzk** [comment]
Thanks for the PR.
@shanku9 can you also change the shebang in the agw_install.sh file ? 
This is for consistency.

**Comment by shanku9** [comment]
updated shebang in agw_install.sh

**Comment by shanku9** [comment]
updated agw deploy guide

**Comment by shanku9** [comment]
new pull request for doc update

**Review by tmdzk — APPROVED** [review]

**Pull request closed without merging**
