### PR TITLE
feat: add support for selecting the default APN per subscriber

### PR DESCRIPTION
**Pull request by AmrElsayyad**
The PR includes changes to enable selection of the default Access Point Name (APN) per subscriber, as different carriers have unique APN settings.

### CODE REVIEW

**Review by jordanvrtanoski — APPROVED** [review]
The feature implementation is alligned with the current architecture.
Code surunding the feature is improved with additional comments.

**Comment by jordanvrtanoski** [comment]
@AmrElsayyad  can you please fix the failed checks so we can merge the PR?

**Comment by AmrElsayyad** [comment]
@jordanvrtanoski Done

**Comment by jordanvrtanoski** [comment]
@AmrElsayyad please check the tests run from NMS Lint & Test flow. The new field in the data model is causing the automated tests to fail as the stubs ware not updated with the new field.

**Comment by AmrElsayyad** [comment]
> @AmrElsayyad please check the tests run from NMS Lint & Test flow. The new field in the data model is causing the automated tests to fail as the stubs ware not updated with the new field.

Fixed the tests

**Comment by jordanvrtanoski** [comment]
@AmrElsayyad thanks for updating the stubs. We still have one more test failing:
```
      201 |     };
      202 |     await waitFor(() => {
    > 203 |       expect(MagmaAPI.apns.lteNetworkIdApnsPost).toHaveBeenCalledWith({
          |                                                  ^
      204 |         networkId,
      205 |         apn: newApn,
      206 |       });

      at toHaveBeenCalledWith (app/views/traffic/__tests__/ApnAddTest.tsx:203:50)
      at runWithExpensiveErrorDiagnosticsDisabled (node_modules/@testing-library/dom/dist/config.js:52:12)
      at checkCallback (node_modules/@testing-library/dom/dist/wait-for.js:141:77)
      at checkRealTimersCallback (node_modules/@testing-library/dom/dist/wait-for.js:133:16)
```

You would need to verify the tests and update the assert/expect where required to consider the new field.

**Comment by AmrElsayyad** [comment]
> @AmrElsayyad thanks for updating the stubs. We still have one more test failing:
> 
> ```
>       201 |     };
>       202 |     await waitFor(() => {
>     > 203 |       expect(MagmaAPI.apns.lteNetworkIdApnsPost).toHaveBeenCalledWith({
>           |                                                  ^
>       204 |         networkId,
>       205 |         apn: newApn,
>       206 |       });
> 
>       at toHaveBeenCalledWith (app/views/traffic/__tests__/ApnAddTest.tsx:203:50)
>       at runWithExpensiveErrorDiagnosticsDisabled (node_modules/@testing-library/dom/dist/config.js:52:12)
>       at checkCallback (node_modules/@testing-library/dom/dist/wait-for.js:141:77)
>       at checkRealTimersCallback (node_modules/@testing-library/dom/dist/wait-for.js:133:16)
> ```
> 
> You would need to verify the tests and update the assert/expect where required to consider the new field. please check the tests run from NMS Lint & Test flow for more details.

Thank you for your patience. I've successfully fixed the failing test now. I apologize for any inconvenience.

**Comment by jordanvrtanoski** [comment]
@AmrElsayyad than you for quickly addressing the issues. There are some additional checks that failed, this time in a different workflow:
```
//lte/gateway/python/magma/subscriberdb/tests:processor_tests            FAILED in 1.1s
  /var/tmp/bazel/execroot/__main__/bazel-out/k8-fastbuild/testlogs/lte/gateway/python/magma/subscriberdb/tests/processor_tests/test.log
//lte/gateway/python/magma/subscriberdb/tests:rpc_tests                  FAILED in 0.9s
  /var/tmp/bazel/execroot/__main__/bazel-out/k8-fastbuild/testlogs/lte/gateway/python/magma/subscriberdb/tests/rpc_tests/test.log
//lte/gateway/python/magma/subscriberdb/tests/store:onready_test         FAILED in 0.7s
  /var/tmp/bazel/execroot/__main__/bazel-out/k8-fastbuild/testlogs/lte/gateway/python/magma/subscriberdb/tests/store/onready_test/test.log
//lte/gateway/python/magma/subscriberdb/tests/store:store_tests          FAILED in 0.9s
  /var/tmp/bazel/execroot/__main__/bazel-out/k8-fastbuild/testlogs/lte/gateway/python/magma/subscriberdb/tests/store/store_tests/test.log
```
I see the latest commit is modifying some of the code under test, so can you please review this test cases and see why they are failing.
The workflow is "AGW Build, Format & Test Bazel / Bazel build and test status (pull_request)"

**Comment by jordanvrtanoski** [comment]
@AmrElsayyad sorry, but we have a new problem. Looks like you had merged the branch with master instead of rebase. There are commits that are causing other checks to fail. You will need:

1. get latest version of master (fetch/pull)
2. cherry-pick the commits relevant for the PR:

- ([d7e5133](https://github.com/magma/magma/pull/15453/commits/d7e51334bcf6b73951ef7db6260954dc3cd15fc6
- [4eef708](https://github.com/magma/magma/pull/15453/commits/4eef708edfe866908b72e9c71071bf11b643886e)
- [3aa77f9](https://github.com/magma/magma/pull/15453/commits/3aa77f90996f5b8a063b66b9d890d639905c2930)

3. force move the head of the branch to the current head `git branch --force default_apn`
4. force push `git push -f`

This should correct the issue with the merge

**Comment by AmrElsayyad** [comment]
@jordanvrtanoski I have updated the branch as you said. I also ran `python3 build.py --tests --up` and it completed successfully. I don't know why the failing workflows fail. I think one of them is related to a Kubernetes test.

**Review by jordanvrtanoski — APPROVED** [review]

**Comment by jordanvrtanoski** [comment]
> @jordanvrtanoski I have updated the branch as you said. I also ran `python3 build.py --tests --up` and it completed successfully. I don't know why the failing workflows fail. I think one of them is related to a Kubernetes test.

@AmrElsayyad some of the tests are flaky, so I restarted them and all of them passed. The PR is merged.

**Comment by AmrElsayyad** [comment]
Thank you @jordanvrtanoski

**Pull request merged**
