### PR TITLE
fix(orc8r): Log entries created from user input

### PR DESCRIPTION
**Pull request by spikey979**
fix(orc8r): Log entries created from user input

## Summary

Added function for string sanitizing before it is written to a log entry.
function works as follows:
it escape special characters in HTML text,
it remove line breaks,
it remove extra whitespace

## Test Plan
ran /magma/orc8r/cloud/docker/  ./build.py -c

For code scanning alerts:
https://github.com/magma/magma/security/code-scanning/35?query=ref%3Arefs%2Fheads%2Fmaster
https://github.com/magma/magma/security/code-scanning/36?query=ref%3Arefs%2Fheads%2Fmaster

### CODE REVIEW

**Comment by uri200** [comment]
I think we can ignore this warning for now
I will consult with the team but I think this is something the linter has introduced recently. So we will have to look into it.


image

**Comment by andreilee** [comment]
@uri200 Was there a consensus? To weigh in, I don't see any reason for us not to sanitize the user input here.

**Comment by uri200** [comment]
Note this seem to have come from a linter error.

Not sure how legit this linter error is. And not sure how many more instances like that we will have.

The log is just printing the content of the variable so we can see the key value. We should t modify that content since then it may mean we are displaying a different key.

**Comment by spikey979** [comment]
On the recommendation of the reviewer, I will close PR as a false positive.

**Pull request closed without merging**
