### PR TITLE
[Converged-MME]ue_context_modification_timer edit.

### PR DESCRIPTION
**Pull request by Vyas20**
[lte][converged-mme][agw]

## Summary

Part of replacing the existing timers with zmq timers, this branch is forked from the branch in PR #4787 and contains ue_context_modification_timer edit.

## Test Plan
Testing with S1-AP Tester and dsTester.

### CODE REVIEW

**Comment by Vyas20** [comment]
MAGMA-OAI-TESTS

**Comment by Vyas20** [comment]
MAGMA-OAI-TESTS

**Comment by Vyas20** [comment]
MAGMA-OAI-TESTS

**Comment by rdefosse** [comment]
MAGMA-OAI-TESTS

**Comment by rdefosse** [comment]
MAGMA-OAI-TESTS

**Review by ulaskozat — CHANGES_REQUESTED** [review]
remove MmeUeContext.h/c and rebase after dependent PRs are merged.

**Comment by Vyas20** [comment]
MAGMA-OAI-TESTS

**Comment by Vyas20** [comment]
MAGMA-OAI-TESTS

**Comment by ulaskozat** [comment]
RestartIntegrationTests

**Review by ulaskozat — APPROVED** [review]
Looks good.

**Pull request merged**
