### PR TITLE
[orc8r][agw] Add default GW support for static SGi MGMT IP

### LINKED ISSUE #3047: Can't configure gateway for SGi Management Interface
### Your Environment

- **Version:** 1.2
- **Affected Component:** Orchestrator, Access Gateway
- **Deployment Environment:** e.g. AWS (orc8r), bare-metal (AGW)

### Describe the Issue

I'm following [the documentation](https://magma.github.io/magma/docs/howtos/config_agw_bridged#agw-management-traffic).
My aim is to configure static IP for SGi Management Interface. The configuration itself works well and static IP was configured on the `uplink_br0` interface.

The problem is that there is no way to specify static gateway and this breaks connectivity to the orc8r.
I've checked the code and realized, that this feature just not yet implemented.

I believe that in order to implement this, we need:
1) extend API with a new field;
2) extend protobuf for pipelined config;
3) implement handling of this new configuration field inside of pipelined.

### PR DESCRIPTION
**Pull request by berezovskyi-oleksandr**
Signed-off-by: Oleksandr Berezovskyi <berezovskyi.oleksandr@gmail.com>

## Summary

Fixes #3047

Add support to specify default gateway for static SGi Management Interface.
This is needed for the case of static IP assignment, which causes loosing of the default gateway and might lead to a lack of connection to orc8r.

## Test Plan

`make test`
Manually tested this feature on AGW.

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by pshelar** [comment]
@berezovskyi-oleksandr Patch looks good, But I think you also need to update lte/cloud/go/services/lte/servicers/builder_servicer.go to map API config to gateway mconfig. also Add unit test in lte/cloud/go/services/lte/servicers/builder_servicer_test.go.

**Review by pshelar — CHANGES_REQUESTED** [review]
need mconfig related changes.

**Comment by berezovskyi-oleksandr** [comment]
@pshelar thanks for review. I've fixed the points you've mentioned. Please take a look

**Comment by pshelar** [comment]
@berezovskyi-oleksandr Patch looks good, But I am seeing error in `make test` in UplinkBridgeWithNonNATTest_IP_VLAN_GW.
can you fix it.

**Comment by berezovskyi-oleksandr** [comment]
@pshelar , sorry for that. Forgot to run it after rebase to master. Please try again

**Review by pshelar — APPROVED** [review]

**Review by mpgermano — APPROVED** [review]

**Review by xjtian — APPROVED** [review]

**Comment by xjtian** [comment]
@pshelar confirmed LTE integ tests passed on a local checkout

**Pull request merged**
