### PR TITLE
[CI] Move yamllint_config.yml to config directory, fixup triggers

### PR DESCRIPTION
**Pull request by electronjoe**
The yamllint_config was being interpreted as a github action. I'm not clear how this succeeded in my testing =D

While here, moving to a more clear Check top level name for better UI visibility. Also refining the trigger conditions.

Signed-off-by: Scott Harrison Moeller <smoeller@fb.com>

### CODE REVIEW

**Comment by rdefosse** [comment]
@electronjoe 

Is this why we keep receiving emails when pushing to our fork repos?

**Comment by electronjoe** [comment]
@rdefosse are the emails coming from Github?

I'm not receiving GH Emails. CircleCI spams me all the time to the point that I don't pay attention.

**Comment by electronjoe** [comment]
@rdefosse nevermind, yes this is the cause of the emails (at least I'm getting them for my fork).

**Comment by electronjoe** [comment]
@rdefosse adding you as reviewer, if you want to LGTM I'll merge

**Review by hcgatewood — APPROVED** [review]

**Pull request merged**
