### PR TITLE
docs: Update Docusaurus Versioning System

### PR DESCRIPTION
**Pull request by jaredmullane**
Signed-off-by: Jared Mullane <jmullane@fb.com>

## Summary

Updated Docusaurus versioning system to move from base release format to ".X" release format (Ex. 1.6.0 to 1.6.X) so that users are not confused as to if they are on the latest version. 

## Test Plan

cd ${MAGMA_ROOT}/docs && make precommit
cd ${MAGMA_ROOT}/docs && make precommit_fix

Screen Shot 2021-12-09 at 6 50 09 PM

### CODE REVIEW

**Review by hcgatewood — APPROVED** [review]
Given the size of this PR, just gonna assume you thoroughly checked it and give you the lgtm 🙂

**Comment by jaredmullane** [comment]
@hcgatewood there is a neat little ```yarn run rename-version``` script that makes the renaming of versions fairly easy versus changing 300 files manually.

**Comment by hcgatewood** [comment]
> @hcgatewood there is a neat little `yarn run rename-version` script that makes the renaming of versions fairly easy versus changing 300 files manually.

Nice, good to know!

**Comment by jaredmullane** [comment]
The script doesn't update all the sidebars apparently so I'll have to update some of the doc IDs manually.

**Comment by jaredmullane** [comment]
@hcgatewood had to manually update some of the document IDs to get the sidebars to accurately populate but everything looks good on my end now pending these final checks.

**Comment by themarwhal** [comment]
Hi @jaredmullane you might have to rebase :'(

**Comment by jaredmullane** [comment]
Thanks @themarwhal ! I created a new PR here https://github.com/magma/magma/pull/11148

**Pull request closed without merging**
