### PR TITLE
refactor(orc8r): Move cloud/go/obsidian to cloud/go/services

### PR DESCRIPTION
**Pull request by MoritzThomasHuebner**
## Summary

Obsidian should live among the other services in `orc8r/cloud/go/services`.

For this PR I have
- Moved the package
- Changed paths across magma to reflect the move
- Ran `go clean_gen` to properly recreate the `obsidian/swagger/protos/swagger.pb.go` file
- There is an update required for the CODEOWNERS file for which I will create a separate PR.
- CodeQL tests are highlighting a known logging vulnerability. This issue existed prior to this PR and there is no consensus yet on how too solve this. See [11738](https://github.com/magma/magma/pull/11738).

Edit:
I rebased this onto #12725, and it should thus be merged after that PR. The diff currently also shows changes from #12725 until it is merged.

## Test Plan

Run unit tests

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by xbend — APPROVED** [review]
Domain Proxy part LGTM.

**Review by nstng — APPROVED** [review]
CI changes LGTM

**Review by ShubhamTatvamasi — APPROVED** [review]

**Review by maxhbr — APPROVED** [review]
LGTM

**Review by maxhbr — APPROVED** [review]
LGTM

**Review by uri200 — APPROVED** [review]

**Pull request merged**
