### PR TITLE
Create a core superbuild

### PR DESCRIPTION
**Pull request by amarpad**
## Create a core super build that depends on common libraries

This prevents the implicit ordering of builds between common and core and
adds an explicit, DEPENDS directive followed by find_packages for importing
exported common library targets.

Signed-off-by: Amar Padmanabhan <amarpadmanabhan@fb.com>

## Test Plan
make integ_test

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by themarwhal — APPROVED** [review]

**Review by ardzoht — APPROVED** [review]

**Comment by rdefosse** [comment]
@amarpad 

Hello Amar,

nice PR.

in `ci-scripts/docker/Dockerfile.mme.ci.rhel8`  add the `liblsan` to the target image

```bash
diff --git a/ci-scripts/docker/Dockerfile.mme.ci.rhel8 b/ci-scripts/docker/Dockerfile.mme.ci.rhel8
index 2e1d29a07..7dd777005 100644
--- a/ci-scripts/docker/Dockerfile.mme.ci.rhel8
+++ b/ci-scripts/docker/Dockerfile.mme.ci.rhel8
@@ -34,6 +34,7 @@ RUN yum update -y && \
     yum -y install --enablerepo="ubi-8-codeready-builder" \
       libubsan \
       libasan \
+      liblsan \
       psmisc \
       tcpdump \
       openssl \
```

Same modification on `lte/gateway/docker/mme/Dockerfile.rhel8` line 550

Regards
Raphael

**Comment by themarwhal** [comment]
Do paths like `/vagrant/c/core/...` work in docker builds? (It looks like they do because the tests are passing. :) ) But do we always have a `/vagrant` directory?

**Comment by amarpad** [comment]
> @amarpad
> 
> Hello Amar,
> 
> nice PR.
> 
> in `ci-scripts/docker/Dockerfile.mme.ci.rhel8` add the `liblsan` to the target image
> 
> ```shell
> diff --git a/ci-scripts/docker/Dockerfile.mme.ci.rhel8 b/ci-scripts/docker/Dockerfile.mme.ci.rhel8
> index 2e1d29a07..7dd777005 100644
> --- a/ci-scripts/docker/Dockerfile.mme.ci.rhel8
> +++ b/ci-scripts/docker/Dockerfile.mme.ci.rhel8
> @@ -34,6 +34,7 @@ RUN yum update -y && \
>      yum -y install --enablerepo="ubi-8-codeready-builder" \
>        libubsan \
>        libasan \
> +      liblsan \
>        psmisc \
>        tcpdump \
>        openssl \
> ```
> 
> Same modification on `lte/gateway/docker/mme/Dockerfile.rhel8` line 550
> 
> Regards
> Raphael

Good point, sorry I marked the review as draft, I will fixup what you suggest and also a couple of other errors like some of the files are showing up as add and delete instead of move, and then republish it for review. Thanks again.

**Comment by amarpad** [comment]
> Do paths like `/vagrant/c/core/...` work in docker builds? (It looks like they do because the tests are passing. :) ) But do we always have a `/vagrant` directory?

That is actually a symlink, I am trying to understand why it gets created, every now and then git move gets confused and my tree gets dirty. I will fix it and push an updated patch, once I figure it out.

**Comment by rdefosse** [comment]
> 
> 
> > @amarpad
> > Hello Amar,
> > nice PR.
> > in `ci-scripts/docker/Dockerfile.mme.ci.rhel8` add the `liblsan` to the target image
> > ```shell
> > diff --git a/ci-scripts/docker/Dockerfile.mme.ci.rhel8 b/ci-scripts/docker/Dockerfile.mme.ci.rhel8
> > index 2e1d29a07..7dd777005 100644
> > --- a/ci-scripts/docker/Dockerfile.mme.ci.rhel8
> > +++ b/ci-scripts/docker/Dockerfile.mme.ci.rhel8
> > @@ -34,6 +34,7 @@ RUN yum update -y && \
> >      yum -y install --enablerepo="ubi-8-codeready-builder" \
> >        libubsan \
> >        libasan \
> > +      liblsan \
> >        psmisc \
> >        tcpdump \
> >        openssl \
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Same modification on `lte/gateway/docker/mme/Dockerfile.rhel8` line 550
> > Regards
> > Raphael
> 
> Good point, sorry I marked the review as draft, I will fixup what you suggest and also a couple of other errors like some of the files are showing up as add and delete instead of move, and then republish it for review. Thanks again.

No problem. I am still running the "Draft" PRs on the OAI pipeline. At least you have a good preview of any issues!

**Comment by amarpad** [comment]
> > > @amarpad
> > > Hello Amar,
> > > nice PR.
> > > in `ci-scripts/docker/Dockerfile.mme.ci.rhel8` add the `liblsan` to the target image
> > > ```shell
> > > diff --git a/ci-scripts/docker/Dockerfile.mme.ci.rhel8 b/ci-scripts/docker/Dockerfile.mme.ci.rhel8
> > > index 2e1d29a07..7dd777005 100644
> > > --- a/ci-scripts/docker/Dockerfile.mme.ci.rhel8
> > > +++ b/ci-scripts/docker/Dockerfile.mme.ci.rhel8
> > > @@ -34,6 +34,7 @@ RUN yum update -y && \
> > >      yum -y install --enablerepo="ubi-8-codeready-builder" \
> > >        libubsan \
> > >        libasan \
> > > +      liblsan \
> > >        psmisc \
> > >        tcpdump \
> > >        openssl \
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Same modification on `lte/gateway/docker/mme/Dockerfile.rhel8` line 550
> > > Regards
> > > Raphael
> > 
> > 
> > Good point, sorry I marked the review as draft, I will fixup what you suggest and also a couple of other errors like some of the files are showing up as add and delete instead of move, and then republish it for review. Thanks again.
> 
> No problem. I am still running the "Draft" PRs on the OAI pipeline. At least you have a good preview of any issues!

@rdefosse I couldn't figure out where the failure was happening based on the Jenkins logs I downloaded. I did apply the patch that you suggested and repushed a build. I will try to see what happens next. Do you know why I needed to add this directive? I haven't changed anything relating to lsan. Is it some funky dependency that used to get captured?

**Comment by rdefosse** [comment]
> 
> 
> > > > @amarpad
> > > > Hello Amar,
> > > > nice PR.
> > > > in `ci-scripts/docker/Dockerfile.mme.ci.rhel8` add the `liblsan` to the target image
> > > > ```shell
> > > > diff --git a/ci-scripts/docker/Dockerfile.mme.ci.rhel8 b/ci-scripts/docker/Dockerfile.mme.ci.rhel8
> > > > index 2e1d29a07..7dd777005 100644
> > > > --- a/ci-scripts/docker/Dockerfile.mme.ci.rhel8
> > > > +++ b/ci-scripts/docker/Dockerfile.mme.ci.rhel8
> > > > @@ -34,6 +34,7 @@ RUN yum update -y && \
> > > >      yum -y install --enablerepo="ubi-8-codeready-builder" \
> > > >        libubsan \
> > > >        libasan \
> > > > +      liblsan \
> > > >        psmisc \
> > > >        tcpdump \
> > > >        openssl \
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Same modification on `lte/gateway/docker/mme/Dockerfile.rhel8` line 550
> > > > Regards
> > > > Raphael
> > > 
> > > 
> > > Good point, sorry I marked the review as draft, I will fixup what you suggest and also a couple of other errors like some of the files are showing up as add and delete instead of move, and then republish it for review. Thanks again.
> > 
> > 
> > No problem. I am still running the "Draft" PRs on the OAI pipeline. At least you have a good preview of any issues!
> 
> @rdefosse I couldn't figure out where the failure was happening based on the Jenkins logs I downloaded. I did apply the patch that you suggested and repushed a build. I will try to see what happens next. Do you know why I needed to add this directive? I haven't changed anything relating to lsan. Is it some funky dependency that used to get captured?

@amarpad 

I've added lately a `RHEL8` simple sanity check deployment test.

It is in a child pipeline and I forgot to add the artifact of this child pipeline to the face-front pipeline in case of errors.

Sorry for the inconvenience

Your last build looks good!

**Comment by rdefosse** [comment]
@amarpad 

I made a fix on my pipeline based on your feedback --> [commit](https://github.com/magma/magma/pull/7043/commits/26e9fe8a658b8463ef03efd1280538471f1c441d)

**Comment by amarpad** [comment]
@themarwhal I have been able to fix the symlinks but the three cmakes are still showing up as add and remove. udp, nas5g and redis_client. Since the change is cosmetic, I am hoping it is ok with you. Please take a look at your convenience.

**Comment by amarpad** [comment]
@rdefosse do you have any suggestions on how I can debug the two failing Jenkins tests?

**Comment by themarwhal** [comment]
> @rdefosse do you have any suggestions on how I can debug the two failing Jenkins tests?

If you mean `Jenkins LTE` and `Jenkins`, I think they are very flaky :/ . It's easiest to just run some tests locally.

**Comment by amarpad** [comment]
> > @rdefosse do you have any suggestions on how I can debug the two failing Jenkins tests?
> 
> If you mean `Jenkins LTE` and `Jenkins`, I think they are very flaky :/ . It's easiest to just run some tests locally.

other than make integ_tests what is interesting? Sorry just ramping back :D

**Comment by themarwhal** [comment]
> > > @rdefosse do you have any suggestions on how I can debug the two failing Jenkins tests?
> > 
> > 
> > If you mean `Jenkins LTE` and `Jenkins`, I think they are very flaky :/ . It's easiest to just run some tests locally.
> 
> other than make integ_tests what is interesting? Sorry just ramping back :D

I think running s1ap tests locally is good enough. All the C/C++ unit tests are covered in the CI checks. :)

**Review by themarwhal — APPROVED** [review]

**Comment by amarpad** [comment]
> > > > @rdefosse do you have any suggestions on how I can debug the two failing Jenkins tests?
> > > 
> > > 
> > > If you mean `Jenkins LTE` and `Jenkins`, I think they are very flaky :/ . It's easiest to just run some tests locally.
> > 
> > 
> > other than make integ_tests what is interesting? Sorry just ramping back :D
> 
> I think running s1ap tests locally is good enough. All the C/C++ unit tests are covered in the CI checks. :)

ok figured it out, the vagrant path is not pointing to the correct directory, I hand fixed it in my vagrant box but didn't update the provisioning script. I will push a fix over the weekend. Thanks for the pointers.

**Comment by amarpad** [comment]
Despite the Jenkins failures, the s1ap integration tests pass on my setup.

**Review by rdefosse — APPROVED** [review]

**Review by themarwhal — APPROVED** [review]

**Pull request merged**
