### PR TITLE
[Proposal] Requirements document for vendor neutral domain proxy

### PR DESCRIPTION
**Pull request by jpad-freedomfi**
Signed-off-by: jpad-freedomfi <61293007+jpad-freedomfi@users.noreply.github.com>

 [lte][orc8r]
## Summary
This document has the requirements for a vendor neutral domain proxy. The idea is to create an open source domain proxy that can support CBRS eNBs from different vendors. 

## Test Plan
The test plan will be the WInnForum test harnesses and test plans.

### CODE REVIEW

**Review by karthiksubraveti — COMMENTED** [review]
@jpad-freedomfi Do you have any thoughts on how the domain proxy is going to be managed, I would think despite it being a separate component, might be nice to be managed and deployed along with Orc8r in magma deployments. Additionally also will be good to share the UI with NMS. wdyt ?

**Comment by jpad-freedomfi** [comment]
@karthiksubraveti I think both of those are good suggestions. While initially thought of as a separate entity the long term goal is to have the DP integrated with Magma NMS. So yes, having it deployable alongside orc8r and having the UI match NMS make a lot of sense.

**Review by karthiksubraveti — APPROVED** [review]

**Comment by electronjoe** [comment]
@jpad-freedomfi , I didn't see this PR coming in, sorry!  We have a process for Proposals and it's excellent that you have a Design doc to commit to this proposals directory (which is part of the process). But this Design Doc PR needs a GH Issue for the Proposal, which would be used for broader discussion and final consensus on the Proposal.  See the Proposal process outlined [Here](https://github.com/magma/magma/tree/master/docs/readmes/proposals). Can you create a GH Issue for your proposal, and add a back-reference to this PR (via Github UI at right)? Magma team has comments on the proposal and this is where we would want them to be carried out.

**Comment by jpad-freedomfi** [comment]
@electronjoe I created an issue here https://github.com/magma/magma/issues/5514. Then I created this PR. Can you help me understand what steps I missed in the intended flow? Also, how do I back-reference this to the linked issue? Do I just put the link to this PR in the issue? or in the comments on the issue?

**Comment by jpad-freedomfi** [comment]
@tjj-freedomfi FYI conversation ^^ regarding the proposal process

**Comment by electronjoe** [comment]
Aah, apologies! I missed that GH Issue. My fault! Let me tag that issue in this PR so it's traceable.

**Comment by jpad-freedomfi** [comment]
no worries. did I do the type:proposal correctly? I wasn't sure how to add the label the design process doc is refers to.

**Comment by jpad-freedomfi** [comment]
Nope, I didn't. I just added type:proposal as a label. I see how to do it now.

**Pull request merged**
