### PR TITLE
refactor(orc8r): FegRelay servicers as External

### PR DESCRIPTION
**Pull request by sabithaatla**
Signed-off-by: root <sabitha.atla@wavelabs.ai>
## Summary

This PR deals with the segregation of FegRelay external gRPC servicers implementation.
These changes are part of the ongoing work which details the distinction between Orc8r-internal gRPC endpoints vs. external, gateway-oriented gRPC endpoints.
Created southbound folder under Servicers to move the external end points

Verified existing UT cases.

This PR was done as part of discussion by @hcgatewood [RemoveGatewayAccess toOrc8r-InternalEndpoints](https://drive.google.com/file/d/1NO6Qd6rU80xPh0Sb0mKWlSfDt0JbeVIT/view)

## Test Plan

All test cases passed

### CODE REVIEW

**Comment by sabithaatla** [comment]
@hcgatewood  Requesting to review

**Review by hcgatewood — APPROVED** [review]

**Comment by sabithaatla** [comment]
@hcgatewood  Requesting Merge

**Comment by hcgatewood** [comment]
@themarwhal can you stamp when have time

**Review by themarwhal — APPROVED** [review]

**Comment by sabithaatla** [comment]
@hcgatewood Requesting to Merge this PR

**Comment by sabithaatla** [comment]
@hcgatewood Please Merge this PR

**Pull request merged**
