### PR TITLE
[docs] Adding proposal for VPN configuration from API

### PR DESCRIPTION
**Pull request by ardzoht**
## Summary

- Added md file that specifies design doc for VPN configuration from API goal
- Added Proposals section to docs sidebar

## Test Plan

- Ran `./create_docusaurus_website.sh` script to test docs locally

image

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by tmdzk** [comment]
@xjtian should we do all proposal directly on magma.github.io (https://github.com/magma/magma) ?

**Review by xjtian — CHANGES_REQUESTED** [review]
OK cool so a few things:

- We can deploy an openVPN server to k8s today using https://hub.helm.sh/charts/stable/openvpn (code at https://github.com/helm/charts/tree/master/stable/openvpn)
- This vpn server can use a persistent volume in k8s to store all the client keys
- So we can add some extra functionality to bootstrapper to wrap the management of the on-disk client keys with some RPC interface, and send those down to the gateway after a successful bootstrap. We can mount the same PVC that the openvpn server uses for the client keys onto the bootstrapper service, this is how we will get bootstrapper to communicate with openvpn.

Check out that helm chart and the scripts inside, or you can kubectl into the one we have running on staging for the CI cluster. All the scripts and stuff are under `/etc/openvpn`.

**Comment by 119Vik** [comment]
Can one of the admins verify this patch?

**Review by xjtian — CHANGES_REQUESTED** [review]
Can you flesh this out a little more for me?

- How are you going to change the bootstrapper RPC interface
- Any REST API changes to make? I think enabling VPN should be a flag beyond just adding the service to the dynamic_services config
- Who's the target user for the VPN? SI or individual tenant of the system? If the latter, we might need to figure out a way to isolate different subsets of clients. I think this should be limited to the operator of the whole system.
- How will a user access a specific gateway? OpenVPN by default comes up with client-to-client disabled, do we want to enable that? It seems a bit dangerous to me as you'd be able to access and compromise any other AGW on the system by compromising a single one. But then the story for SSHing is a little more complicated because ovpn is running in a pod so you'll have to kubectl exec into the pod first before SSHing to a specific client.

**Comment by ardzoht** [comment]
@xjtian Added details for boostrapper process RPC extension, REST API updates, and client VPN gateway usage.

**Comment by shaddi** [comment]
Great to see this progressing. A few thoughts:

1. Enabling long-lived, persistent VPN sessions to AGWs is an anti-pattern we probably don't want to support -- among other issues, OpenVPN has some scalability challenges with large numbers of clients, and shell access to an AGW should be a last-ditch resort for administrative tasks. Consider default short-lived certs for this.
1. Why not expose an API along the lines of `enableShell`/`disableShell` (again, with short timeout) to abstract the details of VPN implementation from the user? In time, we may want to switch to newer VPN mechanisms (e.g., once Wireguard gets mainlined).
1. If I understand correctly, the proposal is to generating a separate OpenVPN client key/cert in the orc8r, then hand that to the AGW. I would suggest generating keys on the client, and sending a cert signing request to the bootstrapper to remove the need for sending private key material over the WAN.
1. OpenVPN config nit, we should be using UDP by default for performance reasons, and falling back to TCP where necessary.
1. Does setting up a jumphost, etc fall within scope for this proposal? (Ideally folks aren't ssh'ing to the VPN server in production)

**Comment by ardzoht** [comment]
@shaddi 

I agree with 1), as of now we're defining 2 types of valid durations (12 hours for support teams, and 10 years for GW team). I think we can align this on 12 hours by default for everyone. Also these will be rotated and aligned with the gateway certs. 
For 3), I think we can define an interface to call the bootstrapper like `RequestCert` function and return the signed certificate.
4) We can define that as a config parameter for the REST API endpoint, setting the default as UDP but to give the option to fallback to TCP. What do you think?
And for 5), I think we can look to setup a jumpserver as next step / improvement, I'd think this could be achievable with a pod on k8s to act as the jumphost, @xjtian might have better thoughts on this.

**Comment by shaddi** [comment]
Makes sense. To your question on 4, I generally feel like this is an implementation detail that shouldn't be exposed in the API (getting back to 2 above).

**Comment by jpad-freedomfi** [comment]
@ardzoht and @shaddi 

This is great to see. We on the FreedomFi team had been discussing a similar problem statement. A couple of comments and questions:


1. Whole heartedly support the notion of "shell access to an AGW should be a last-ditch resort for administrative tasks." But in early stage deployments, it has been needed regularly until we solidify deployment models and associated configurations. 

1. I very much support the NMS based enableShell/disableShell idea.

1. If I'm following the current plan, it is very dependent on the connection to orc8r being operational, it that correct? If so, one of the primary use cases we have had early on for shell access has been when initially deployed AGWs have issues establishing the connection to the orc8r. In our proposal, we were thinking shell connection would follow the logic below
   1. Shell access is enabled on boot by default (or perhaps after some backoff timer)
   1. If connection to orc8r is confirmed, shell access is governed by orc8r setting
        1. enableShell starts connection
        1. disableShell stops connection
   1. If connection is orc8r is lost, shell connection is enabled after timer expiration of x minutes. x = TBD. 

#3 above would help with configuration issues when IP networking is functional. Any thoughts on how that use case can be supported with your current plan?

**Comment by ardzoht** [comment]
@jpad-freedomfi 

Thanks for your input and thoughts. 

You are correct, the main idea behind this is having the client validated through the orc8r connection, as well as deploying the VPN server on k8s along with it. I see one of your concerns is having this as a dependency, as it will have to wait for an established connection / certification with orc8r, one of the options to tackle this would be adding a separate connection on the service wrapper on the gateway separated from the orc8r one, not governed by the openVPN server. 

Having said that I feel this defeats the purpose of having the authentication we use with orc8r (we would have to pre-provision the client with auth keys) and it would require a separate tunnel to connect to. But if this is a primary use case we can chat more on this.

**Comment by xjtian** [comment]
@jpad-freedomfi if the primary motivation for this feature request is for freshly installed AGW's encountering connectivity problems, I think this use case might be best served "out of band" from core magma functionality, so to speak. Not allowing unathenticated hardware to communicate with Orchestrator application components (apart from the bootstrapper) is a pretty foundational security principle for us so I'm not in love with the idea of opening up some sort of jumphost/vpn server to unauthenticated hardware.

I do see value in Alex's proposal here for a managed VPN setup to gain access to boxes in a last-resort scenario. If we do move forward with this, it will definitely be through some authenticated RPC interface. If that doesn't work for the use cases that you need shell access for, maybe you can look into some sidecar functionality for your specific deployments.

**Comment by amarpad** [comment]
I think the logic to connect back to the orc8r needs to be simple enough that we should assume that it is almost at the same level as a tcp connection (plus some certificate). So, I am biased towards assuming the orc8r is available
It will be good for us to track the number of times an orc8r connection is wedged but ssh is available going forward, that will also inform us of the need for some side car mechanism. This will help us embark on the more complex approach based on concrete data vs a hunch that the orc8r might not be available.

**Comment by amarpad** [comment]
Note: A more common model for network devices would be to check point configuration and then rollback when the node can't ping home. Since we don't have managed config for the AGW this is harder to implement (as we are pure linux distro config files).

**Comment by jpad-freedomfi** [comment]
Ok. Willing to concede our initial 2 for 2 was newb user (me) learning curve issues. But I like Amar's idea of tracking to validate if we got unlucky or if it happens to others. FWIW we had orc8r URL issues in first two deployments. Is there a way to recover from a wrong orc8r URL in the AGW config without SSH access once the unit is remote?

**Comment by xjtian** [comment]
@jpad-freedomfi That is a specific scenario where you'd be totally hosed without access to the box, yes. In our field deployments, we do the installation and verify connectivity with orc8r in a controlled setting (e.g. lab) before installing hardware in the field.

**Comment by jpad-freedomfi** [comment]
@xjtian ok. So in that case this is a new topic. As Magma scales, and AGWs get produced and deployed in the 100's and 1000's, how do we handle provisioning customer specific orc8r URLs on a unit without touching every box between factory and field? 

Maybe we start a new/separate topic for this.

**Comment by jpad-freedomfi** [comment]
@119Vik see discussion above.

**Comment by shaddi** [comment]
@jpad-freedomfi, I think the scenario you're describing is out of scope for this PR, though important. Perhaps we can create a new issue to track this. In general, provisioning different orc8r URLs is something you could consider baking in to your hardware provisioning process, since migrating an AGW across orc8r instances is a disruptive activity (as it by definition requires replacing all AGW configuration state). I could imagine a "AGW export and migration" service to help automate migration from one orc8r to another, if this is a use case that can't be handled at hardware provisioning.

**Comment by amarpad** [comment]
We had a health check CLI that would validate that the RPC and stuff is up, maybe we just bake that in as part of the process to image a GW. Not sure I remember who worked on it even.

**Review by xjtian — APPROVED** [review]
At this point the proposal doc basically lgtm, what's left is to decide if we actually want to take the time to implement this.

**Pull request merged**
