### PR TITLE
fix(agw): protobuf py files for agw are created

### LINKED ISSUE #13033: Py protobuf files in magma debian build are created
**Problem**
* magma debian packages in the magma artifactory do not have python protobuf files
* e.g. `$ dpkg -c ~/magma/magma_1.8.0-1654249857-334c4a37_amd64.deb | grep mconfigs`
```
-rw-r--r-- 0/0            2398 2022-06-03 08:08 ./usr/local/lib/python3.8/dist-packages/magma/configuration/mconfigs.py
```
* expected: `$ dpkg -c ~/magma/magma_1.8.0-1654243827-1a1e2b33_amd64.deb | grep mconfigs`
```
-rw-r--r-- 0/0             159 2022-06-03 08:13 ./usr/local/lib/python3.8/dist-packages/orc8r/protos/mconfig/mconfigs_pb2_grpc.py
-rw-r--r-- 0/0           10219 2022-06-03 08:13 ./usr/local/lib/python3.8/dist-packages/orc8r/protos/mconfig/mconfigs_pb2.py
-rw-r--r-- 0/0           11901 2022-06-03 08:13 ./usr/local/lib/python3.8/dist-packages/orc8r/protos/mconfig/mconfigs_pb2.pyi
-rw-r--r-- 0/0            2398 2022-06-03 06:37 ./usr/local/lib/python3.8/dist-packages/magma/configuration/mconfigs.py
-rw-r--r-- 0/0             159 2022-06-03 08:13 ./usr/local/lib/python3.8/dist-packages/feg/protos/mconfig/mconfigs_pb2_grpc.py
-rw-r--r-- 0/0           20947 2022-06-03 08:13 ./usr/local/lib/python3.8/dist-packages/feg/protos/mconfig/mconfigs_pb2.py
-rw-r--r-- 0/0           33002 2022-06-03 08:13 ./usr/local/lib/python3.8/dist-packages/feg/protos/mconfig/mconfigs_pb2.pyi
-rw-r--r-- 0/0             159 2022-06-03 08:13 ./usr/local/lib/python3.8/dist-packages/lte/protos/mconfig/mconfigs_pb2_grpc.py
-rw-r--r-- 0/0           32234 2022-06-03 08:13 ./usr/local/lib/python3.8/dist-packages/lte/protos/mconfig/mconfigs_pb2.py
-rw-r--r-- 0/0           52192 2022-06-03 08:13 ./usr/local/lib/python3.8/dist-packages/lte/protos/mconfig/mconfigs_pb2.pyi
```

**Analysis**
* The magma debian package is created in the build_all workflow - boiled down the following is executed
  * `lte/gateway$ ./release/pydep finddep --install-from-repo -b --build-output ~/magma-deps -l ./release/magma.lockfile.ubuntu python/setup.py $MAGMA_ROOT/orc8r/gateway/python/setup.py`
    * analyses and setups magma debian dependencies
    * ! this installs python protobuf 3.19.0 from the magma artifactory
    * if protobuf 3.19.0 is not in the artifactory then `python3-protobuf_3.19.0` is created and uploaded
  * `./release/build-magma.sh -h 123 --commit-count 23 -t RelWithDebInfo --cert $MAGMA_ROOT/.cache/test_certs/rootCA.pem --proxy $MAGMA_ROOT/lte/gateway/configs/control_proxy.yml --os ubuntu`
    * build magma and package as .deb
    * this builds python protobuf files based on python protobuf 3.19.0 from above
* magma python protobuf files can not be created with the setup above (`~/magma/(lte|orc8r)/gateway/python$ make protos`)
```
Traceback (most recent call last):
  File "/usr/local/bin/protoc-gen-mypy", line 5, in <module>
    from mypy_protobuf.main import main
  File "/usr/local/lib/python3.8/dist-packages/mypy_protobuf/main.py", line 22, in <module>
    import google.protobuf.descriptor_pb2 as d
  File "/usr/local/lib/python3.8/dist-packages/google/protobuf/descriptor_pb2.py", line 5, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/usr/local/lib/python3.8/dist-packages/google/protobuf/descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
AttributeError: module 'google.protobuf.internal.containers' has no attribute 'MutableMapping'
--mypy_out: protoc-gen-mypy: Plugin failed with status code 1.
```
  * See https://github.com/protocolbuffers/protobuf/issues 9180 (should be fixed with protobuf 3.20)
* protobuf was upgraded in magma with https://github.com/magma/magma/pull/11698 - this was several month ago. Why is this an issue now?
  * before the artifactory switch `pydep` was based on the fb artifactory and artifacts were written to the magma artifactory. I.e., `python3-protobuf_3.19` was written to the magma artifactory. But from the fb artifactory protobuf 3.14 was installed.

**Approach**
* upgrade protobuf in magma to 3.20.1 - does this have side effects?

### PR DESCRIPTION
**Pull request by nstng**
Signed-off-by: Nils Semmelrock <nils.semmelrock@tngtech.com>

## Summary

See #13033

## Test Plan

See #13033

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by sebathomas** [comment]
The pylint error seems to be a known problem of the new protobuf version, see:
https://github.com/protocolbuffers/protobuf/issues/9730

It's probably safe to disable the check via `# pylint: disable=no-name-in-module`

**Comment by ardzoht** [comment]
Have we verified that the new version is also pulled in magma_test VM?

**Review by ardzoht — APPROVED** [review]
lgtm

**Review by sebathomas — APPROVED** [review]

**Review by vktng — APPROVED** [review]
LGTM.

**Pull request merged**
