### PR TITLE
Test build time fresh

### PR DESCRIPTION
**Pull request by themarwhal**
## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by rdefosse** [comment]
@themarwhal 

This fails on `OAI CI` pipeline because `bazel` is not the base image used to build `sctpd`

**Comment by rdefosse** [comment]
@themarwhal 

we will need to add `bazel` in my dockerfiles (`lte/gateway/docker/mme`) to make sure it is the build from scratch when we will merge this PR

**Comment by themarwhal** [comment]
@rdefosse Thanks for letting me know! (I only had this PR up to test some build time related things so I am not planning on merging this, but I did not think to migrate the OAI jenkins job for the eventual migration.)

I'll file a task for this, thanks for flagging!

**Comment by rdefosse** [comment]
@themarwhal 

what is the status on this PR?

You need to resync and re-run CI.

Raphael

**Pull request closed without merging**
