### PR TITLE
Fix orc8r proxy service name for bootstrapper.

### PR DESCRIPTION
**Pull request by reddydodda**
Signed-off-by: reddydodda <reddydodda@gmail.com>

### CODE REVIEW

**Comment by reddydodda** [comment]
@xjtian @mpgermano  Please review. this need to be fixed as per nghttpx_open template

https://github.com/facebookincubator/magma/blob/master/orc8r/cloud/docker/proxy/templates/nghttpx_open.conf.j2#L49

**Comment by xjtian** [comment]
Oh right because we're not using external DNS resolution in the MCP stack right? In our prod, we have DNS bootstrapper-controller.magma.etagecom.io pointing to this service on port 443.

This is kinda tricky because the service name will depend on the controller hostname for k8s DNS resolution to work (in our external DNS for prod, the hostname is controller.magma.etagecom.io). I think that value should be in the helm chart values though.

Might be easier to make the name of the whole service a value for the MCP stack, just so we don't break existing deployments.

Edit for clarity: keep the existing value as the default name for the service in the values.yml and override it for the MCP stack.

**Review by xjtian — CHANGES_REQUESTED** [review]
See comment on PR

**Comment by reddydodda** [comment]
@xjtian  Please review.

**Pull request closed without merging**
