### PR TITLE
docs: typo in Security Debugging docs

### PR DESCRIPTION
**Pull request by alexzurbonsen**
## Summary

Replace `.sh` with `.bash` to make command work properly.

### CODE REVIEW

**Review by Neudrino — CHANGES_REQUESTED** [review]
`.bash` is a rather uncommon file extension. Usually those files should also be `.sh` files with an `#!/usr/bin/env bash` (or similar) comment in the first line.
So I think, we should rather correct the file extensions to comply with usual standards in contrast  to modifying the documentation to bake in the odds.

**Comment by alexzurbonsen** [comment]
> `.bash` is a rather uncommon file extension. Usually those files should also be `.sh` files with an `#!/usr/bin/env bash` (or similar) comment in the first line. So I think, we should rather correct the file extensions to comply with usual standards in contrast to modifying the documentation to bake in the odds.

Sounds reasonable.

**Review by Neudrino — APPROVED** [review]

**Comment by voisey** [comment]
@alexzurbonsen Should this be updated in previous versions of the docs too?

**Review by voisey — CHANGES_REQUESTED** [review]
It seems the file is .bash for magma versions >=1.5 (see https://github.com/magma/magma/commit/0c03dfeb007ac7e71f9cfaae230702be7e7c0a9c), so if you could please fix all versioned docs for >=1.5, that would be great!

**Comment by alexzurbonsen** [comment]
> It seems the file is .bash for magma versions >=1.5 (see [0c03dfe](https://github.com/magma/magma/commit/0c03dfeb007ac7e71f9cfaae230702be7e7c0a9c)), so if you could please fix all versioned docs for >=1.5, that would be great!

Done :)

**Review by voisey — APPROVED** [review]

**Pull request merged**
