### PR TITLE
[orc8r] Remove all OrchestratorPlugin artifacts

### PR DESCRIPTION
**Pull request by electronjoe**
## Summary

See Issue #3984.  This Pull Request resolves the issue - removing all implementations and uses of the Plugin infrastructure.

## Test 

Executed the following and validated no test failures were reported.

- cd magma/orc8r/cloud/docker
- ./build.py -m
- make build # to build
- make test # to run all unit tests
- make precommit # to run all targets needed before committing

Signed-off-by: Scott Harrison Moeller <smoeller@fb.com>

### CODE REVIEW

**Review by themarwhal — APPROVED** [review]

**Review by hcgatewood — CHANGES_REQUESTED** [review]
Hey Scott looks great, thanks for adding this

One last thing: can you remove the migration_plugin build targets. And if there's anything left over in the codebase from the plugin part of that migration 

For context, that's a real old migration (m003) -- the oldest we reference in the Docusaurus is m005

Just for completeness, you may also want to add a note then to the m003 migration about how it's effectively a dead migration at this point

**Review by uri200 — APPROVED** [review]

**Comment by electronjoe** [comment]
> Hey Scott looks great, thanks for adding this
> 
> One last thing: can you remove the migration_plugin build targets. And if there's anything left over in the codebase from the plugin part of that migration
> 
> For context, that's a real old migration (m003) -- the oldest we reference in the Docusaurus is m005
> 
> Just for completeness, you may also want to add a note then to the m003 migration about how it's effectively a dead migration at this point

If it's effectively a dead migration - should I remove the entire migration instead of exclusively surgically removing the migrations_plugin / plugin components of the migration?

**Comment by electronjoe** [comment]
> > Hey Scott looks great, thanks for adding this
> > One last thing: can you remove the migration_plugin build targets. And if there's anything left over in the codebase from the plugin part of that migration
> > For context, that's a real old migration (m003) -- the oldest we reference in the Docusaurus is m005
> > Just for completeness, you may also want to add a note then to the m003 migration about how it's effectively a dead migration at this point
> 
> If it's effectively a dead migration - should I remove the entire migration instead of exclusively surgically removing the migrations_plugin / plugin components of the migration?

PTAL #4616 and see what you think - I broke it out into another PR as I wasn't certain if this was the direction desired.

**Review by hcgatewood — APPROVED** [review]
Hey @electronjoe I think splitting is a good plan. Lgtm

**Review by emakeev — APPROVED** [review]
LGTM as soon as unit tests pass

**Pull request merged**
