### PR TITLE
[orc8r] Minor CMakeLists.txt cleanups

### PR DESCRIPTION
**Pull request by mcallahan**
Make sure all of the CMakeLists.txt files in orc8r contain
the magma copyright, contain a reasonable minimum cmake version
(arbitrarily picked at 3.8 for the C++ extensions),
and set C++14 as the language to use.

Signed-off-by: Michael Callahan <michaelcallahan@fb.com>

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by tmdzk — APPROVED** [review]

**Comment by tmdzk** [comment]
@ssanadhya  can you look into it?

**Comment by ssanadhya** [comment]
@mcallahan , could you please add a test plan to this change? It will be great if you can test the following:

1. Compilation with `make build_common` under `magma/lte/gateway` on your dev VM
2. Bringing up all services on the dev VM with `make run` under `magma/lte/gateway`
3. Run S1ap tests as described here: https://magma.github.io/magma/docs/lte/s1ap_tests

**Review by themarwhal — APPROVED** [review]

**Comment by ekowtaylor** [comment]
@themarwhal , @tmdzk can this be merged and closed?

**Comment by themarwhal** [comment]
@emakeev / @hcgatewood / @mpgermano Could you give this a review? Thanks!

**Review by hcgatewood — APPROVED** [review]
Deferring to @themarwhal as this is all gateway changes

**Comment by themarwhal** [comment]
Hey @mcallahan sorry about this again. Looks like another merge conflict. Should be good to go once that is resolved.

**Pull request merged**
