### PR TITLE
feat(orc8r): Add FreedomFi One as a supported eNB

### PR DESCRIPTION
**Pull request by amarpad**
## Summary

Add a new eNB model in the drop down

Signed-off-by: Amar Padmanabhan <amar@freedomfi.com>

## Test Plan

unit tests

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by andreilee** [comment]
Did you bring up the NMS for a sanity check?

**Comment by amarpad** [comment]
> Did you bring up the NMS for a sanity check?

Nope will do that. Also do let me know if there is some other testing I should do. Sorry meant to add a comment in the review around what are the tests I need to do beyond running the unit tests.

**Comment by amarpad** [comment]
Screen Shot 2021-09-12 at 8 04 29 PM

@andreilee, I was able to add the eNB through the NMS and read it back

**Comment by andreilee** [comment]
Thanks a ton for running the NMS sanity check and also debugging our NMS developer setup process

**Review by andreilee — APPROVED** [review]

**Pull request merged**
