### PR TITLE
[docs] Navigation Update

### PR DESCRIPTION
**Pull request by jimmytipit**
- Added Blog to top nav
- Updated footer blog link to magmacore.org
- Update Dev Conference link in footer

Signed-off-by: Jimmy McArthur <jimmy@tipit.net>

## Summary

Update outdated navigation in footer and header

## Test Plan

Simple link updates, testing was done locally.

### CODE REVIEW

**Review by jimmytipit — COMMENTED** [review]
LGTM :)

**Comment by rdefosse** [comment]
Can one of the admins verify this patch?

**Comment by ekowtaylor** [comment]
@jimmytipit would you mind rebasing and pushing this PR? Looks like a fairly straightforward change.

**Comment by jimmytipit** [comment]
We're about to redo the navigation anyway, so I'll go ahead and close this since it's 3 months old.

**Pull request closed without merging**
