### PR TITLE
refactor: remove old northbound listSubscribers handler

### PR DESCRIPTION
**Pull request by christinewang5**
## Summary
* Remove old northbound listSubscribers handler
* Updated tests to reflect change

## Test Plan
* ran tests
image
* checked the nms UI to see if we can still add and remove subscribers 
image

### CODE REVIEW

**Review by andreilee — COMMENTED** [review]
Looks good! Make sure to fix the `eslint` and `yarn` tests

**Review by hcgatewood — APPROVED** [review]
Awesome! I think you just need to fix the DCO check -- the bot comment has a howto for how to fix the full stack

Other than that, ping me tomorrow when it's ready and I'll merge for you!

**Comment by christinewang5** [comment]
sorry for all the forced pushes! >.<
i had trouble amending the commits so that they included the sign off....

**Review by andreilee — APPROVED** [review]

**Comment by hcgatewood** [comment]
Force-merging to override apparent eslint flake

**Pull request merged**
