### PR TITLE
feat(ci): consolidate linter implementations to use reviewdog for better Github integration

### PR DESCRIPTION
**Pull request by Neudrino**
## Summary

- add tflint to reviewdog to have this integrated with Github as well.

## Test Plan

- CI
  - no change to Terraform files: https://github.com/magma/magma/actions/runs/2219664144
  - change to Terraform files which are green: https://github.com/magma/magma/actions/runs/2219674103

## Additional information

- requires https://github.com/magma/magma/pull/12293

### CODE REVIEW

**Review by maxhbr — CHANGES_REQUESTED** [review]
Changes look good, but PR title does not follow semantic commits format.

**Review by maxhbr — APPROVED** [review]
Ah, `ci: ` is allowed, but I would prefer to have `feat(ci):` or `fix(ci):`.

I think `ci` should be used in the context of for example `ci(orc8r):` if you do ci work for orc8r. If a feature is added to ci it should be `feat(ci)`.

**Comment by maxhbr** [comment]
This adds a new top level folder that is not covered in the codeowners file. Is there a group that would be appropriate?

**Comment by Neudrino** [comment]
> This adds a new top level folder that is not covered in the codeowners file. Is there a group that would be appropriate?

Maybe I misunderstand the comment, but the changed file is covered by the `@magma/approvers-ci` group.

https://github.com/magma/magma/blob/master/CODEOWNERS#L3

**Comment by Neudrino** [comment]
> This adds a new top level folder that is not covered in the codeowners file. Is there a group that would be appropriate?

Maybe I misunderstand the comment, but the changed file is covered by the `@magma/approvers-ci` group.

https://github.com/magma/magma/blob/master/CODEOWNERS#L3

**Review by maxhbr — APPROVED** [review]
LGTM

**Pull request merged**
