### PR TITLE
fix(ci): updated deb build CI job

### PR DESCRIPTION
**Pull request by ShubhamTatvamasi**
## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by Neudrino — CHANGES_REQUESTED** [review]
Why would that be necessary? The job [looks totally fine](https://github.com/magma/magma/runs/7785054628?check_suite_focus=true#step:10:1) to me.

**Comment by MoritzThomasHuebner** [comment]
LGTM if removing `github.event` doesn't change the behavior The previous state worked as expected already.

**Comment by ShubhamTatvamasi** [comment]
> Why would that be necessary? The job [looks totally fine](https://github.com/magma/magma/runs/7785054628?check_suite_focus=true#step:10:1) to me.

If we remove `github.event` code works the same but code looks cleaner.

**Review by maxhbr — APPROVED** [review]
LGTM

**Comment by ShubhamTatvamasi** [comment]
Hi @Neudrino, I guess you also have to approve this.

**Review by MoritzThomasHuebner — APPROVED** [review]

**Review by Neudrino — APPROVED** [review]

**Pull request merged**
