### PR TITLE
fix(agw): Added code to correct the grpc encoding format of msisdn within ue_context

### PR DESCRIPTION
**Pull request by rsarwad**
Fix(agw): Added code to correct the grpc encoding format of msisdn within ue_context
This fixes the issue, https://github.com/magma/magma/issues/4908

## Summary
Issue description: While writing msisdn to Redis DB, mme was throwing encoding format error as below:
'magma.lte.oai.UeContext.msisdn' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.

Resolution: Corrected the gRPC encoding format of msisdn while writing to DB.
## Test Plan
Executed s1ap sanity test suite and verified the changes in Tera vm by executing inbound_roaming_01.ntl test case

Signed-off-by: Rashmi <rashmi.sarwad@radisys.com>

### CODE REVIEW

**Review by ardzoht — APPROVED** [review]
lgtm, thanks for this!

**Comment by crbertoldo** [comment]
@rsarwad @rmeleromira @uri200, please do you happen to know what triggers the [issue](https://github.com/magma/magma/issues/4908)n, and what are the real impacts of the serialization failure (crash, attach failure, etc.)?

**Comment by rsarwad** [comment]
> @rsarwad @rmeleromira @uri200, please do you happen to know what triggers the [issue](https://github.com/magma/magma/issues/4908), and what are the real impacts of the serialization failure (crash, attach failure, etc.)?

Hi @crbertoldo, Let me share my understanding and analysis
Having defined the data type as string in proto file, the value needs to be in UTF-8 encoded format. But with data type as byte doesn't need to have specific encoding format.
Msisdn value is received from HSS and stored in UE context, the same value is stored in Redis DB and also used while sending create session request from both spgw and sgw_s8.
Since we were seeing the error:
'magma.lte.oai.UeContext.msisdn' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.
In spgw_state.proto file, msisdn is of type byte, https://github.com/magma/magma/blob/master/lte/protos/oai/spgw_state.proto#L71
So we changed msisdn to bytes in mme_nas_state.proto file. 

@uri200, please correct me if I am wrong. 
@crbertoldo, could you please let us know any issue with this change?

**Comment by crbertoldo** [comment]
Thanks a lot, @rsarwad and @uri200!

**Pull request merged**
