### PR TITLE
fix(agw): restore SGi bridge flows to keep connectivity.

### PR DESCRIPTION
**Pull request by pshelar**
In case AGW service crash loop, the bridged mode AGW can
completely loose connectivity due to OVS reset done by
service monitoring the crash loop.
Following PR restores flows to keep the connectivity
to AGW via SGi interface.

Signed-off-by: Pravin B Shelar <pbshelar@fb.com>

## Test Plan
validated flow restoration on vagrant vm.

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by ulaskozat — COMMENTED** [review]
can we add some unit tests for this or at least include some test results against flakiness?

**Comment by pshelar** [comment]
> can we add some unit tests for this or at least include some test results against flakiness?

there is not framework for UT for this type of change. let me explore it.

**Comment by pshelar** [comment]
> > can we add some unit tests for this or at least include some test results against flakiness?
> 
> there is not framework for UT for this type of change. let me explore it.

I have added unit test for script using pipelineD test framework.

**Review by ulaskozat — APPROVED** [review]
Thanks for adding the test!

**Review by koolzz — APPROVED** [review]

**Review by ardzoht — APPROVED** [review]
lgtm

**Pull request merged**
