### PR TITLE
refactor(orc8r): Builder servicer endpoint as internal

### PR DESCRIPTION
**Pull request by sabithaatla**
Signed-off-by: root <sabitha.atla@wavelabs.ai>

## Summary

This PR deals with the segregation of Builder's internal gRPC servicers implementation.
These changes are part of the ongoing work which details the distinction between Orc8r-internal gRPC endpoints vs. external, gateway-oriented gRPC endpoints.
Moved MconfigBuilder implementation to protected folder.
Verified existing UT cases.

This PR was done as part of discussion by @hcgatewood [Remove gateway access to Orc8r-internal endpoints](https://drive.google.com/file/d/1NO6Qd6rU80xPh0Sb0mKWlSfDt0JbeVIT/view)

## Test Plan
All test cases passed.
No new Tc's added.

### CODE REVIEW

**Comment by sabithaatla** [comment]
@hcgatewood  Please review. This PR is created by closing https://github.com/magma/magma/pull/11176 which was approved by you.

**Review by themarwhal — APPROVED** [review]
lgtm, the changes look identical to the closed PR which hunter approved.

**Review by themarwhal — CHANGES_REQUESTED** [review]
Actually, it looks like orc8r checks are failing. Ping me again when that is fixed :)


```
=== Errors
[323](https://github.com/magma/magma/runs/5055995639?check_suite_focus=true#step:9:323)
services/orchestrator/servicers/protected/builder_servicer_test.go:531:13: undefined: "magma/orc8r/cloud/go/services/orchestrator/servicers".GetStateMconfig
[324](https://github.com/magma/magma/runs/5055995639?check_suite_focus=true#step:9:324)
services/orchestrator/servicers/protected/builder_servicer_test.go:546:13: undefined: "magma/orc8r/cloud/go/services/orchestrator/servicers".GetStateMconfig
[325](https://github.com/magma/magma/runs/5055995639?check_suite_focus=true#step:9:325)
services/orchestrator/servicers/protected/builder_servicer_test.go:557:13: undefined: "magma/orc8r/cloud/go/services/orchestrator/servicers".GetStateMconfig
[326](https://github.com/magma/magma/runs/5055995639?check_suite_focus=true#step:9:326)
services/orchestrator/servicers/protected/builder_servicer_test.go:570:13: undefined: "magma/orc8r/cloud/go/services/orchestrator/servicers".GetStateMconfig
[327](https://github.com/magma/magma/runs/5055995639?check_suite_focus=true#step:9:327)

[328](https://github.com/magma/magma/runs/5055995639?check_suite_focus=true#step:9:328)
DONE 495 tests, 4 errors in 200.361s
[329](https://github.com/magma/magma/runs/5055995639?check_suite_focus=true#step:9:329)
make[1]: *** [test] Error 2
[330](https://github.com/magma/magma/runs/5055995639?check_suite_focus=true#step:9:330)
/src/magma/orc8r/cloud/go/module.mk:100: recipe for target 'test' failed
[331](https://github.com/magma/magma/runs/5055995639?check_suite_focus=true#step:9:331)
make: *** [/src/magma/orc8r_test] Error 2
```

**Comment by sabithaatla** [comment]
> Actually, it looks like orc8r checks are failing. Ping me again when that is fixed :)
> 
> ```
> === Errors
> [323](https://github.com/magma/magma/runs/5055995639?check_suite_focus=true#step:9:323)
> services/orchestrator/servicers/protected/builder_servicer_test.go:531:13: undefined: "magma/orc8r/cloud/go/services/orchestrator/servicers".GetStateMconfig
> [324](https://github.com/magma/magma/runs/5055995639?check_suite_focus=true#step:9:324)
> services/orchestrator/servicers/protected/builder_servicer_test.go:546:13: undefined: "magma/orc8r/cloud/go/services/orchestrator/servicers".GetStateMconfig
> [325](https://github.com/magma/magma/runs/5055995639?check_suite_focus=true#step:9:325)
> services/orchestrator/servicers/protected/builder_servicer_test.go:557:13: undefined: "magma/orc8r/cloud/go/services/orchestrator/servicers".GetStateMconfig
> [326](https://github.com/magma/magma/runs/5055995639?check_suite_focus=true#step:9:326)
> services/orchestrator/servicers/protected/builder_servicer_test.go:570:13: undefined: "magma/orc8r/cloud/go/services/orchestrator/servicers".GetStateMconfig
> [327](https://github.com/magma/magma/runs/5055995639?check_suite_focus=true#step:9:327)
> 
> [328](https://github.com/magma/magma/runs/5055995639?check_suite_focus=true#step:9:328)
> DONE 495 tests, 4 errors in 200.361s
> [329](https://github.com/magma/magma/runs/5055995639?check_suite_focus=true#step:9:329)
> make[1]: *** [test] Error 2
> [330](https://github.com/magma/magma/runs/5055995639?check_suite_focus=true#step:9:330)
> /src/magma/orc8r/cloud/go/module.mk:100: recipe for target 'test' failed
> [331](https://github.com/magma/magma/runs/5055995639?check_suite_focus=true#step:9:331)
> make: *** [/src/magma/orc8r_test] Error 2
> ```

@themarwhal Error fixed.. Please approve and merge

**Review by themarwhal — APPROVED** [review]

**Pull request merged**
