### PR TITLE
docs(orc8r): Removing Juju deployment how-to from 1.8 branch

### PR DESCRIPTION
**Pull request by Gmerold**
Signed-off-by: Bartlomiej Gmerek <bartlomiej.gmerek@canonical.com>

## Summary

Removes Juju-based deployment how-to from `v1.8` branch. Charmed Magma doesn't support 1.8 yet.

## Test Plan

N/A

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by mpfirrmann** [comment]
@Gmerold, since this is a backport to v1.8 you should inform the responsible devs in the `#magma-releases` channel and request their explicit approval.

**Comment by Gmerold** [comment]
> @Gmerold, since this is a backport to v1.8 you should inform the responsible devs in the `#magma-releases` channel and request their explicit approval.

Thanks. I've posted a msg.

**Review by LKreutzer — CHANGES_REQUESTED** [review]
Please run `cd docs && make dev` and commit the resulting changes to update the `en.json` file.

**Comment by Gmerold** [comment]
> Please run `cd docs && make dev` and commit the resulting changes to update the `en.json` file.

@LKreutzer Thanks. Done.

**Comment by LKreutzer** [comment]
@Gmerold Sorry, I just noticed that this should not be a backport PR at all. The documentation for the 1.8 branch is deployed from the `docs/docusaurus/versioned_docs/version-1.8.0` on the `master` branch of `magma/magma`. 

To get this change deployed:

- Close this PR
- Do the same change in the `docs/docusaurus/versioned_docs/version-1.8.0` folder on `master`.
- Run `make dev` again.
- Open new PR against `master`. 

No additional steps needed, as this is not a backport.

**Pull request closed without merging**
