### PR TITLE
refactor(orc8r): ServiceRegistry service security changes

### PR DESCRIPTION
**Pull request by tej-wavelabs**
Signed-off-by: Tej <tej.prakash@wavelabs.ai>

## Summary

This PR deals with the segregation of `ServiceRegistry` internal gRPC servicers implementation.

These changes are part of the ongoing work which details the distinction between Orc8r-internal gRPC endpoints vs. external, gateway-oriented gRPC endpoints.

- All servicers in service_registry/servicers moved to service_registry/servicers/protected
- Imports updated wherever necessary

This PR was done as part of requirement by @hcgatewood [RemoveGatewayAccess toOrc8r-InternalEndpoints](https://drive.google.com/file/d/1NO6Qd6rU80xPh0Sb0mKWlSfDt0JbeVIT/view)

## Test Plan

All existing UTs passed
No new UTs added
No UTs removed

### CODE REVIEW

**Review by sabithaatla — DISMISSED** [review]
Need to move the internal proto servicer definition to Service scope

**Review by hcgatewood — CHANGES_REQUESTED** [review]
To echo @sabithaatla -- need to move the .proto definition file to the correct location, analogous to the work in https://github.com/magma/magma/pull/10902

**Comment by tej-wavelabs** [comment]
> To echo @sabithaatla -- need to move the .proto definition file to the correct location, analogous to the work in #10902

@sabithaatla @hcgatewood -- The service_registry.proto is used in platform registry at `orc8r/lib/go/registry`, platform registry in turn is a dependency for other components aswell like feg, cwf. 

If we still need to move service_registry.proto to service scope, we will have to change go.mod for orc8r/lib/go so that it can resolve the packages in orc8r/cloud/go which doesn't look in line with the project design. 

Inputs?

**Comment by hcgatewood** [comment]
@tej-wavelabs ah good catch. This is... an unfortunate artifact of how this was originally implemented, ugh. Let's leave it as-is for now then

**Review by hcgatewood — APPROVED** [review]

**Comment by tej-wavelabs** [comment]
@hcgatewood All the review comments have been resolved. This is ready to be merged now.

**Review by themarwhal — APPROVED** [review]
Hi @tej-wavelabs ! Looks good, but the commit message will need to be amended to appease the Semantic PR check. It checks for both the PR title and the commit name.

**Review by sabithaatla — APPROVED** [review]

**Comment by tej-wavelabs** [comment]
> Hi @tej-wavelabs ! Looks good, but the commit message will need to be amended to appease the Semantic PR check. It checks for both the PR title and the commit name.

Fixed! Please review changes

**Review by themarwhal — APPROVED** [review]

**Comment by anusha-konda** [comment]
@hcgatewood , @themarwhal , Can you please merge this PR. Thanks.

**Pull request merged**
