### PR TITLE
chore: bump node fetch

### PR DESCRIPTION
**Pull request by lucasgonze**
## Summary

Upgrade node-fetch to 2.6.7 by touching react-json-view and puppeteer.

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by Neudrino** [comment]
Can you give a reason, why this change was done?

A convincing test plan, needs to be given!
If this is touching puppeteer, this test plan needs to include execution of all E2E test.

**Review by Neudrino — COMMENTED** [review]
Can you give a reason, why this change was done?

A convincing test plan, needs to be given!
If this is touching puppeteer, this test plan needs to include execution of all E2E test.

**Comment by lucasgonze** [comment]
> Can you give a reason, why this change was done?

This change fixes a CVE in node-fetch.

> A convincing test plan, needs to be given! If this is touching puppeteer, this test plan needs to include execution of all E2E test.

Let's brainstorm in a live chat.

**Comment by sebathomas** [comment]
@lucasgonze The e2e tests are described here so maybe you can try them on your machine:
https://docs.magmacore.org/docs/nms/dev_testing#end-to-end-test

**Comment by lucasgonze** [comment]
> @lucasgonze The e2e tests are described here so maybe you can try them on your machine: https://docs.magmacore.org/docs/nms/dev_testing#end-to-end-test

Thanks. I'll do that.

**Comment by lucasgonze** [comment]
> @lucasgonze The e2e tests are described here so maybe you can try them on your machine: https://docs.magmacore.org/docs/nms/dev_testing#end-to-end-test

yarn:e2e passes

**Comment by lucasgonze** [comment]
Old: 
- react-json-view: ^1.19.1
- "puppeteer": "7.1.0" (dev dependency)

**Comment by lucasgonze** [comment]
Closing in favor of https://github.com/magma/magma/pull/13828, which is slightly cleaner.

**Pull request closed without merging**
