### PR TITLE
chore: move .bzl files into bazel/

### PR DESCRIPTION
**Pull request by themarwhal**
Signed-off-by: Marie Bremner <marwhal@fb.com>

## Summary
We are starting to accumulate .bzl / .BUILD files at the root (and other places). To clean this up, this PR creates a bazel/ directory at the root to store all these files. I copied the directory structure from [envoyproxy/envoy](https://sourcegraph.com/github.com/envoyproxy/envoy/-/tree/baze) and [uber/protocol ](https://sourcegraph.com/github.com/uber/prototool)

This structure will help us when constructing Dockerfiles that require Bazel.

Some notable changes
1. The gazelle update-repo command is modified to point to the new directory. `src/go/README.md` is updated to reflect that change. (cc @zbrock , @mstre123)
2. Moving the bazelrcs into the bazel directory as well. I'll remove the old files for this in a week so that there is less of a disturbance. (Getting the updated change would require a VM re-provision and a devcontainer hash update)

## Test Plan
Run the following commands to make sure they still work
```
bazel run //:gazelle -- update-repos -from_file=src/go/go.mod -to_macro=bazel/go_repositories.bzl%go_repositories
bazel run //:gazelle
bazel test //...
```

### CODE REVIEW

**Review by mstre123 — APPROVED** [review]

**Review by markjen — APPROVED** [review]

**Review by Neudrino — APPROVED** [review]

**Comment by rdefosse** [comment]
@themarwhal 

the CI server just stopped about 30 minutes ago during your CI run.

You will need to re-sync to re-trigger.

Sorry for the inconvenience.
Raphael

**Comment by themarwhal** [comment]
rebasing to get past broken feg check

**Review by ardzoht — APPROVED** [review]
`lte/gateway/..` changes lgtm

**Comment by themarwhal** [comment]
Hi @rdefosse! Could I get some help understanding why this job failed?

**Pull request merged**
