### PR TITLE
 [MME_Crash] [Mobile_Reachability_Timer] Fixed MME crash during sanity while handling mobile reachability timer expiry

### PR DESCRIPTION
**Pull request by tmdzk**
[MME_Crash] [Mobile_Reachability_Timer] Fixed MME crash during sanity while handling mobile reachability timer expiry

## Summary

Fixed MME crash during sanity while handling mobile reachability timer expiry

## Test Plan

`cd lte/gateway && fab integ_test`

### CODE REVIEW

**Comment by ssanadhya** [comment]
This PR resolves the CI check issues seen with https://github.com/magma/magma/pull/5227 (copy of https://github.com/magma/magma/pull/5303) created by @VinashakAnkitAman .

@tmdzk I see that `ci/circleci: Build Error` is still showing up in the CI checks, but it is not a required check. Is that a red flag?

**Review by ssanadhya — APPROVED** [review]
Same changes as in #5303 and #5227

**Review by ulaskozat — CHANGES_REQUESTED** [review]
I don't understand what this PR is solving.

**Review by ulaskozat — APPROVED** [review]
LGTM after @ssanadhya's clarification.

**Comment by ardzoht** [comment]
Closing this since #5303 merged which is an exact copy of this PR

**Pull request closed without merging**
