### PR TITLE
fix(agw): update lte/gateway/c/core to clang-format-11 Google style

### PR DESCRIPTION
**Pull request by electronjoe**
Finalizes #6187.  This PR atomically does the following:

- Re-formats all of `/lte/gateway/c/core` with `clang-format-11` and `Google` style
- Updates GH Workflow for CI to match this migration
- Updates the `lte/gateway/Makefile` target for `format_all` to support this migration

Should outstanding PRs have issues with the new CI phase / rebasing on this PR, it is advised they re-format their modified files (from within either the Magma Developer VM or the Devcontainer) with:

```bash
/usr/bin/clang-format-11 --style='{BasedOnStyle: Google, IncludeBlocks: Preserve, SortIncludes: false}' -i path/to/file1.cpp path/to/file2.h ...
```

OR

```bash
cd lte/gateway/
make format_all
```

Signed-off-by: Scott Moeller <electronjoe@gmail.com>

### CODE REVIEW

**Review by themarwhal — APPROVED** [review]

**Review by tmdzk — APPROVED** [review]

**Comment by ssanadhya** [comment]
@electronjoe , could you please add a test plan? 
Were you able to verify that `make build_oai` and `make test_oai` succeed?

**Comment by ssanadhya** [comment]
@tmdzk , can we trigger a run of LTE integration test in CI on this PR pre-merge?

**Review by ulaskozat — APPROVED** [review]
LGTM

**Comment by tmdzk** [comment]
> @tmdzk , can we trigger a run of LTE integration test in CI on this PR pre-merge?

@ssanadhya, @electronjoe should be able to trigger them there: https://github.com/electronjoe/magma/actions/workflows/lte-integ-test.yml?query=

**Comment by electronjoe** [comment]
> > @tmdzk , can we trigger a run of LTE integration test in CI on this PR pre-merge?
> 
> @ssanadhya, @electronjoe should be able to trigger them there: https://github.com/electronjoe/magma/actions/workflows/lte-integ-test.yml?query=

WUT! SO AMAZING!

**Comment by electronjoe** [comment]
> @electronjoe , could you please add a test plan? Were you able to verify that `make build_oai` and `make test_oai` succeed?

For this PR I didn't have a test plan other than the CI phases - which do include `make build_oai` and `make test_oai`.

**Comment by ulaskozat** [comment]
> > > @tmdzk , can we trigger a run of LTE integration test in CI on this PR pre-merge?
> > 
> > 
> > @ssanadhya, @electronjoe should be able to trigger them there: https://github.com/electronjoe/magma/actions/workflows/lte-integ-test.yml?query=
> 
> WUT! SO AMAZING!

FWIW, I did run the integ test for this PR and it passes locally. However, there are new merged code @electronjoe with merge conflicts...

**Comment by electronjoe** [comment]
> > > > @tmdzk , can we trigger a run of LTE integration test in CI on this PR pre-merge?
> > > 
> > > 
> > > @ssanadhya, @electronjoe should be able to trigger them there: https://github.com/electronjoe/magma/actions/workflows/lte-integ-test.yml?query=
> > 
> > WUT! SO AMAZING!
> 
> FWIW, I did run the integ test for this PR and it passes locally. However, there are new merged code @electronjoe with merge conflicts...

Thanks Ulas.

I intend to rebase and rerun CI, try to merge after hours this weekend.

**Pull request merged**
