### PR TITLE
docs: AWS Cloudstrapper Install Instructions

### PR DESCRIPTION
**Pull request by jaredmullane**
Signed-off-by: Jared Mullane <jmullane@fb.com>

## Summary

This provides instructions for how to deploy Magma via AWS Cloudstrapper.

## Test Plan

create_docusaurus_website.sh

image

### CODE REVIEW

**Comment by arunuke** [comment]
Thanks @jaredmullane . This looks good to me.

**Review by hcgatewood — APPROVED** [review]
Skimmed, lgtm

**Comment by themarwhal** [comment]
Docs check seem to be failing: see https://docs.magmacore.org/docs/next/docs/docs_overview#precommit

**Comment by jaredmullane** [comment]
Updated here with passing lint: https://github.com/magma/magma/pull/9718

cc: @themarwhal @hcgatewood

**Pull request closed without merging**
