### PR TITLE
feat(agw): Create Load tests for SubscriberDB.

### PR DESCRIPTION
**Pull request by mstre123**
Tests Add, Get, Update, List and Delete.
Signed-off-by: mstre123 <mstre123@gmail.com>

## Summary
Load tests for all subsriberdb service protos.

## Test Plan
Ran locally

### CODE REVIEW

**Review by ardzoht — CHANGES_REQUESTED** [review]
Can you also add the subscriberdb entry on `lte/gateway/python/setup.py`?

**Comment by mstre123** [comment]
> Can you also add the subscriberdb entry on `lte/gateway/python/setup.py`?

done - is there a way to test this?

**Comment by ardzoht** [comment]
> > Can you also add the subscriberdb entry on `lte/gateway/python/setup.py`?
> 
> done - is there a way to test this?

@mstre123 after running `make clean` and `make` again on the magmaVM, you can run `magtivate` and you should be able to run the load test script from anywhere.

**Review by ardzoht — APPROVED** [review]
lgtm

**Pull request merged**
