### PR TITLE
chore: support fuzzing

### PR DESCRIPTION
**Pull request by 0x34d**
## Summary

Adding Fuzzing support for Memory security.

## Additional Information

Security team should have received an email from me.

### CODE REVIEW

**Comment by lucasgonze** [comment]
> Security team should have received an email from me.

Arjun, was that "tar -xf Bug_Report.tar.xz" email from you? I have to tell you we thought it was likely to be malware.

I have a work item to implement fuzzing so am glad to be getting your contribution.

What fuzzing infrastructure are you proposing to use? Who will run it, and how?

May I ask how you came to be doing this work? I'm curious. Would you mind say more about yourself?

**Comment by 0x34d** [comment]
> Arjun, was that "tar -xf Bug_Report.tar.xz" email from you? I have to tell you we thought it was likely to be malware.

LOL XD:)
@vxunderground suicide time.


> What fuzzing infrastructure are you proposing to use? Who will run it, and how?

- Google's [oss-fuzz](https://github.com/google/oss-fuzz) infrastructure.


> May I ask how you came to be doing this work? I'm curious. Would you mind say more about yourself?

- That's what I do for living.
- Bug Bounty and adding open source projects in oss-fuzz(mostly network base).
- [My log](https://github.com/google/oss-fuzz/pulls?q=is%3Apr+author%3A0x34d+is%3Aclosed)

**Comment by lucasgonze** [comment]
Ok, next step is for me to study this more closely. BBIAB.

**Comment by lucasgonze** [comment]
A couple relevant links:

* https://security.googleblog.com/2023/02/taking-next-step-oss-fuzz-in-2023.html
* https://github.com/google/oss-fuzz/issues/9628

**Comment by lucasgonze** [comment]
@0x34d can you explain the provenance of the .raw files?

**Comment by 0x34d** [comment]
> @0x34d can you explain the provenance of the .raw files?

Input aka seed or corpus file for fuzzing.

Create by using : 
- https://github.com/magma/magma/blob/master/lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp
- https://github.com/magma/magma/blob/master/lte/gateway/c/core/oai/test/mme_app_task/test_mme_app_esm_encode_decode.cpp

use in nas5g_message_decode_seed_corpus/
```
NAS5GPktSnapShot::guti_based_registration
NAS5GPktSnapShot::pdu_session_est_req_type1
NAS5GPktSnapShot::pdu_session_est_req_type2
etc.
```

use in nas_message_decode_seed_corpus/
```
buffer of esm_msg_encode 
```

Note: I know they are not perfect seeds for `nas_message_decode` and `nas5g_message_decode` , It's close to good.

Help : [link](https://llvm.org/docs/LibFuzzer.html#corpus)

**Comment by 0x34d** [comment]
The PR for magma https://github.com/google/oss-fuzz/pull/9635

Note: Work in progress.

**Comment by lucasgonze** [comment]
Be patient. I have to research this one carefully, and I am new to the tech.

**Comment by lucasgonze** [comment]
I haven't forgotten this.

**Comment by 0x34d** [comment]
> I haven't forgotten this.

Alright, ping me when it's done.
I'm working on something else.

**Comment by lucasgonze** [comment]
Starting work.

**Comment by 0x34d** [comment]
> * [ ]  in lte/gateway/c/core/oai/include/amf_config.hpp you [changed the function signature](https://github.com/magma/magma/pull/14966/files#diff-24d51cc58d48b630021a3e0f6ff8253b4ecea53d8fd5b5161de6737fd5e7a7c7) from old-style (IE K&R generation) to modern C++. I'm curious why. Was there a functional reason?

Yes, unable to compile with `clang-15`
Error:
```
lte/gateway/c/core/oai/tasks/amf/amf_app_main.cpp:242:16: error: conflicting types for 'amf_app_init'
extern "C" int amf_app_init(const amf_config_t* amf_config_p) {
```
#### Note: I can craft a patch in https://github.com/google/oss-fuzz/pull/9635 but things will become messy in Ideal integration.

**Comment by lucasgonze** [comment]
> compile with `clang-15`

How do you run your compile? What is the command line to run the fuzzer?

**Comment by 0x34d** [comment]
original:
```
CC=clang
CXX=clang++
CFLAGS=-O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link
CXXFLAGS=-O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -stdlib=libc++
```

Mine:
```
readonly EXTRA_BAZEL_FLAGS="$(
for f in ${CFLAGS}; do
    echo "--conlyopt=${f}" "--linkopt=${f}"
    echo "--cxxopt=${f}" "--linkopt=${f}"
done
)"

bazel build \
    --dynamic_mode=off \
    --repo_env=CC=${CC} \
    --repo_env=CXX=${CXX} \
    --linkopt=-lsctp \
    --linkopt=-lidn \
    --linkopt=-ltspi \
    --linkopt=-lhogweed \
    --linkopt=${LIB_FUZZING_ENGINE} \
    --linkopt=-Wl,-rpath,'\$ORIGIN/lib' \
    ${EXTRA_BAZEL_FLAGS} \
    //lte/gateway/c/core/oai/fuzzing/...:*
```

#### Note: There are two possible ways also.
- I use patch in oss-fuzz `build.sh`.
- use of `FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION` macro for [amf_config.hpp](https://github.com/magma/magma/pull/14966/files#diff-24d51cc58d48b630021a3e0f6ff8253b4ecea53d8fd5b5161de6737fd5e7a7c7)

**Comment by 0x34d** [comment]
@lucasgonze Review?

**Comment by lucasgonze** [comment]
What platform are you building on?

**Comment by 0x34d** [comment]
> What platform are you building on?

`Ubuntu 20.04`

https://github.com/google/oss-fuzz/issues/9628

**Comment by lucasgonze** [comment]
> `Ubuntu 20.04`

What CPU?

**Comment by 0x34d** [comment]
> What CPU?

architecture x64 

Possibly: amd epyc or  intel xeon(it's a cluster)

**Comment by lucasgonze** [comment]
> > What CPU?
> 
> architecture x64
> 
> Possibly: amd epyc or intel xeon(it's a cluster)

The PR doesn't build on M1.

**Comment by 0x34d** [comment]
> > > What CPU?
> > 
> > 
> > architecture x64
> > Possibly: amd epyc or intel xeon(it's a cluster)
> 
> The PR doesn't build on M1.

What to do?
I don't use Apple or Microsoft, I'm on Fedora.

**Comment by lucasgonze** [comment]
I'll ask around.

**Comment by maxhbr** [comment]
It is sufficient if this runs on some architectures but at least in CI? M1 support does not sound important for that topic.

**Comment by 0x34d** [comment]
@lucasgonze What happened?

**Comment by 0x34d** [comment]
FvnPq61X0AEbjNd

**Comment by lucasgonze** [comment]
Note to myself: a natural place to deploy the fuzzer on a regular basis is in the ABot tests run by Wavelabs.

**Comment by 0x34d** [comment]
Ping

**Comment by 0x34d** [comment]
CLOSE

**Pull request closed without merging**
