### PR TITLE
chore(docs): Add link to current proposal process

### PR DESCRIPTION
**Pull request by hcgatewood**
## Summary

Presence of two "proposals" docs has confused contributors. Trying this solution first.

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by themarwhal — APPROVED** [review]

**Comment by hcgatewood** [comment]
> Oops! Looks like you failed the `Semantic PR check`.
> 
> ### Howto
> * [Instructions on formatting your PR title](https://magma.github.io/magma/docs/next/contributing/contribute_workflow#guidelines)
> * [Guide to the different CI checks and resolution guidelines](https://docs.magmacore.org/docs/next/contributing/contribute_ci_checks)

@quentinDERORY wat

```bash
$ git show                                    
commit 32d2a787b5e683a2b38edde069ac8a7c926632fe (HEAD -> prop_doc, origin/prop_doc)
Author: Hunter Gatewood <hgatewood@gmail.com>
Date:   Fri Jul 23 11:01:56 2021 -0700

    chore(docs): Add link to current proposal process
    
    Signed-off-by: Hunter Gatewood <hgatewood@gmail.com>
```

**Comment by themarwhal** [comment]
> Oops! Looks like you failed the `Semantic PR check`.
> 
> ### Howto
> * [Instructions on formatting your PR title](https://magma.github.io/magma/docs/next/contributing/contribute_workflow#guidelines)
> * [Guide to the different CI checks and resolution guidelines](https://docs.magmacore.org/docs/next/contributing/contribute_ci_checks)

huh why is this failing?

**Comment by hcgatewood** [comment]
@quentinDERORY what's up with the semantic PR check failing?

**Pull request merged**
