### PR TITLE
Revert "fix(mme): Handling missing support for MME_UE_S1AP_ID and  eNB_UE_S1AP_ID in E-RAB Modification Indication"

### PR DESCRIPTION
**Pull request by panyogesh**
Reverts magma/magma#15326

### CODE REVIEW

**Comment by maxhbr** [comment]
Please explain what you are doing and why. This PR has no helpful description and no context and just comes from nowhere with no linked discussion.

**Comment by panyogesh** [comment]
This PR is under observation (possibly revert)  as it seems to be reason for the CI failure for 5G testcases : 
https://magma-ci.web.app/ ([7e26dbb9](https://github.com/magma/magma/commit/7e26dbb9),  [dd42de5b](https://github.com/magma/magma/commit/dd42de5b)).
Although fixes are for 4G,  its somehow effecting the 5G cases. for instance the testcase: MultiSession_UEIDLE_to_Active_With_ServiceReq_Mo_Data 

Automated tools are

**Comment by nareshwave** [comment]
[](url
[1.9.0-1700465187-dd42de5b   WORKING BUILD.zip](https://github.com/magma/magma/files/13544484/1.9.0-1700465187-dd42de5b.WORKING.BUILD.zip)
[1.9.0-1700693252-7e26dbb9 failed build logs.zip](https://github.com/magma/magma/files/13544485/1.9.0-1700693252-7e26dbb9.failed.build.logs.zip)

**Review by prabinakpattnaik — APPROVED** [review]
LGTM

**Pull request merged**
