### PR TITLE
fix(agw): updated dockerfile focal repo for release

### PR DESCRIPTION
**Pull request by ShubhamTatvamasi**
Signed-off-by: Shubham Tatvamasi <shubhamtatvamasi@gmail.com>

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by crasu** [comment]
@ShubhamTatvamasi  Have you tested of the container can still be build after the repo change? Do the cwag integ tests still run?

**Comment by ShubhamTatvamasi** [comment]
> @ShubhamTatvamasi Have you tested if the container can still be build after the repo change? Do the cwag integ tests still run?

I have not tested manually, but CI looks good.

**Comment by crasu** [comment]
@ShubhamTatvamasi I tried to build that locally and I am getting build failures in the docker containers. Its probably not related to your changes but magmad is constantly not building because it is unable to pip install https://github.com/URenko/aioh2/

**Comment by ShubhamTatvamasi** [comment]
Merged changes with https://github.com/magma/magma/pull/13824

**Pull request closed without merging**
