### PR TITLE
docs: Migration of contributers guide to Github Wiki

### PR DESCRIPTION
**Pull request by Neudrino**
## Summary

- This is part of the effort from https://github.com/magma/magma/issues/9848.
- This is a follow up to https://github.com/magma/magma/pull/10953.
- To avoid having diverging documentation the content was copied over and linked in the appropriate places for a seamless transition.
- Please see **https://github.com/magma/magma/wiki/Contributing-Code** for the migration target.
- This should about finalize the migration of the topic "Contributing Code".

### CODE REVIEW

**Review by themarwhal — APPROVED** [review]
Changes look good!

Do we have a strategy on how searching for an entry would work with GitHub Wikis? Is there a search bar?

Also, I think we should do the same for versioned docs too :)

**Review by ildikov — APPROVED** [review]
Thank you @Neudrino !

**Review by electronjoe — APPROVED** [review]

**Comment by Neudrino** [comment]
> Do we have a strategy on how searching for an entry would work with GitHub Wikis? Is there a search bar?

You can use the Github global search bar with a search restricted to the Repository. On the left hand-side you will than find a category "Wikis".

grafik

**Comment by Neudrino** [comment]
> Also, I think we should do the same for versioned docs too :)

Good point. Maybe we can do a back port, once all people finished their part in the migration?
Or the problem might solve itself, if 1.7 is out and we have a new "default" version of the DocuSaurus?

**Comment by themarwhal** [comment]
> > Do we have a strategy on how searching for an entry would work with GitHub Wikis? Is there a search bar?
> 
> You can use the Github global search bar with a search restricted to the Repository. On the left hand-side you will than find a category "Wikis".
> 
> grafik

ah! didn't realize this was an option :D glad i asked!

**Comment by themarwhal** [comment]
> > Also, I think we should do the same for versioned docs too :)
> 
> Good point. Maybe we can do a back port, once all people finished their part in the migration? Or the problem might solve itself, if 1.7 is out and we have a new "default" version of the DocuSaurus?

Yeah I think we can do a full cleaning sweep once the migration is fully complete? (I would rather have it be gone entirely so that there's no chance for confusion :) )

**Pull request merged**
