### PR TITLE
docs(sessiond, pipelined): Create Design Proposal for UE Sharding

### PR DESCRIPTION
**Pull request by veshkemburu**
Signed-off-by: veshkemburu <veshkemburu@fb.com>

## Summary

Discuss the motivation and approach for sharding UEs to improve polling information.

## Test Plan

Create diagrams/tables describing flow and demonstrating potential outcomes
Write unit tests for parts of features described in the document.
Discuss with sessiond maintainers different approaches.

## Additional Information

Design doc: [https://fb.quip.com/qw7nAsV77VRe](https://fb.quip.com/qw7nAsV77VRe)

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by ulaskozat** [comment]
I find it really hard to read design docs in PR form if particularly there are figures, diagrams, tables, etc. Could you post a google doc that can be commented on?

**Comment by veshkemburu** [comment]
> I find it really hard to read design docs in PR form if particularly there are figures, diagrams, tables, etc. Could you post a google doc that can be commented on?

Yes! Added it to the description.

**Comment by ulaskozat** [comment]
@pshelar @uri200 @koolzz would not it make more sense to track "active" users in their own bucket, note that I am talking about the connection state.

**Comment by amarpad** [comment]
any chance we can move it to a shared google doc like the one we have in magmacore.org? The quip requires an FB password.

**Comment by pshelar** [comment]
> @pshelar @uri200 @koolzz would not it make more sense to track "active" users in their own bucket, note that I am talking about the connection state.

I would prefer deleting the flows for inactive sessions and adding it back when the session becomes active.

**Comment by ekowtaylor** [comment]
@veshkemburu what is the plan to move this forward?

**Pull request closed without merging**
