### PR TITLE
Added all non-sanity test cases to defs.mk file

### PR DESCRIPTION
**Pull request by VinashakAnkitAman**
## Title
[Sanity_Testing] Added all non-sanity test cases to defs.mk file

## Summary
The PRs #5931, #5986, #5988, #6061 contain fixes for some of the test cases added here and hence must be merged before this PR.

There were many test cases which were added but were untracked. This PR adds all the non-sanity test cases to the defs.mk file for better tracking. All the new test cases should be part of the defs.mk file for easy tracking. The non-sanity test cases which are passing in set are kept under target "NON_SANITY_TESTS" and can be executed with command "make nonsanity". Rest all the test cases showing issues are kept under different commented sections. The set of non-sanity test cases added here for tracking are as follows:

```
s1aptests/test_attach_service_without_mac.py
s1aptests/test_paging_request.py
s1aptests/test_multi_enb_paging_request.py
s1aptests/test_enb_partial_reset_with_unknown_ue_s1ap_ids.py
s1aptests/test_attach_auth_mac_failure.py
s1aptests/test_data_flow_after_service_request.py
s1aptests/test_attach_esm_information_timerexpiration.py
s1aptests/test_attach_inactive_tau_with_combined_tala_update_reattach.py
s1aptests/test_attach_active_tau_with_combined_tala_update_reattach.py
s1aptests/test_attach_detach_two_pdns_with_tcptraffic.py
s1aptests/test_attach_restricted_plmn.py
s1aptests/test_activate_deactivate_multiple_dedicated.py
s1aptests/test_sctp_shutdown_while_mme_is_stopped.py
s1aptests/test_attach_detach_rar_activation_reject.py
s1aptests/test_continuous_random_attach.py
s1aptests/test_enb_partial_reset_multi_ue_with_mme_restart.py
s1aptests/test_attach_ics_drop_with_mme_restart.py
s1aptests/test_attach_mme_restart_detach_multi_ue.py
s1aptests/test_no_auth_response_with_mme_restart.py
s1aptests/test_no_esm_information_rsp_with_mme_restart.py
s1aptests/test_no_smc_with_mme_restart_reattach.py
s1aptests/test_no_attach_complete_with_mme_restart.py
s1aptests/test_attach_ics_failure_with_mme_restart.py
s1aptests/test_outoforder_erab_setup_rsp_default_bearer.py
s1aptests/test_agw_offload_idle_active_ue.py
s1aptests/test_agw_offload_mixed_idle_active_multiue.py
s1aptests/test_secondary_pdn_with_dedicated_bearer_multiple_services_restart.py
s1aptests/test_outoforder_erab_setup_rsp_dedicated_bearer.py
s1aptests/test_attach_detach_with_ipv6_pcscf_and_dns_addr.py
s1aptests/test_ipv4v6_secondary_pdn_rs_retransmit.py
s1aptests/test_ipv4v6_secondary_pdn_spgw_initiated_ded_bearer.py
s1aptests/test_ipv6_secondary_pdn_rs_retransmit.py
s1aptests/test_ipv4v6_secondary_pdn.py
s1aptests/test_ipv4v6_secondary_pdn_with_ded_bearer.py
s1aptests/test_ipv6_secondary_pdn_with_ded_bearer.py
s1aptests/test_ipv4v6_secondary_pdn_with_ded_bearer_multi_ue.py
s1aptests/test_attach_detach_with_corrupt_stateless_mme.py
s1aptests/test_ipv4v6_secondary_pdn_multi_ue.py
s1aptests/test_attach_detach_setsessionrules_tcp_data.py
s1aptests/test_stateless_multi_ue_mixedstate_mme_restart.py
s1aptests/test_attach_with_multiple_mme_restarts.py
s1aptests/test_paging_with_mme_restart.py
s1aptests/test_standalone_pdn_conn_req_with_apn_correction.py
s1aptests/test_attach_esm_information_apn_correction.py
s1aptests/test_enb_partial_reset_multi_ue.py
s1aptests/test_attach_ul_udp_data_multi_ue.py
s1aptests/test_attach_dl_udp_data_multi_ue.py
s1aptests/test_attach_ul_tcp_data_multi_ue.py
s1aptests/test_attach_dl_tcp_data_multi_ue.py
s1aptests/test_attach_dl_ul_tcp_data_multi_ue.py
s1aptests/test_attach_and_mme_restart_loop_detach_and_mme_restart_loop_multi_ue.py
s1aptests/test_no_auth_response_with_mme_restart_reattach.py
s1aptests/test_no_identity_rsp_with_mme_restart.py
s1aptests/test_attach_esm_info_timerexpiration_max_retries.py
s1aptests/test_3495_timer_for_default_bearer_with_mme_restart.py
s1aptests/test_3495_timer_for_dedicated_bearer_with_mme_restart.py
s1aptests/test_imei_restriction_smc.py
s1aptests/test_imei_restriction_no_imeisv_in_smc.py
s1aptests/test_imei_restriction_wildcard_snr.py
s1aptests/test_attach_detach_with_pco_ipcp.py
s1aptests/test_attach_complete_after_ics_timer_expiry.py
s1aptests/test_send_error_ind_for_dl_nas_with_auth_req.py
s1aptests/test_send_error_ind_for_erab_setup_req.py
```

2 new scripts also added as part of PR #6061 for modifying and restoring the configurations specific to non-sanity test cases,
```
s1aptests/test_modify_config_for_non_sanity.py 
s1aptests/test_restore_config_after_non_sanity.py 
```
The test case **s1aptests/test_attach_detach_setsessionrules_tcp_data.py** is probably fixed and added as sanity test cases as part of commit-id: 6bd5b922c62eff45e3936fddeaf2a2b9ccc050bb, however needs to be reverified.

Some test cases have been added in run-time with ongoing parallel development and testing activities after raising this PR and hence might have been missed in the list above.

Some of the test cases have been marked with the Github Issue Ids for better tracking. In future, this is supposed to be a common habit to mark a tracking Github issue Id for all commented test cases in defs.mk file.

## Test Plan
Executed individually and as part of target "make nonsanity"

Signed-off-by: VinashakAnkitAman <ankit.aman@radisys.com>

### CODE REVIEW

**Comment by VinashakAnkitAman** [comment]
Hi @themarwhal.. Do we run python lint check on files which are not part of PR also? Here lint warnings can be seen for following files which does not include any change as part of this PR:
```
circleci/release/fabfile.py
lte/gateway/python/load_tests/loadtest_pipelined.py
lte/gateway/python/scripts/pipelined_cli.py
```

**Comment by themarwhal** [comment]
> Hi @themarwhal.. Do we run python lint check on files which are not part of PR also? Here lint warnings can be seen for following files which does not include any change as part of this PR:
> 
> ```
> circleci/release/fabfile.py
> lte/gateway/python/load_tests/loadtest_pipelined.py
> lte/gateway/python/scripts/pipelined_cli.py
> ```

Interesting.. 
This is the command used to find the changed files, so there maybe something wrong. https://github.com/magma/magma/blob/master/.github/workflows/wemake-python-styleguide.yml#L15
I'll take a look but feel free to ignore the failed check.

**Comment by VinashakAnkitAman** [comment]
> > Hi @themarwhal.. Do we run python lint check on files which are not part of PR also? Here lint warnings can be seen for following files which does not include any change as part of this PR:
> > ```
> > circleci/release/fabfile.py
> > lte/gateway/python/load_tests/loadtest_pipelined.py
> > lte/gateway/python/scripts/pipelined_cli.py
> > ```
> 
> Interesting..
> This is the command used to find the changed files, so there maybe something wrong. https://github.com/magma/magma/blob/master/.github/workflows/wemake-python-styleguide.yml#L15
> I'll take a look but feel free to ignore the failed check.

Surprising to see that.  However, I think the issue has been fixed, because after rebasing the PR, I don't see those lint issues on other files.

**Review by ulaskozat — APPROVED** [review]
LGTM

**Comment by ekowtaylor** [comment]
Once this PR has been approved and passing all CI checks, use the ready2merge label to indicate the maintainers can merge your PR.

**Review by ardzoht — APPROVED** [review]
lgtm

**Review by ulaskozat — APPROVED** [review]
LGTM

**Pull request merged**
