### PR TITLE
fix(orc8r): upgraded grafana version to 6.7.6

### PR DESCRIPTION
**Pull request by ShubhamTatvamasi**
Signed-off-by: Shubham Tatvamasi <shubhamtatvamasi@gmail.com>

## Test Plan

After deployment of the latest Grafana docker image with Orc8r we have to log in to the NMS go to **Metrics** tab. Their check all the required graphs are visible or not.

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by themarwhal** [comment]
Was this tested locally? Trying to understand how to verify such a change. :)

**Comment by ShubhamTatvamasi** [comment]
> Was this tested locally? Trying to understand how to verify such a change. :)

Yes, this was tested locally.

**Review by hcgatewood — APPROVED** [review]
Please include details of your test plan in the PR description 🙂  Assuming it was manually tested effectively, lgtm

**Comment by ShubhamTatvamasi** [comment]
> Please include details of your test plan in the PR description slightly_smiling_face Assuming it was manually tested effectively, lgtm

Just updated.

**Pull request merged**
