### PR TITLE
feat(agw): set up containerized agw with fabric

### LINKED ISSUE #14909: Fabric is Cleaned-Up
This a collection of technical debt in fabric files. This was identified during #14612 and should be handled after the respective PR is merged.

- [x] `get_test_summaries` function and calls should be refactored. Havin a host argument seems to be unused. Arguments `integ_tests` and `sudo_tests` should be generalized (maybe call function twice) #14998
- [ ] cleanup boiler plate code in `/lte/gateway/fabfile.py` (setup for containerized, deb, dev integ tests and federated integ tests) #15027
- [x] remove unused functions and tasks from fabfiles
- [x] improve handling of `exit()`/`sys.exit()`, and `raise` calls in fabric files #15020 
- [x] adapt more pythonic syntax as described in review comment https://github.com/magma/magma/pull/14806#pullrequestreview-1294884555 #15002
- [x] Some minor refactoring, including formatting changes. ~#15004~ (reverted in #15030 ), #15035

### PR DESCRIPTION
**Pull request by wolfseb**
Part of #14909 .

## Summary

Introduces a fabric command to setup the dockerized AGW for convenience.

## Test Plan

Setup the dockerized AGW with the fabric command `fab start-gateway-containerized` and check the containers functionality.

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by MoritzThomasHuebner — APPROVED** [review]

**Comment by MoritzThomasHuebner** [comment]
@LKreutzer maybe you can review this as well.

**Review by LKreutzer — COMMENTED** [review]
I started some integ test runs on a copy branch:
- https://github.com/magma/magma/actions/runs/4373139879
- https://github.com/magma/magma/actions/runs/4373140797
- https://github.com/magma/magma/actions/runs/4373142111

**Comment by LKreutzer** [comment]
> I started some integ test runs on a copy branch:
> 
>     * https://github.com/magma/magma/actions/runs/4373139879
> 
>     * https://github.com/magma/magma/actions/runs/4373140797
> 
>     * https://github.com/magma/magma/actions/runs/4373142111

Looks like the tests are okay.

**Review by LKreutzer — APPROVED** [review]
Lgtm

**Pull request merged**
