### PR TITLE
[lte][orc8r] deprecates field relay_enabled in lte mconfigs

### PR DESCRIPTION
**Pull request by waqaraqeel**
## Summary

Addresses #7336. Deprecates field `relay_enabled` in SessionD mconfig and pushes regenerated Go files. 

## Test Plan

Ran `./build.py --test` in `orc8r/cloud/docker` and `make test_session_manager` and `make test_oai` in `lte/gateway`. 100% tests passed.

### CODE REVIEW

**Review by ulaskozat — APPROVED** [review]
LGTM. Does this require any cloud side changes and db migration?

**Comment by waqaraqeel** [comment]
> LGTM. Does this require any cloud side changes and db migration?

I don't think so. The field hasn't actually been removed.

**Comment by uri200** [comment]
What happens to the swagger field? Is there any plan to remove it safely?

**Review by themarwhal — APPROVED** [review]
lgtm!

**Comment by waqaraqeel** [comment]
> What happens to the swagger field? Is there any plan to remove it safely?

I'm not sure... Perhaps will open another PR to do it.

**Pull request merged**
