### PR TITLE
feat(amf): Slice type name and type change in amf

### PR DESCRIPTION
**Pull request by panyogesh**
Fix:
     1. Change the name of Slice Type and Slice Differentiator and appending amf in front
     2. Changing the type of slice to int as per spec
     3. Removing prefix 0x from default values of slice as per the spec

  Test:
       1. Testing of SD mismatch case with Simulator
        2. Unit testing
 
 Scenarios :
       1. MAGMA(ST=1, SD=1) and UERANSIM(ST=1, SD wildcard). Expected PDU session created
       2. MAGMA(ST=1, SD=ffffff) and UERANSIM(ST=1, SD=1). Expected NGAP failure
       3. MAGMA(ST=1, SD=ffff) and UERANSIM(ST=1, SD wildcard). Expected PDU session created
       4. MAGMA(ST=1, SD=1) and UERANSIM(ST=1, SD=1). Expected PDU session created
   
 Logs: 
     8/19 Test  #8: test_amf_app ......................   Passed    0.17 sec
      
Signed-off-by: Yogesh Pandey <yogesh@wavelabs.ai>

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by ulaskozat — APPROVED** [review]
LGTM

**Review by ulaskozat — APPROVED** [review]
LGTM

**Comment by ulaskozat** [comment]
can you attach test results?

**Comment by panyogesh** [comment]
NGAP-SetupResponse-with-ST1-SD1
[TestLogs-10392.txt](https://github.com/magma/magma/files/7580905/TestLogs-10392.txt)

**Comment by panyogesh** [comment]
> can you attach test results?

Added the pcap and default/non-default configuration options

**Pull request merged**
