### PR TITLE
[AGW] [Stateless] Deprecate unused shell scripts for configuring stateless AGW

### PR DESCRIPTION
**Pull request by ssanadhya**
## Summary

The logic to configure stateless AGW mode has been refactored into `lte/gateway/python/scripts/config_stateless_agw.py` and `orc8r/gateway/python/magma/common/stateless_agw.py`. This change removes the old `config_stateless_*.sh` scripts as they are not needed any more. 

## Test Plan

- Destroy and recreate the Magma gateway VM
-- Create local vagrant box with:
```
cd ../../orc8r/tools/packer/
mkdir -p ../packer-magma-dev-virtualbox
cp -R *.json *.seed http scripts ../packer-magma-dev-virtualbox/
cd ../packer-magma-dev-virtualbox/
PACKER_LOG=1 packer build -except=vagrant-cloud magma-dev-virtualbox.json
```
-- Add the box to local vagrant 
```
vagrant box add magma-dev-vbox-stateless-py ~/magma/orc8r/tools/packer-magma-dev-virtualbox/builds/magma_dev_virtualbox.box
```
-- Use the localbox in `lte/gateway/Vagrantfile`
```
diff --git a/lte/gateway/Vagrantfile b/lte/gateway/Vagrantfile
index 78952e89d..6cb077e11 100644
--- a/lte/gateway/Vagrantfile
+++ b/lte/gateway/Vagrantfile
@@ -25,9 +25,9 @@ Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
     # - debian/contrib-jessie64
     # - linux kernel from debian jessie backports
     # - updated vbguest-tool
-    magma.vm.box = "magmacore/magma_dev"
+    magma.vm.box = "magma-dev-vbox-stateless-py"
     magma.vm.hostname = "magma-dev"
-    magma.vm.box_version = "1.1.20210120"
+    #magma.vm.box_version = "1.1.20210120"

     magma.vbguest.auto_update = false
```
-- Bring up Magma VM and check there is no `config_stateless.*sh` in `/usr/local/bin`
```
vagrant up magma
vagrant ssh magma
vagrant@magma-dev:~$ ls /usr/local/bin/config_state*
/usr/local/bin/config_stateless_agw.py
```

- Run `build-magma.sh` inside the VM and check contents of .deb package with 
`dpkg -c <package_name> | grep config_stateless`
Example:
```
vagrant@magma-dev:~/magma-packages$ dpkg -c magma_1.4.0-1609912282-933f2a32_amd64.deb | grep config_stateless
-rwxr-xr-x 0/0            6180 2021-01-06 05:51 ./usr/local/bin/config_stateless_agw.py
```

- `make integ_test`

### CODE REVIEW

**Review by pshelar — APPROVED** [review]
LGTM

**Comment by 119Vik** [comment]
RestartCWAGTests

**Comment by tmdzk** [comment]
You can rebuild all vagrant VMs using : https://jenkins.magmacore.org/job/vagrant_build/ 
If you want to do it manually you can reproduce the steps that we use in this script: https://github.com/magma/magma/blob/master/ci-scripts/JenkinsFile-build-vagrant-boxes 

@ssanadhya

**Review by ulaskozat — APPROVED** [review]
LGTM

**Review by tmdzk — APPROVED** [review]
RIP stateless!

**Pull request merged**
