### PR TITLE
chore(mme): move some sources out of c/core/oai/common and ...

### PR DESCRIPTION
**Pull request by electronjoe**
...split bazel target for lib/hashtable

Working towards #11892.

The purpose of this PR is to begin the process (demonstrate a path) of untangling cyclic dependencies that have presently been balled up into one very large Bazel label at `//lte/gateway/c/core:core`.  Untangling them reduces technical debt, but also greatly improves cache behavior in Bazel, build and test iteration times for sub-components.

This PR:

1. Moves five source files with no external cyclic dependencies from `lte/gateway/c/core/oai/common` to `lte/gateway/c/core/common`.  This move is required due to Bazel constraints (you cannot create a Bazel module if some source files in that directory are already in parent-directory modules - ergo we cannot create /c/core/oai/common/BUILD.bazel module if some files in oai/common/ are specified in `:core` already).
2. Generates isolated Bazel Build targets for these sources within `lte/gateway/c/core/common/BUILD.bazel` and updates all BUILD.bazel repo-wide with need of these dependencies
3. Establishes a new CMake external project within `lte/gateway/c/core/common` and adds it as a dependency to `lte/gateway/c/core/oai/common/CMakeLists.txt`. Note that this is a shortcut - what should be done is to hunt down EVERY CMake target that needs these dependencies and add the linking directive. But CMake use is on a fast path to deprecation at this point and this solution "works" because everybody who needed these assets already links against Common.
4. With 1-3 above done it was now possible to break out `lib/hashtable` into a new separate Bazel label as well (removing it from the giant `:core` label)

Note that 1-3 are "atomic" and I don't see how I can make this PR smaller [edit: I could have started with lesser migration targets that are not so frequently used across the codebase...].  Line item 4 is optional but a very small contribution to the size of this PR.

## Test Plan

Locally validated changes in GitHub Codespaces by validating success of:

```
bazel build //lte/gateway/c/... <success>
bazel test //lte/gateway/c/... <success>
cd lte/gateway
make build_oai <success>
make test_oai <success>
```

Signed-off-by: Scott Moeller [electronjoe@gmail.com](mailto:electronjoe@gmail.com)

### CODE REVIEW

**Review by nstng — APPROVED** [review]
This looks like a blueprint for a couple of followup tasks :)

Only minor question ...
Moving sources out of the core feels wired, but I know about the restriction. Do you see this as an intermediate state that should be refactored when core/oai/common becomes a Bazel package? Should it be documented or tracked in an issue?

**Comment by electronjoe** [comment]
> Moving sources out of the core feels wired

This was the feedback from @ardzoht as well - so I am going to instead move the sources to `lte/gateway/c/core/common`.

The goal would be that all source would be moved down a dir to `c/core` and `oai` would be deprecated.

Does that address your concern?

**Comment by nstng** [comment]
> > Moving sources out of the core feels wired
> 
> This was the feedback from @ardzoht as well - so I am going to instead move the sources to `lte/gateway/c/core/common`.
> 
> The goal would be that all source would be moved down a dir to `c/core` and `oai` would be deprecated.
> 
> Does that address your concern?

This sounds like a good idea - with this the way forward is clear and no post refactoring is needed.

**Review by ardzoht — APPROVED** [review]
lgtm, synced offline with @electronjoe regarding the `lte/gateway/c/core` hierarchy, the desired structure should be files being moved out of `../c/core/oai` should be moved to `../c/core/common`

**Pull request merged**
