### PR TITLE
CI: initial commit for new pipeline (Container and DsTester)

### PR DESCRIPTION
**Pull request by rdefosse**
# Initial version of the OAI-based container-based for DsTester and real RAN-UE testing

For the moment only the build

## Summary
 
- using lock to not compete against other OAI CI jobs
 - adding base image tag
 - adding base image tag check
 - throwing error when no base image
 - tagging base image
 - building image from CI-shortened Dockerfile
 - adding build log to artifacts
 - adding HTML report generation

Signed-off-by: Raphael Defosseux <raphael.defosseux@openairinterface.org>

## Test Plan

I've got [a development pipeline job](https://jenkins-oai.eurecom.fr/job/MAGMA-MME-CI-develop/)

## Additional Information

It should not touch any existing CI files.

### CODE REVIEW

**Comment by rdefosse** [comment]
No need to run the existing pipeline

**Comment by rdefosse** [comment]
@tmdzk @119Vik @ssanadhya @mattymo 

I've added the call to the child pipeline.

**Comment by rdefosse** [comment]
@tmdzk @mattymo @119Vik 

Can you please review and/or approve?

I really need to have this PR merged. 

Otherwise I'll merge it myself.

Raphael

**Review by mattymo — APPROVED** [review]

**Comment by mattymo** [comment]
@rdefosse no objections here. This won't break any existing tasks, so go ahead.

**Review by 119Vik — APPROVED** [review]
LGTM
For HTML generation You may consider https://jinja.palletsprojects.com/en/2.11.x/
should make your life easier

**Review by tmdzk — APPROVED** [review]

**Pull request merged**
