### PR TITLE
[SessionD] Deprecate unused session_map_ variable from LocalEnforcer

### PR DESCRIPTION
**Pull request by themarwhal**
## Summary
This field was deprecated from the move to use SessionStore

## Test Plan
SessionD builds/unit tests

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by ulaskozat — APPROVED** [review]
LGTM

**Comment by ulaskozat** [comment]
did you run lte integ tests?

**Comment by themarwhal** [comment]
@ulaskozat Yes, and the jenkins build has passed

**Review by uri200 — APPROVED** [review]
LGTM

**Pull request merged**
