### PR TITLE
fix(agw): Modified code to port UE context to protobuf structure at spgw task

### PR DESCRIPTION
**Pull request by rsarwad**
## Summary
agw(fix): Modified code to port UE context to protobuf structure at spgw task

## Test Plan
Executed s1ap sanity test suite and unit test cases

### CODE REVIEW

**Comment by nstng** [comment]
@rsarwad, what is the difference to #14810? The changes seem overlapping - what is the plan for merging here?

The Bazel changes look good in general, but it looks to me there are a couple of memory leaks detected in the tests - is this ready-for-review?

**Comment by rsarwad** [comment]
> @rsarwad, what is the difference to #14810? The changes seem overlapping - what is the plan for merging here?
> 
> The Bazel changes look good in general, but it looks to me there are a couple of memory leaks detected in the tests - is this ready-for-review?

PR https://github.com/magma/magma/pull/14810 has been branched out from this PR and this PR has been branched out from https://github.com/magma/magma/pull/14717. But PR 14717 is blocked from getting approvals from magma/approvers-agw .
So currently the diff shows 3 PR changes. To view individual PR changes, I have created PRs in my forked repo, https://github.com/rsarwad/magma/pull/29 and https://github.com/rsarwad/magma/pull/30

Yes with restart test cases, memory leaks are observed. I shall move this PR to draft till memory leaks are fixed

**Comment by rdefosse** [comment]
@rsarwad 

I made a mistake on one of the OAI CI servers while your PR was running. Sorry. It should be OK.

**Comment by nstng** [comment]
`//lte/gateway/c/core/oai/test/sgw_s8_task:sgw_dedicated_bearer_test` was failing in CI - I recently noticed this one failing and succeeding after restarting the run. This is the second strike - if I see this happening again, then I will mark the test as flaky (will then be executed with a one-out-of-three policy).

Restarted the tests.

**Comment by rsarwad** [comment]
> @rsarwad
> 
> I made a mistake on one of the OAI CI servers while your PR was running. Sorry. It should be OK.

No problem

**Comment by nstng** [comment]
Bazel and pipelined changes lgtm. Can you please,
* argue here why `test_spgw_state_converter.cpp` was removed
* rebase -> in order to re-trigger the oai jenkins tests

I will approve afterwards.

**Comment by panyogesh** [comment]
@VinashakAnkitAman : I guess we can close the PR. Kindly confirm

**Comment by Sathyaj27** [comment]
Closing this PR

**Pull request closed without merging**
