### PR TITLE
[Bug_Fix] [MME_Crash] [Mobile_Reachability_Timer] Fixed MME crash during sanity while handling mobile reachability timer expiry

### LINKED ISSUE #5053: [AGW][S1ap tests] Fix flaky S1ap tests
Some S1ap tests are flaky in CI or have been tweaked to workaround random failures. The tests mostly pass locally but get stuck when run as part of `make integ_test`

- **test_enb_partial_reset.py**
The test passes ([passing_enb_partial_reset_mme.log](https://github.com/magma/magma/files/6011995/passing_enb_partial_reset_mme.log)) when the release_access_bearers_response arrives before the Detach request, but fails ([failing_enb_partial_reset_num.log](https://github.com/magma/magma/files/6012004/failing_enb_partial_reset_num.log)) when the release_access_bearers_response arrives after the Detach request. 
https://github.com/magma/magma/pull/4798 add a delay before sending the Detach request to workaround this issue, but a fix is needed on MME to handle this scenario.

-  **test_service_req_ul_udp_data_with_mme_restart.py**
The test fails if MME sends paging indication as this TC does not expect Paging Ind. The issue is seen when test_service_req_ul_udp_data_with_mme_restart.py TC is executed after test_attach_service_with_multi_pdns_and_bearers_mt_data.py TC. https://github.com/magma/magma/pull/5041 ignores the paging ind message and waits for ICR Req. But the actual issue of why Paging Application is triggering Paging even though there is no MT data in the TC needs to be analyzed and fixed.

- **test_no_auth_response.py**
```
test_no_auth_response
    response.msg_type, s1ap_types.tfwCmd.UE_AUTH_REQ_IND.value
AssertionError: 52 != 7
```
The test case fails as UE context release indication is received instead of Auth Request The AGW syslog shows that MME restarted during the test case with the following:

```
 ==24600==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62200001b9e0 at pc 0x55aa4db67a15 bp 0x7fd151354660 sp 0x7fd151354658
Feb 19 17:58:24 magma-dev mme[24600]: READ of size 4 at 0x62200001b9e0 thread T16
Feb 19 17:58:24 magma-dev mme[24600]:     #0 0x55aa4db67a14 in mme_app_handle_mobile_reachability_timer_expiry /home/vagrant/magma/lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c:1818
Feb 19 17:58:24 magma-dev mme[24600]:     #1 0x55aa4de8195c in mme_app_nas_timer_handle_signal_expiry /home/vagrant/magma/lte/gateway/c/oai/tasks/nas/util/nas_timer.c:100
Feb 19 17:58:24 magma-dev mme[24600]:     #2 0x55aa4db56403 in handle_message /home/vagrant/magma/lte/gateway/c/oai/tasks/mme_app/mme_app_main.c:248
Feb 19 17:58:24 magma-dev mme[24600]:     #3 0x7fd1638e57bd in zloop_start (/usr/lib/x86_64-linux-gnu/libczmq.so.4+0x287bd)
Feb 19 17:58:24 magma-dev mme[24600]:     #4 0x55aa4db57161 in mme_app_thread /home/vagrant/magma/lte/gateway/c/oai/tasks/mme_app/mme_app_main.c:465
Feb 19 17:58:24 magma-dev mme[24600]:     #5 0x7fd1660c44a3 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x74a3)
Feb 19 17:58:24 magma-dev mme[24600]:     #6 0x7fd162438d0e in __clone (/lib/x86_64-linux-gnu/libc.so.6+0xe8d0e)
Feb 19 17:58:24 magma-dev mme[24600]: AddressSanitizer can not describe address in more detail (wild memory access suspected).
```
This is most likely bad state left from previous test run, where the mobile reachability timer was not cleared. Attaching MME logs before and after the restart for analysis [mme_logs_auth_resp_failure.zip](https://github.com/magma/magma/files/6012162/mme_logs_auth_resp_failure.zip)

### PR DESCRIPTION
**Pull request by VinashakAnkitAman**
## Title
[Bug_Fix] [MME_Crash] [Mobile_Reachability_Timer] Fixed MME crash during sanity while handling mobile reachability timer expiry

## Summary
This PR is a fix for the flaky test case test_no_auth_response.py as part of issue #5053. While working with the PR #4798, the test case test_no_auth_response.py was always failing during sanity (make integ_test). 

The issue was observed with the mobile reachability timer for the test case s1aptests/test_idle_mode_with_mme_restart.py. During the MME restart for this test case, the mobile reachability timer id was not getting updated properly and because of this after MME restart, when it was handling service request, the stopping of timer was failing. The timer was still running with a wrong timer id and with the expiry of timer, MME was not able to find the context and getting crashed. 

This crash was always happening while running test case test_no_auth_response.py as the timer was expiring by that time, leaving the doubt over this test case while the issue was with the test case s1aptests/test_idle_mode_with_mme_restart.py. This PR fixes the issue.

## Test Plan
Verified with Sanity and individual test case executions
Verified with the changes of PR #4798
Verified with these non-sanity test cases: (Taken from comment by Shruti)
    s1aptests/test_ics_timer_expiry_with_mme_restart.py
    s1aptests/test_implicit_detach_timer_with_mme_restart.py
    s1aptests/test_mobile_reachability_timer_with_mme_restart.py

Signed-off-by: VinashakAnkitAman <ankit.aman@radisys.com>

### CODE REVIEW

**Comment by ssanadhya** [comment]
@VinashakAnkitAman , can you verify that the timer test cases for MME restarts (which are not part of integ_tests) also pass with this change? Specifically, the test cases are:

```
test_ics_timer_expiry_with_mme_restart.py
test_implicit_detach_timer_with_mme_restart.py
test_mobile_reachability_timer_with_mme_restart.py
```

**Comment by VinashakAnkitAman** [comment]
> @VinashakAnkitAman , can you verify that the timer test cases for MME restarts (which are not part of integ_tests) also pass with this change? Specifically, the test cases are:
> 
> ```
> test_ics_timer_expiry_with_mme_restart.py
> test_implicit_detach_timer_with_mme_restart.py
> test_mobile_reachability_timer_with_mme_restart.py
> ```

Yes @ssanadhya .. I have verified with these non-sanity test cases.. Actually I collected the timer test cases which are not part of sanity from this list of test cases (https://drive.google.com/file/d/1pNZyUM_1b_0erz52gSYwbGokriZfxXFd/view?usp=sharing) and verified for them. The test cases are passing fine with this PR's change.

**Review by ssanadhya — APPROVED** [review]

**Comment by rdefosse** [comment]
MAGMA-OAI-TESTS

**Comment by rdefosse** [comment]
@VinashakAnkitAman @ssanadhya @lionelgo 

This PR does not build in the OAI variant. (`export FEATURES=mme_oai; make build_oai`)

See compile logs [here](https://jenkins-oai.eurecom.fr/job/MAGMA-MME-production/84/artifact/magma_logs.zip).

Regards
Raphael

**Comment by rdefosse** [comment]
@ssanadhya @rsarwad 

I suspect it is the commit that was just merged: `790162fe02315c3909d331615353c14afc56280e`

PR #5092 

Regards
Raphael

**Comment by rsarwad** [comment]
> @ssanadhya @rsarwad
> 
> I suspect it is the commit that was just merged: `790162fe02315c3909d331615353c14afc56280e`
> 
> PR #5092
> 
> Regards
> Raphael

Hi Raphael,
I will correct it soon. And also execute,  export FEATURES=mme_oai; make build_oai
I apologize for the inconvenience caused.

**Comment by rdefosse** [comment]
@rsarwad 

```bash
$ git diff
diff --git a/lte/gateway/c/oai/oai_mme/oai_mme.c b/lte/gateway/c/oai/oai_mme/oai_mme.c
index 90aef56c0..4e39d5001 100644
--- a/lte/gateway/c/oai/oai_mme/oai_mme.c
+++ b/lte/gateway/c/oai/oai_mme/oai_mme.c
@@ -43,7 +43,6 @@
 #include "sgs_defs.h"
 #include "sms_orc8r_defs.h"
 #include "ha_defs.h"
-#include "sgw_s8_defs.h"
 #include "oai_mme.h"
 #include "pid_file.h"
 #include "service303_message_utils.h"
@@ -51,6 +50,7 @@
 #include "intertask_interface.h"
 #include "intertask_interface_types.h"
 #if EMBEDDED_SGW
+#include "sgw_s8_defs.h"
 #include "mme_app_embedded_spgw.h"
 #include "spgw_config.h"
 #include "sgw_defs.h"
```
Can you test in a magma-dev VM? For me it works.
Raphael

**Comment by rsarwad** [comment]
> > @ssanadhya @rsarwad
> > I suspect it is the commit that was just merged: `790162fe02315c3909d331615353c14afc56280e`
> > PR #5092
> > Regards
> > Raphael
> 
> Hi Raphael,
> I will correct it soon. And also execute, export FEATURES=mme_oai; make build_oai
> I apologize for the inconvenience caused.



> @rsarwad
> 
> ```shell
> $ git diff
> diff --git a/lte/gateway/c/oai/oai_mme/oai_mme.c b/lte/gateway/c/oai/oai_mme/oai_mme.c
> index 90aef56c0..4e39d5001 100644
> --- a/lte/gateway/c/oai/oai_mme/oai_mme.c
> +++ b/lte/gateway/c/oai/oai_mme/oai_mme.c
> @@ -43,7 +43,6 @@
>  #include "sgs_defs.h"
>  #include "sms_orc8r_defs.h"
>  #include "ha_defs.h"
> -#include "sgw_s8_defs.h"
>  #include "oai_mme.h"
>  #include "pid_file.h"
>  #include "service303_message_utils.h"
> @@ -51,6 +50,7 @@
>  #include "intertask_interface.h"
>  #include "intertask_interface_types.h"
>  #if EMBEDDED_SGW
> +#include "sgw_s8_defs.h"
>  #include "mme_app_embedded_spgw.h"
>  #include "spgw_config.h"
>  #include "sgw_defs.h"
> ```
> 
> Can you test in a magma-dev VM? For me it works.
> Raphael

Yes, this will work for magma-dev VM as well.

**Comment by ssanadhya** [comment]
@VinashakAnkitAman , can you rebase this onto latest master? Looks like the CI checks did not get triggered when you converted from draft to open mode.

**Comment by VinashakAnkitAman** [comment]
> @VinashakAnkitAman , can you rebase this onto latest master? Looks like the CI checks did not get triggered when you converted from draft to open mode.

I have rebased the code now. I can see some failures with netlify deployment, but could not figure out the root cause for that viewing the logs.

**Comment by rdefosse** [comment]
MAGMA-OAI-TESTS

**Comment by rdefosse** [comment]
MAGMA-OAI-TESTS

**Comment by rdefosse** [comment]
MAGMA-OAI-TESTS

**Comment by ssanadhya** [comment]
These changes are already merged as part of https://github.com/magma/magma/pull/5303

**Pull request closed without merging**
