### PR TITLE
[AGW] Update agw installation documentation

### PR DESCRIPTION
**Pull request by tmdzk**
Signed-off-by: Timothée Dzik <timdzik@fb.com>

[AGW] Update agw installation documentation

## Summary

Update agw installation documentation

### CODE REVIEW

**Review by karthiksubraveti — APPROVED** [review]

**Review by pshelar — CHANGES_REQUESTED** [review]
why are we going back to 1.3 install script? can you add context to the commit msg.

**Comment by tmdzk** [comment]
@pshelar v1.4 is not stable it will change when it gets tagged.

**Comment by pshelar** [comment]
now it looks stable, can we update this PR.

**Comment by ekowtaylor** [comment]
@tmdzk , @rpraveen can we move this PR forwards if it still needs to be merged

**Pull request closed without merging**
