### PR TITLE
chore: delete config file

### PR DESCRIPTION
**Pull request by lucasgonze**
A partial fix for https://github.com/magma/security/issues/111.  Discussion of this PR should be within that ticket.

This PR deletes a file that is probably no longer used. 

Signed-off-by: Lucas Gonze <lucas@gonze.com>

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by lucasgonze** [comment]
The two failing tests aren't relevant to this change:
image

**Comment by lucasgonze** [comment]
The two failing tests aren't relevant to this change:
image

This could be real:
image

**Review by sebathomas — APPROVED** [review]
I don't think this is used any more.

**Review by uri200 — APPROVED** [review]

**Comment by sebathomas** [comment]
@lucasgonze I think you may need to rebase the PR. There is a required job blocking the merge that was introduced in the CI recently.

**Comment by lucasgonze** [comment]
The failing tests are unrelated to the content of this change. They are problems in the tests, not in the code.

**Comment by lucasgonze** [comment]
@sebathomas rebased and pushed.

**Pull request merged**
