### PR TITLE
chore(agw): remove unused asn1 message files 

### PR DESCRIPTION
**Pull request by themarwhal**
Signed-off-by: Marie Bremner <marwhal@fb.com>

## Summary
I think these are all unused? letting CI run to determine..

## Test Plan
CI -> Unit tests have passed, OAI Jenkins job is ongoing
`fab release package` -> completed without errors

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by themarwhal** [comment]
@rdefosse Any idea why the Jenkins job might be failing?

**Comment by rdefosse** [comment]
> @rdefosse Any idea why the Jenkins job might be failing?

@themarwhal  looks like we are having network issues again in Eurecom. I will notify the IT team.

Just resync and re-trigger.. It should be ok

**Review by ardzoht — APPROVED** [review]
lgtm, thanks for the cleanup

**Comment by ssanadhya** [comment]
LGTM, @ardzoht @themarwhal , let's wait for Magma-OAI-Jenkins to pass before merging. cc: @rdefosse

**Pull request merged**
