### PR TITLE
New Controller

### PR DESCRIPTION
**Pull request by Lkishor123**
## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by ajahl** [comment]
Is there a reason to include the bstring library into the Magma repo a second time? The library already exist sin the repo `lte/gateway/c/core/oai/lib/bstr/bstrlib.c`.

**Comment by Lkishor123** [comment]
> Is there a reason to include the bstring library into the Magma repo a second time? The library already exists in the repo `lte/gateway/c/core/oai/lib/bstr`.

**Comment by Lkishor123** [comment]
> Is there a reason to include the bstring library into the Magma repo a second time? The library already exists in the repo `lte/gateway/c/core/oai/lib/bstr`.

@ajahl I was just doing some experiment out. Will close this draft PR. Thanks

**Comment by Lkishor123** [comment]
> Is there a reason to include the bstring library into the Magma repo a second time? The library already exists in the repo `lte/gateway/c/core/oai/lib/bstr`.

@ajahl, I was doing some experiment for code refactoring. I will close this PR. Thanks.

**Pull request closed without merging**
