### PR TITLE
[orc8r] annotate unused params with __attribute__

### PR DESCRIPTION
**Pull request by waqaraqeel**
Signed-off-by: Waqar Aqeel <waqeel@fb.com>

## Summary

Working towards #5490

## Test Plan

Ran `cmake` and `make` in `orc8r/gateway/c/common`. Also ran `./build.py -t` in `orc8r/cloud/docker`.

### CODE REVIEW

**Review by themarwhal — APPROVED** [review]
awesome :) Thanks!

**Comment by themarwhal** [comment]
You might also want to run `make format_common` if you haven't already.

**Comment by waqaraqeel** [comment]
> You might also want to run `make format_common` if you haven't already.

I just did now and it changes a single character. Should I push and let all the tests run again?

**Comment by themarwhal** [comment]
> > You might also want to run `make format_common` if you haven't already.
> 
> I just did now and it changes a single character. Should I push and let all the tests run again?

Please do! Thanks! And if you label the PR with `ready2merge` when you are ready, I'll go ahead and merge the change.

**Comment by electronjoe** [comment]
Thanks for the merge assist @themarwhal! Nice work on first PR @waqaraqeel  =D

**Pull request merged**
