### PR TITLE
[ci] missing logs in artifacts

### LINKED ISSUE #3602: [CI/CD] Jenkins Pipeline does not capture all logs in artifact
## Jenkins server

on `https://jenkins.magmacore.org/job/magma_integration_tests/` job

--> artifact `magma_logs.zip`

I tagged is as `High Priority` because developers cannot see what went wrong on their PR runs.

## Describe the Issue

I was analyzing the logs on Mohit's PR (2707) --> `https://jenkins.magmacore.org/job/magma_integration_tests/1255/artifact/magma_logs.zip`

We could not find the MME logs.

I looked into `ci-scripts/JenkinsFile-GitLab` and there are a few missing `copyFrom2ndServer` function calls.

List of missing files (not exhaustive)

* archives/magma_dev_syslog.log
* archives/magma_dev_mme.log
* archives/magma_test_syslog.log
* archives/magma_trfserver_run1.log
* archives/magma_dev_syslog_s11.log
* archives/magma_dev_mme_s11.log

### PR DESCRIPTION
**Pull request by rdefosse**
## Summary

Based on [Issue 3602](https://github.com/magma/magma/issues/3602)

## Test Plan

Cannot be tested until merged into `master` branch.

## Additional Information

I've added also some PCAP captures on S1 and S11 interfaces.

### CODE REVIEW

**Review by ssanadhya — APPROVED** [review]

**Review by tmdzk — APPROVED** [review]

**Review by 119Vik — APPROVED** [review]
Looks good, these changes were tested already

**Comment by 119Vik** [comment]
Due to conflicts we have in this PR and another large refactoring we are going to merge into the Jenkinsfile (https://github.com/magma/magma/pull/3804) I suggest add refactored version of changes done in this PR in to https://github.com/magma/magma/pull/3804

**Comment by rdefosse** [comment]
@119Vik 

I will resync tommorrow and push again!

**Comment by rdefosse** [comment]
@119Vik @mattymo @tmdzk 

With your new direct `sh` approach, the logs are not missing any more. That PR is not needed anymore by itself.

But I pushed back with the `tcpdump` captures, so we have also S1/S11 capture logs for developers to analyze.

Regards
Raphael

**Review by mattymo — APPROVED** [review]

**Pull request merged**
