### PR TITLE
Add support for Baicells BaiBS_RTSH firmware

### PR DESCRIPTION
**Pull request by gjalves**
This patch just allow another Baicells firmware to use the already existing support.

### CODE REVIEW

**Review by xjtian — CHANGES_REQUESTED** [review]
Check out the changes to device_utils.py in #1037, and rebase after we merge that please - I'll approve and import after :)

**Comment by gjalves** [comment]
I've update as requested, but do not know why CI failed.

**Comment by 119Vik** [comment]
Can one of the admins verify this patch?

**Review by electronjoe — APPROVED** [review]

**Comment by electronjoe** [comment]
Unable to validate the PR but the harm seems low and this is super easy to roll back if necessary. Ergo I'm stamping it.

**Review by pshelar — APPROVED** [review]

**Comment by electronjoe** [comment]
@gjalves if you want to re-push the PR it will re-run our CI and as we have approvals now, we can merge! May require a rebase on master?

**Comment by ekowtaylor** [comment]
@gjalves any thoughts about re-pushing this PR?

**Comment by ekowtaylor** [comment]
@electronjoe can this be merged in anyway or it has to be rebased by the author?

**Comment by electronjoe** [comment]
> @electronjoe can this be merged in anyway or it has to be rebased by the author?

If it's going to be merged somebody like me would need to create a new PR to work it through the CI pipeline and merge conflicts. We would effectively abandon this PR. I can do that...

**Comment by electronjoe** [comment]
> > @electronjoe can this be merged in anyway or it has to be rebased by the author?
> 
> If it's going to be merged somebody like me would need to create a new PR to work it through the CI pipeline and merge conflicts. We would effectively abandon this PR. I can do that...

In attempting to reproduce this PR for myself - I see somebody else has already merged this PR's capability (perhaps by copying it). Closing this PR as a result.

**Pull request closed without merging**
