### PR TITLE
chore(cwg): Upgrade helm.sh/helm/v3 to v3.2.4

### PR DESCRIPTION
**Pull request by spikey979**
Signed-off-by: Kristijan <spikey979@gmail.com>

chore(cwg): Upgrade helm.sh/helm/v3 to v3.2.4

## Summary

The Helm core maintainers have identified an information disclosure vulnerability in Helm 3.0.0-3.1.2. This issue has been fixed in Helm 3.2.0, so helm.sh/helm/v3 package should be upgraded to v3.2.0 or later.

Solution: github.com/operator-framework/operator-sdk should be upgraded to v0.19.4, then package helm.sh/helm/v3 will be automatically upgraded to v3.2.4

This is for dependabot alert:
https://github.com/magma/magma/security/dependabot/82

### CODE REVIEW

**Comment by themarwhal** [comment]
@spikey979 Merge conflict :'(

Do validate this change, do you mind running
```
cd ${MAGMA_ROOT}/cwf/k8s/cwf_operator && go mod download
make -C ${MAGMA_ROOT}/cwf/k8s/cwf_operator precommit
```

**Comment by spikey979** [comment]
> @spikey979 Merge conflict :'(
> 
> Do validate this change, do you mind running
> 
> ```
> cd ${MAGMA_ROOT}/cwf/k8s/cwf_operator && go mod download
> make -C ${MAGMA_ROOT}/cwf/k8s/cwf_operator precommit
> ```

I resolved conflicts, but I didn't understand what exactly you wanted me to do... Should I run **go mod download** and **precommit** localy?

**Comment by spikey979** [comment]
I checked the package version, helm.sh/helm/v3 is now upgraded to v3.2.4

**Comment by themarwhal** [comment]
> > @spikey979 Merge conflict :'(
> > Do validate this change, do you mind running
> > ```
> > cd ${MAGMA_ROOT}/cwf/k8s/cwf_operator && go mod download
> > make -C ${MAGMA_ROOT}/cwf/k8s/cwf_operator precommit
> > ```
> 
> I resolved conflicts, but I didn't understand what exactly you wanted me to do... Should I run **go mod download** and **precommit** localy?

yes please.

**Comment by spikey979** [comment]
@themarwhal  I executed this two commands... 
Screenshot 2022-03-10 at 13 01 52

**Review by themarwhal — APPROVED** [review]

**Pull request merged**
