### PR TITLE
fix(agw): Updated Magma version to 1.8.0 for upgrade script

### PR DESCRIPTION
**Pull request by ShubhamTatvamasi**
Signed-off-by: Shubham Tatvamasi <shubhamtatvamasi@gmail.com>

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by maxhbr** [comment]
do we want to go through regular review, or should it be force merged?

**Comment by ShubhamTatvamasi** [comment]
> do we want to go through regular review, or should it be force merged?

I think we can just force merge this one.

**Comment by maxhbr** [comment]
ok, lets see if we get the go from @panyogesh or @m-govind.

**Review by panyogesh — APPROVED** [review]
LGTM

**Pull request merged**
