### PR TITLE
[Terraform] [AWS] Upgraded Postgres version

### PR DESCRIPTION
**Pull request by ShubhamTatvamasi**
## Summary

**9.6.15** version is no shown for creation on RDS page.

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by joary** [comment]
@ShubhamTatvamasi, thanks for your contribution.

You can also change the `orc8r_db_engine_version` directly from your main.tf, by overwriting the default value, [see more details](https://magma.github.io/magma/docs/next/orc8r/dev_aws_stack#what-does-terraform-deploy-in-my-aws-account)

For example, you can add [in your maint.tf orc8r module](https://github.com/magma/magma/blob/155942ad9e55aa997b690a9b6071c189adaa2ee3/orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/basic/main.tf#L21) another line with:
```
 orc8r_db_engine_version = 9.6.21
```

Have you tried overwriting the config?, did it not worked for you?

**Comment by ShubhamTatvamasi** [comment]
> @ShubhamTatvamasi, thanks for your contribution.
> 
> You can also change the `orc8r_db_engine_version` directly from your main.tf, by overwriting the default value, [see more details](https://magma.github.io/magma/docs/next/orc8r/dev_aws_stack#what-does-terraform-deploy-in-my-aws-account)
> 
> For example, you can add [in your maint.tf orc8r module](https://github.com/magma/magma/blob/155942ad9e55aa997b690a9b6071c189adaa2ee3/orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/basic/main.tf#L21) another line with:
> 
> ```
>  orc8r_db_engine_version = 9.6.21
> ```
> 
> Have you tried overwriting the config?, did it not worked for you?

Thanks @joary, I have not tried this, but it's good to know. And I still think we should update this version because the previous version is not supported anymore.

**Review by karthiksubraveti — CHANGES_REQUESTED** [review]
Hey Shubham, I was actually planning in incrementing this all the way to 12.6. There are a few issues with upgrade though when a user is trying to upgrade from 9.6 -> 12.6. I have some changes lined up for this, along with some documentation changes as well. Can you bump this up to 12.6, we can merge this change.

**Review by karthiksubraveti — APPROVED** [review]
LGTM.

**Pull request merged**
