### PR TITLE
refactor: remove duplication of metrics helpers functions

### PR DESCRIPTION
**Pull request by waqaraqeel**
## Summary

Metrics helper functions such as `increment_counter` were duplicated in MetricsHelpers.cpp and service303.cpp. This PR removes that duplication and brings all metrics helper functions to MetricsHelpers.cpp.

## Test Plan

Ran `make test_oai` and `make test_session_manager` in AGW VM. All passed.

### CODE REVIEW

**Comment by rdefosse** [comment]
@waqaraqeel 

Failing when OAI CI pipeline tries to connect w/ `OAI-UE` modem.

Logs available at `https://jenkins-oai.eurecom.fr/job/MAGMA-MME-RHEL8-Deploy-Check/529/`

In `archives/mme-stdout.log`:

```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
```

**Comment by waqaraqeel** [comment]
> https://jenkins-oai.eurecom.fr/job/MAGMA-MME-RHEL8-Deploy-Check/529/

@rdefosse Thanks for the update! I'm struggling to understand why this update would cause the reported error in `NwGtpv2cMsgIeParseInfo.c`. Seems unlikely as the code in question is completely unrelated to metrics. Could we re run this test?

**Review by themarwhal — APPROVED** [review]
Awesome work :)

**Comment by electronjoe** [comment]
For bonus bonus - there is a potential for a small follow-up PR. GCC warnings are detecting an out-of-order initialization in proximity to this change.

```
/magma/lte/gateway/c/session_manager/SessionState.h: In constructor 'magma::SessionState::SessionState(const magma::StoredSessionState&, magma::StaticRuleStore&)':
/magma/lte/gateway/c/session_manager/SessionState.h:802:12: warning: 'magma::SessionState::shard_id_' will be initialized after [-Wreorder]
  802 |   uint16_t shard_id_;
      |            ^~~~~~~~~
/magma/lte/gateway/c/session_manager/SessionState.h:740:12: warning:   'uint32_t magma::SessionState::request_number_' [-Wreorder]
  740 |   uint32_t request_number_;
      |            ^~~~~~~~~~~~~~~
/magma/lte/gateway/c/session_manager/SessionState.cpp:129:1: warning:   when initialized here [-Wreorder]
  129 | SessionState::SessionState(
```

C++ Initializes member variables in the order of declaration for the class. It appears we are specifying initializer list values in the constructor that are not the same order as the member declarations in the class definition (of the header). This can lead to nasty bugs - sometimes.

**Comment by waqaraqeel** [comment]
> @waqaraqeel
> 
> Failing when OAI CI pipeline tries to connect w/ `OAI-UE` modem.
> 
> Logs available at `https://jenkins-oai.eurecom.fr/job/MAGMA-MME-RHEL8-Deploy-Check/529/`
> 
> In `archives/mme-stdout.log`:
> 
> ```
> terminate called after throwing an instance of 'std::logic_error'
>   what():  basic_string::_M_construct null not valid
> ```

Talked to @rdefosse offline. The issue has been fixed now and the OAI CI pipeline is fine.

**Comment by waqaraqeel** [comment]
> For bonus bonus - there is a potential for a small follow-up PR. GCC warnings are detecting an out-of-order initialization in proximity to this change.

Will work on it. Thanks!

**Comment by themarwhal** [comment]
> > For bonus bonus - there is a potential for a small follow-up PR. GCC warnings are detecting an out-of-order initialization in proximity to this change.
> 
> Will work on it. Thanks!

There's https://github.com/magma/magma/pull/8304 authored by @veshkemburu - so this might be resolved soon

**Comment by waqaraqeel** [comment]
> There's #8304 authored by @veshkemburu - so this might be resolved soon

Thanks for the heads up! Looks like #8304 addresses the build warnings.

**Review by ardzoht — APPROVED** [review]
lgtm, thanks for this

**Pull request merged**
