### PR TITLE
[orc8r][mesh][serdes] Convert remaining serdes to non-registry pattern

### PR DESCRIPTION
**Pull request by hcgatewood**
## Summary

This is the third and final in a set of stacked PRs to move serdes away from the plugin+global registry pattern and into the explicit registry pattern.

### Context: serdes

We currently manage 5 serde domains:
- device
- testcontroller
- state
- configurator: network configs
- configurator: ent configs

This PR handles the device and testcontroller domains, across all orc8r modules.

### Serde changes

As part of the service mesh changes, core orc8r services must function without compile-time build information from non-core orc8r services. This means, e.g., the state service needs to pass around state which it will no longer be able to deserialize.

Rather than keeping an implicit, global, multi-domain registry of serdes populated during plugin registration (plugin pattern), we instead prefer an explicit, per-process, flat "registry" of serdes populated as a const-like variable. Each module (or service) tracks their own set of serdes. This simplifies the codebase and lowers the surface area for introducing bugs. 

### Device and testcontroller serde changes

These were both straightforward changes, as far as serdes go. All device registration uses the same core orc8r device serdes, and testcontroller is a non-core service which only ever uses its own testcontroller serdes.

### Misc included changes

- Cleaned up the device service's servicer
- Removed the plugin_test file rather than fixing the now-broken test

## Test Plan

- [x] make test

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by themarwhal — APPROVED** [review]
feg changes look good to me

**Comment by 119Vik** [comment]
RestartCWAGTests

**Comment by 119Vik** [comment]
RestartLTETests

**Review by xjtian — APPROVED** [review]
looks like straightforward boilerplate to me

**Review by uri200 — APPROVED** [review]

**Pull request merged**
