### PR TITLE
fix(agw): c++ migration of nas/ies files

### PR DESCRIPTION
**Pull request by pruthvihebbani**
Signed-off-by: Pruthvi Hebbani <pruthvi.hebbani@radisys.com>

fix(agw): c++ migration of nas/ies files
This is same as PR: https://github.com/magma/magma/pull/13988. Review comments on #13988 are also addressed in this PR.

## Summary

Migrated all the files under nas/ies to cpp/hpp and fixed all the compilation errors and warnings

## Test Plan

Executed s1ap integ_tests, bazel build and unit test

### CODE REVIEW

**Comment by pruthvihebbani** [comment]
image
Bazel build works in my local system with commad - "bazel build --config=production //lte/gateway/c/core:agw_of". But I see some failures in the CI. @nstng @LKreutzer any command to reproduce the errors in my local system?

**Comment by nstng** [comment]
> @nstng @LKreutzer any command to reproduce the errors in my local system?

Hi, the build is not failing when the library is build, it is failing when a test is build - e.g. `bazel build //lte/gateway/c/core/oai/test/amf:amf_stateless_test`. This fails for us locally as well (with the same errors as in CI).

We are unsure why this is working with make, but not with bazel. We will update when we have an idea.

**Comment by nstng** [comment]
> > @nstng @LKreutzer any command to reproduce the errors in my local system?
> 
> Hi, the build is not failing when the library is build, it is failing when a test is build - e.g. `bazel build //lte/gateway/c/core/oai/test/amf:amf_stateless_test`. This fails for us locally as well (with the same errors as in CI).
> 
> We are unsure why this is working with make, but not with bazel. We will update when we have an idea.

@pruthvihebbani Update: If I wrap
```
#ifdef __cplusplus
extern "C" {
#endif
...
#ifdef __cplusplus
}
#endif
```
around `#include "lte/gateway/c/core/common/backtrace.h"` in `lte/gateway/c/core/common/assertions.h` and
```
#include "lte/gateway/c/core/oai/common/TLVEncoder.h"
#include "lte/gateway/c/core/oai/common/TLVDecoder.h"
```
in a lot of `.cpp` files (unsure about the minimal set) then I can run successfully `bazel test //lte/gateway/c/core/oai/test/amf:amf_stateless_test` and `make test_oai BUILD_TYPE=Debug OAI_TESTS=test_amf_app`.

Can you help me to understand what the issue here is? Do we have a different build order in make and Bazel and then the include-once-guardes (e.g., `#ifndef FILE_TLV_DECODER_SEEN`, `#define FILE_TLV_DECODER_SEEN`) are causing issues?

Also I would be interested what the rule is to add the `#ifdef __cplusplus` guards during the migration.

**Comment by nstng** [comment]
> @nstng Can you share files you changed for the build to pass?

around `#include "lte/gateway/c/core/common/backtrace.h"` in `lte/gateway/c/core/common/assertions.h` and basically around all
```
#include "lte/gateway/c/core/oai/common/TLVEncoder.h"
#include "lte/gateway/c/core/oai/common/TLVDecoder.h"
```
where it was not already added. But as I said, I did not check for a minimal set.

**Review by LKreutzer — APPROVED** [review]
Bazel changes lgtm

**Review by rsarwad — APPROVED** [review]
LGTM

**Pull request merged**
