### PR TITLE
fix(agw): upgrade protobuf python package (backport)

### PR DESCRIPTION
**Pull request by ajahl**
Signed-off-by: Alex Jahl <alexander.jahl@tngtech.com>

## Summary

This is a backport PR that fixes broken builds on Magma 1.7. In 1.7, the python protobuf package are pinned to version 3.19.0. This leads to conflicts with other python packages.  Therefore, the PR updates the used protobuf package to version 3.20.3.

### CODE REVIEW

**Review by sebathomas — APPROVED** [review]
Basically a backport to fix the issues discussed in #13033.

**Review by LKreutzer — COMMENTED** [review]
Change looks reasonable. There are many workflows failing, including the bazel one, but it is in a very old state. How to proceed with this? It seems the bazel workflow is failing due to folly.

**Comment by sebathomas** [comment]
We can only force-merge it, we won't get the CI to run because it's still partially based on CircleCI on v1.7.

However, we're not sure we need this change any more. It seems it would only be required to build Magma, not to install the production release, and we're not planning to build a new release of 1.7 at the moment.

**Review by LKreutzer — APPROVED** [review]

**Comment by voisey** [comment]
Closing this because it seems it's not needed. Please reopen if you think otherwise :slightly_smiling_face:

**Pull request closed without merging**
