### PR TITLE
feat(mme): Stateless feature integration for NGAP

### LINKED ISSUE #11071: Stateless feature integration for NGAP

### PR DESCRIPTION
**Pull request by sreedharkumartn**
Signed-off-by: sreedharkumartn <sreedhar.kumar@wavelabs.ai>

## Summary
This PR consists of the flags for putting ngap_state, ngap_ue_state and ngap_imsi_map.
1. put_ngap_state (ngap_state_t, gnb_description_t).
2. put_ngap_ue_state (m5g_ue_description_t).
3. put_ngap_imsi_map (ngap_imsi_map_t).

This table shows syncing of ngap state information, ue state information, ngap imsi map to redis db at different steps.
image
- is_task_state_same will sync ngap state information.
- is_ue_state_same will sync ue state information and ngap imsi map.
- false - will sync into redis db.
- true - won't sync to redis db.

## Test Plan
- **Verified the Unit test Cases.**
UT_NGAP_Integration

- **Verified with basic sanity (Stateless - Disable)**

Environment Setup:
- Disable the switch in orc8r.
Disable_switch

- Confirmation of stateless disable in mme log.
mme_log_ss

mme log and PCAP snap.
- Corresponding mme log.
[mme_ngap_integration.log](https://github.com/magma/magma/files/7828656/mme_ngap_integration.log)

- Corresponding Packet Pcap.
image

- **Stateless feature testing (Stateless - enable)**:
Environment Setup:
- Tested with Integration of all AMF and NGAP PR's corresponding to stateless.
AMF PR's : 
#10605, 
#10805, 
#10903, 
#10853, 
#10885, 
#10906, 
#10908, 
#10958, 
#11034, 
#11090.
NGAP PR's : 
#11014, 
#11005, 
#11032, 
this PR.

- Test Plan:

    - Bring up mme. Add subscriber. Connect GNB(ueransim). Connect UE(ueransim).
    - Ue registartion and PDU session is up.
    - Do a make restart. This mimics a mme crash and the state data is lost.(1)
    - Trigger a ps-release from the ueransim's ue-cli.
    Expected behavior: The PDU session release should take place successfully. This verifies that mme has fetched
    the data from Redis DB and is successfully able to continue with the ps-release flow.
    Observered: Successfully continuation.
    - Do a make restart. This mimics a mme crash and the state data is lost.(2)
    - Trigger deregister normal from the ueransim's ue-cli.
    Expected behavior: The deregister normal should take place successfully. We receive a Guti-based registration Request.
    Observered: Successfully continuation and Guti-based registration is successful and PDU session is established.
    - Do a make restart. This mimics a mme crash and the state data is lost.(3)
    - Trigger deregister switch-off from the ueransim's ue-cli.
    Expected behavior: The deregister switch-off should take place successfully
    Observered: Deregister switch-off is successful.

- Enable the switch in orc8r.
enable_orc8r

- Confirmation of stateless enable in mme log.
image

- Redis db entries during process.
MicrosoftTeams-image

- Redis db entries after deregister switch-off.
MicrosoftTeams-image (1)

- Please find the Pcap and logs below.
[pcap_and_logs.zip](https://github.com/magma/magma/files/7828970/pcap_and_logs.zip)

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by ssanadhya — APPROVED** [review]
LGTM

**Comment by ssanadhya** [comment]
@sreedharkumartn , can you confirm if this PR can be merged on its own? If not, which PRs does it depend on?

**Comment by sreedharkumartn** [comment]
Thanks for the review comment @ssanadhya.
 #11014 should get merge before this PR.

**Review by ardzoht — APPROVED** [review]
lgtm, @sreedharkumartn is this ready to merge?

**Comment by sreedharkumartn** [comment]
@ssanadhya and @ardzoht , thanks for reviewing the PR. PR is rebased.
Please merge this PR.

**Pull request merged**
