### PR TITLE
fix(mme): reduce EPC_STATS_TIMER_MSEC back to 20s

### PR DESCRIPTION
**Pull request by uri200**
Signed-off-by: Oriol Batalla <obatalla@fb.com>

## Summary

Stats on MME are used to debug issues. Reducing its frequency to 1 min defeats the purpose of this log.

Setting this back to 20s until we have a config parameter to change that value

## Test Plan

make test at agw

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by amarpad — APPROVED** [review]
cc @ulaskozat 
Just want to make sure everyone is ok with this. This is going to be an ITT_MSG every 20 sec.

**Comment by ulaskozat** [comment]
@uri200 The idea is to not use this for debugging purposes only. Have you tested this on Spirent against GA targets? Rather than setting it to a lower value as default, could you add this to mme configuration?

**Comment by uri200** [comment]
> @uri200 The idea is to not use this for debugging purposes only. Have you tested this on Spirent against GA targets? Rather than setting it to a lower value as default, could you add this to mme configuration?

Hey @ulaskozat, note those questions should have been answered here https://github.com/magma/magma/pull/7847 when this value was increased from 20 to 60 seconds: Is there any prof the increase of this value from 20 to 60  really helped? Was this tested against GA  targets before and after the change?

If this has a real impact on performance, of course let's set it to 60. But if it does not have any, we should not compromise other features of the system.

**Comment by amarpad** [comment]
Hi @uri200 the frequency of ITTI messages were always 60s. The service303 and S1 threads were reaching into MME_APP which was a correctness issue not a logging issue. So I moved the message to ITTI. Since the MME_APP thread no longer had all the state we decided to move logging to the service303 thread and there is no point having a display frequency of 20s if the state is updated every 60s

**Comment by uri200** [comment]
Hey @amarpad so that means that to increase the frequency of that message we would need to increase the frequency of the whole IITI queue?

**Comment by amarpad** [comment]
> Hey @amarpad so that means that to increase the frequency of that message we would need to increase the frequency of the whole IITI queue?

EPC_STATS_TIMER_MSEC determines the frequency of sending ITTI messages which you are updating so this works, just that it increases the load on ITTI messages.

**Comment by uri200** [comment]
yep, but my question is: with the changes done on the previous PR the logging function can only report changes as fast as the ITTI queue. Is that right?

**Comment by ardzoht** [comment]
I think we should make this a configurable field, it is clear that there's a need for adjusting the frequency for different purposes (TeraVM as Oriol explains) with the trade-offs of performance, we can add a local service config to control this, wdyt? cc @ulaskozat @amarpad

**Comment by amarpad** [comment]
> yep, but my question is: with the changes done on the previous PR the logging function can only report changes as fast as the ITTI queue. Is that right?

yep right. All tasks report their state to the service303 thread and threads don't access each others state. MME datastructures are not thread safe so what was happening could trigger issues like https://github.com/magma/magma/issues/7421

**Comment by ulaskozat** [comment]
> > @uri200 The idea is to not use this for debugging purposes only. Have you tested this on Spirent against GA targets? Rather than setting it to a lower value as default, could you add this to mme configuration?
> 
> Hey @ulaskozat, note those questions should have been answered here #7847 when this value was increased from 20 to 60 seconds: Is there any prof the increase of this value from 20 to 60 really helped? Was this tested against GA targets before and after the change?
> 
> If this has a real impact on performance, of course let's set it to 60. But if it does not have any, we should not compromise other features of the system.

@uri200 while writing a long message on the context, I see that @amarpad has already provided it. Let's not beat ourselves on this and make this a configurable parameter with default as 60 seconds and @uri200 you can use any value you want for observability during tests.

**Comment by ulaskozat** [comment]
@uri200 @amarpad @ardzoht I will raise a PR to make this configurable...

**Pull request closed without merging**
