### PR TITLE
docs(eventd): Remove reference to Make commands

### LINKED ISSUE #14028: How to create event for eventd with Bazel?
While going through the documentation we found the section: "How-to: Create an event" in the `/workspaces/magma/docs/readmes/lte/eventd.md` file. We should figure out if this is even a use-case, and if yes, then how to do this with Bazel and update the documentation later too. (Currently documentation changes are collected in this [PR](/workspaces/magma/docs/readmes/lte/eventd.md).)

* understand the feature in `eventd.md`
  * is this only relevant for development or also for production usage (e.g. a user can add it's own events)
* play through the feature described in `eventd.md` with bazel
  * might need modification of the BUILD.bazel file
* document steps needed in #14025

### PR DESCRIPTION
**Pull request by vktng**
Signed-off-by: Krisztián Varga <krisztian.varga@tngtech.com>

## Summary

Previously `make run` was needed for Python scripts to be able to emit an event that used swagger. Since the services are bazelified this is no longer needed. A new event can be created by placing the new yml file into the `lte/swagger` directory, without any further action needed.

This closes #14028.

## Test Plan

1. Create a fresh gateway VM
2. Do the Bazel gateway VM setup as described in https://magma.github.io/magma/docs/next/lte/s1ap_tests
3. Create a new event
4. Emit the new event from a script
5. Check if the event appears in the eventd logs

Example:
New file `$MAGMA_ROOT/lte/swagger/my_events.v1.yml`:

```
---
swagger: '2.0'

info:
  title: MY event definitions
  description: These events occur in MY task
  version: 1.0.0

definitions:
  my_success:
    type: object
    description: My success
    properties:
      msg:
        type: string
```

Add the following to `$MAGMA_ROOT/lte/gateway/configs/eventd.yml`:

```
  my_success:
    module: lte
    filename: my_events.v1.yml
```

Use the following code to emit the event:
```

import snowflake
from magma.eventd.eventd_client import log_event
from orc8r.protos.eventd_pb2 import Event

log_event(
    Event(
        stream_name="magmad",
        event_type="my_success",
        tag=snowflake.snowflake(),
        value="{}",
    ),
)
```
Add this to the BUILD.bazel file in the directory, where your script is:

```
MAGMA_ROOT = "RELATIVE_PATH_TO_MAGMA_ROOT"
ORC8R_ROOT = "{}orc8r/gateway/python".format(MAGMA_ROOT)

py_binary(
    name = "your_script_name",
    srcs = ["your_script_name.py"],
    imports = [ORC8R_ROOT],
    legacy_create_init = False,
    deps = [
        "//orc8r/gateway/python/magma/eventd:eventd_client",
        "//orc8r/protos:mconfig_python_proto",
        requirement("snowflake"),
    ],
)
```

Then call the script with Bazel: `bazel run //PATH/TO/YOUR/SCRIPT:your_script_name`

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by voisey — APPROVED** [review]

**Comment by nstng** [comment]
Why not add your very detailed example to the documentation?

**Review by nstng — CHANGES_REQUESTED** [review]
Why not add your very detailed example to the documentation?

**Comment by voisey** [comment]
> Why not add your very detailed example to the documentation?

I was also thinking of requesting this, so I'd be happy if it was added.

**Comment by vktng** [comment]
> Why not add your very detailed example to the documentation?

I thought it is straightforward, I just followed the documentation that is already there. I provided the example as a quick copy-paste for testing my solution if anyone is interested. I can add it to the page if you think it adds value.

**Comment by nstng** [comment]
> > Why not add your very detailed example to the documentation?
> 
> I thought it is straightforward, I just followed the documentation that is already there. I provided the example as a quick copy-paste for testing my solution if anyone is interested. I can add it to the page if you think it adds value.

It looks very helpful to me - I think this could save people a lot of time. I vote for adding this.

**Review by nstng — APPROVED** [review]
lgtm!

**Pull request merged**
