### PR TITLE
chore: Only deploy AGW if integ-test passes

### PR DESCRIPTION
**Pull request by themarwhal**
Signed-off-by: Marie Bremner <marwhal@fb.com>

## Summary
Noticing that now we deploy agw on every build - is this on purpose? (@tmdzk / @quentinDERORY )

## Test Plan
Run `circleci config validate` locally

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by quentinDERORY — APPROVED** [review]

**Comment by quentinDERORY** [comment]
No it was not intentional ^^' , but going forward on GHA this will be the case.

**Comment by themarwhal** [comment]
> No it was not intentional ^^' , but going forward on GHA this will be the case.

@quentinDERORY  with GHA, would we have a two tier system? Like first we deploy for testing and then once all tests pass they are promoted to a staging tier? (Or some other)

**Comment by quentinDERORY** [comment]
They are currently being published on PR event to test registries.(already built) You could trigger manually advanced integ test (currently only CWF & LTE) on the PR . Merging to master will be the promotion to staging tier.

**Comment by themarwhal** [comment]
> They are currently being published on PR event to test registries.(already built) You could trigger manually advanced integ test (currently only CWF & LTE) on the PR . Merging to master will be the promotion to staging tier.

Ah I see, but we don't block the promotion to staging based on test results?

**Comment by quentinDERORY** [comment]
> > They are currently being published on PR event to test registries.(already built) You could trigger manually advanced integ test (currently only CWF & LTE) on the PR . Merging to master will be the promotion to staging tier.
> 
> Ah I see, but we don't block the promotion to staging based on test results?

yes correct we don't block promotion to staged based on test results.

**Pull request merged**
