### PR TITLE
orc8r : Segregation of Builder service as internal

### PR DESCRIPTION
**Pull request by sabithaatla**
Signed-off-by: sabithaatla <sabitha.atla@wavelabs.ai>

## Summary
This PR deals with the segregation of Builder's internal gRPC servicers implementation.
These changes are part of the ongoing work which details the distinction between Orc8r-internal gRPC endpoints vs. external, gateway-oriented gRPC endpoints.
Moved MconfigBuilder implementation to protected folder.
Verified existing UT cases.

### CODE REVIEW

**Comment by themarwhal** [comment]
Do you have more context for the motivations behind this change?

**Comment by sabithaatla** [comment]
> 
It is part of segregation of orc8r servicers as  internal and southbound servicers which is requested by Hunter.
Still it is in progress so moved to Draft PR

**Comment by uri200** [comment]
@sabithaatla  is this needed anymore. If not, can we close it please?

**Comment by sabithaatla** [comment]
Closing this PR..Raised new PR [11415](https://github.com/magma/magma/pull/11415)

**Pull request closed without merging**
