### PR TITLE
fix(nms): Added environment variables on Helm charts to be displayed on NMS

### PR DESCRIPTION
**Pull request by ShubhamTatvamasi**
Signed-off-by: Shubham Tatvamasi <shubhamtatvamasi@gmail.com>

## Summary

Added environment variables on Helm charts to be displayed on NMS for issue https://github.com/magma/magma/issues/8678

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by sudhikan** [comment]
Thanks for raising this PR @ShubhamTatvamasi. QQ do we need to bump the chart version in lte-orc8r, feg-orc8r, fbcinternal-orc8r etc. ? 

I think just bumping orc8rlib and orc8r is good right? No other charts are getting changed... ? 

@hcgatewood thoughts?

**Comment by ShubhamTatvamasi** [comment]
> Thanks for raising this PR @ShubhamTatvamasi. QQ do we need to bump the chart version in lte-orc8r, feg-orc8r, fbcinternal-orc8r etc. ? 
> 
> 
> 
> I think just bumping orc8rlib and orc8r is good right? No other charts are getting changed... ? 
> 
> 
> 
> @hcgatewood thoughts?

I have just updated the dependence chart version not the main chart version.

**Review by sudhikan — APPROVED** [review]
lgtm

requesting to backport to 1.6 please.

**Comment by hcgatewood** [comment]
> Thanks for raising this PR @ShubhamTatvamasi. QQ do we need to bump the chart version in lte-orc8r, feg-orc8r, fbcinternal-orc8r etc. ?
> 
> I think just bumping orc8rlib and orc8r is good right? No other charts are getting changed... ?
> 
> @hcgatewood thoughts?

I'm not sure, will defer to y'all 🙂

**Review by hcgatewood — APPROVED** [review]

**Review by themarwhal — APPROVED** [review]

**Comment by hcgatewood** [comment]
Hey @ShubhamTatvamasi! Looks like the Semantic PR check is failing -- here's how to fix that https://github.com/magma/magma/pull/9778#issuecomment-947351172

**Comment by ShubhamTatvamasi** [comment]
> Hey @ShubhamTatvamasi! Looks like the Semantic PR check is failing -- here's how to fix that [#9778 (comment)](https://github.com/magma/magma/pull/9778#issuecomment-947351172)

Semantic PR issue has been fixed.

**Comment by hcgatewood** [comment]
Cool cool. Next check: looks like the chart versions aren't quite lining up for wifi-orc8r https://github.com/magma/magma/runs/4088498665?check_suite_focus=true

Try rebasing onto latest master then checking it out

**Comment by ShubhamTatvamasi** [comment]
> Cool cool. Next check: looks like the chart versions aren't quite lining up for wifi-orc8r https://github.com/magma/magma/runs/4088498665?check_suite_focus=true
> 
> Try rebasing onto latest master then checking it out

Done

**Comment by hcgatewood** [comment]
Merged! Thanks for the fix

**Pull request merged**
