### PR TITLE
chore(nms): Upgrade chart-js-2 and react-chart-js

### LINKED ISSUE #13375: Upgrade chart.js and react-chartjs-2
See https://react-chartjs-2.js.org/docs/migration-to-v4 (There seems to be no list of breaking changes for v2 -> v3)

Maybe also relevant
https://www.chartjs.org/docs/latest/getting-started/v3-migration.html

### PR DESCRIPTION
**Pull request by thmsschmitt**
## Summary

* Upgrades chart-js-2 and react-chart-js .
* The moment adapter for chart-js-2 [requires moment 2](https://github.com/chartjs/chartjs-adapter-moment), but we still use moment. Therefore I would recommend to upgrade moment first https://github.com/magma/magma/issues/13377 
* Fixes https://github.com/magma/magma/issues/13375

## Test Plan

Check if all charts look like before
Screenshot 2022-08-11 at 18 00 46
Screenshot 2022-08-11 at 18 07 08
Screenshot 2022-08-11 at 17 56 52

### CODE REVIEW

**Comment by Neudrino** [comment]
- Rebased after merge of #13377

**Comment by Neudrino** [comment]
For testing I did:
- `nms$ yarn test`
- `nms$ ./e2e_test_setup.sh`
- start orc8r and nms and accessed the UI to see a diagram displayed

@sebathomas I did have some weird issue, presumably with the bundler, yesterday. However, after a clean start today, I could not systematically reproduce them. Even without code changes compared to yesterday, the tests were green for me today.
It would be good, if you could also see, whether the described tests also work fine on your machine.

**Comment by sebathomas** [comment]
Yes, they're green for me too. Don't these tests run in the CI?

**Review by sebathomas — APPROVED** [review]
Also tried starting NMS locally and didn't notice any errors.

**Comment by Neudrino** [comment]
> Yes, they're green for me too. Don't these tests run in the CI?

Yes they do. But as I have seen this errors yesterday, I thought one additional data point would not hurt here. Just to gain more confidence.

**Pull request merged**
