### PR TITLE
ci: Remove bazel-cache-push workflow

### PR DESCRIPTION
**Pull request by jheidbrink**
## Summary

Remove the "Push Bazel Cache To S3" workflow. In #13330 we stop using the zipped disk caches and use remote caches instead.

## Test Plan

not tested

## Additional Information

When this is merged, the secrets `AWS_ACCESS_KEY_AMI_BAZEL_CACHE_S3` and `AWS_SECRET_ACCESS_KEY_AMI_BAZEL_CACHE_S3` can be removed.

- [ ] This change is backwards-breaking (when pull/13330 isn't merged yet, this can slightly increase bazel build times, but not break anything)

### CODE REVIEW

**Review by LKreutzer — APPROVED** [review]
Lgtm, obviously should only be merged after https://github.com/magma/magma/pull/13330. 

Are the VM caches used anywhere at the moment?

We should keep the configs used here: `production`, `limited_mem`, `asan` for VM/devcontainer in mind as they should also be added to the bazel workflow (this is already planned).

**Comment by jheidbrink** [comment]
> obviously should only be merged after https://github.com/magma/magma/pull/13330.

It's not a strict requirement though, the codespaces would just get an older cache until #13330 is merged.

> Are the VM caches used anywhere at the moment?

No, the caches are built and uploaded, but seem unused.

> We should keep the configs used here: production, limited_mem, asan for VM/devcontainer in mind as they should also be added to the bazel workflow (this is already planned).

Yes, good point!

**Review by maxhbr — APPROVED** [review]
LGTM

**Comment by maxhbr** [comment]
I removed the secrets

**Pull request merged**
