### PR TITLE
[docs] Magma Header Update to match Magmacore.org - Take 2

### PR DESCRIPTION
**Pull request by jimmytipit**
# Summary

- This PR addresses the need to unify magma docs layout with magmacore.org site .

# Additional Information

* Creates a unified design
* Swaps docusaurus logo for magma
* Still "to do" - adjusting footer links/colors

### CODE REVIEW

**Comment by jimmytipit** [comment]
Alright - you can see the latest version with the correct 1.3.0 docs here: https://5fad5b1d80a101000881a814--competent-euler-513227.netlify.app/docs/basics/introduction.html

@xjtian @jbryce

**Comment by jimmytipit** [comment]
Final preview URL: https://5fad6649ece0d10008bf7bf8--competent-euler-513227.netlify.app/docs/basics/introduction.html

**Review by jbryce — COMMENTED** [review]
This looks good to me now. Thanks for the updates

**Comment by xjtian** [comment]
Neat. Is there a CD pipeline to automatically deploy docusaurus to magmacore.org? Where does that live in case we need to debug that?

**Comment by jimmytipit** [comment]
We are using Netlify for CD and the URL will be docs.magmacore.org. We're happy to manage this from the OIF side, but if you'd prefer to add some folks to your team let me know. We need to add additional seats to the platform.

Thanks,
Jimmy

**Review by jbryce — APPROVED** [review]

**Pull request merged**
