### PR TITLE
[Converged-MME]ts8_timer edit

### PR DESCRIPTION
**Pull request by Vyas20**
[lte][converged-mme][agw]

## Summary

Part of replacing the existing timers with zmq timers, this branch is forked from the branch in PR #4773 and contains ts8_timer edits.

## Test Plan

Testing with S1-AP Tester and dsTester.

### CODE REVIEW

**Comment by Vyas20** [comment]
MAGMA-OAI-TESTS

**Comment by Vyas20** [comment]
MAGMA-OAI-TESTS

**Review by ulaskozat — APPROVED** [review]
LGTM

**Comment by ulaskozat** [comment]
@Vyas20 can you resolve the merge conflict?

**Comment by rdefosse** [comment]
MAGMA-OAI-TESTS

**Pull request merged**
