### PR TITLE
chore: Remove unnecessary includes directory from common

### PR DESCRIPTION
**Pull request by themarwhal**
## Summary
Address https://github.com/magma/magma/issues/8446 (remove the include directory from orc8r/gateway/c/common directories to flatten it a bit)

## Test Plan
CI, manually running make test_oai

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by ssanadhya — APPROVED** [review]
Lgtm

**Comment by themarwhal** [comment]
@ShubhamTatvamasi do you happen to know why the orc8r test is failing? 

https://github.com/magma/magma/runs/6220879128?check_suite_focus=true

It's failing with the error
```bash
OK
[11157](https://github.com/magma/magma/runs/6220879128?check_suite_focus=true#step:5:11157)
Checking if helm charts are in sync
[11158](https://github.com/magma/magma/runs/6220879128?check_suite_focus=true#step:5:11158)
Actual chart version for orc8r = 1.5.28, orcl variables chart version is 1.5.27
[11159](https://github.com/magma/magma/runs/6220879128?check_suite_focus=true#step:5:11159)
Traceback (most recent call last):
[11160](https://github.com/magma/magma/runs/6220879128?check_suite_focus=true#step:5:11160)
  File "/root/scripts/test_helm_charts_sync.py", line 136, in <module>
[11161](https://github.com/magma/magma/runs/6220879128?check_suite_focus=true#step:5:11161)
    assert tf_charts_in_sync and orcl_charts_in_sync
[11162](https://github.com/magma/magma/runs/6220879128?check_suite_focus=true#step:5:11162)
AssertionError
[11163](https://github.com/magma/magma/runs/6220879128?check_suite_focus=true#step:5:11163)
Error: Process completed with exit code 1.
```

**Comment by ShubhamTatvamasi** [comment]
> @ShubhamTatvamasi do you happen to know why the orc8r test is failing?
> 
> https://github.com/magma/magma/runs/6220879128?check_suite_focus=true
> 
> It's failing with the error
> 
> ```shell
> OK
> [11157](https://github.com/magma/magma/runs/6220879128?check_suite_focus=true#step:5:11157)
> Checking if helm charts are in sync
> [11158](https://github.com/magma/magma/runs/6220879128?check_suite_focus=true#step:5:11158)
> Actual chart version for orc8r = 1.5.28, orcl variables chart version is 1.5.27
> [11159](https://github.com/magma/magma/runs/6220879128?check_suite_focus=true#step:5:11159)
> Traceback (most recent call last):
> [11160](https://github.com/magma/magma/runs/6220879128?check_suite_focus=true#step:5:11160)
>   File "/root/scripts/test_helm_charts_sync.py", line 136, in <module>
> [11161](https://github.com/magma/magma/runs/6220879128?check_suite_focus=true#step:5:11161)
>     assert tf_charts_in_sync and orcl_charts_in_sync
> [11162](https://github.com/magma/magma/runs/6220879128?check_suite_focus=true#step:5:11162)
> AssertionError
> [11163](https://github.com/magma/magma/runs/6220879128?check_suite_focus=true#step:5:11163)
> Error: Process completed with exit code 1.
> ```

Hi @themarwhal, this is orc8r version issue, I am working on the fix.

**Comment by ShubhamTatvamasi** [comment]
Here is the PR for the fix @themarwhal https://github.com/magma/magma/pull/12597

**Comment by nstng** [comment]
Hi, what about the lte include folders? Are they also relevant for this cleanup?
```
./lte/gateway/c/core/oai/include
./lte/gateway/c/core/oai/lib/gtpv2-c/nwgtpv2c-0.11/include
./lte/gateway/c/core/oai/tasks/ngap/include
./lte/gateway/c/core/oai/tasks/amf/include
./lte/gateway/c/core/oai/tasks/nas5g/include
```

**Comment by themarwhal** [comment]
> Hi, what about the lte include folders? Are they also relevant for this cleanup?
> 
> ```
> 
> ./lte/gateway/c/core/oai/include
> 
> ./lte/gateway/c/core/oai/lib/gtpv2-c/nwgtpv2c-0.11/include
> 
> ./lte/gateway/c/core/oai/tasks/ngap/include
> 
> ./lte/gateway/c/core/oai/tasks/amf/include
> 
> ./lte/gateway/c/core/oai/tasks/nas5g/include
> 
> ```

Hello! Yes i only intended to clean up the common directory.

**Review by nstng — APPROVED** [review]
bazel changes lgtm

**Review by ajahl — APPROVED** [review]

**Review by LKreutzer — APPROVED** [review]

**Pull request merged**
