### PR TITLE
chore(orc8r): Upgrade gopkg.in/yaml from v2.2.2 to v3.0.0

### PR DESCRIPTION
**Pull request by spikey979**
Signed-off-by: Kristijan <spikey979@gmail.com>

chore(orc8r): Upgrade gopkg.in/yaml from v2.2.2 to v3.0.0

## Summary

The Kubernetes API Server component in versions 1.1-1.14, and versions prior to 1.15.10, 1.16.7 and 1.17.3 allows an authorized user who sends malicious YAML payloads to cause the kube-apiserver to consume excessive CPU cycles while parsing YAML. Bug is fixed in version 2.2.8 and higher.
Issue exist in orc8r/lib/go/protos/ where package github.com/stretchr/testify v1.4.0 uses gopkg.in/yaml.v2 v2.2.2
To solve this issue, it should upgrade github.com/stretchr/testify v1.4.0 to version v1.7.0 that uses gopkg.in/yaml.v3 v3.0.0

PR is for security alert: https://github.com/magma/magma/security/dependabot/orc8r/lib/go/protos/go.sum/gopkg.in%2Fyaml.v2/open

### CODE REVIEW

**Comment by lucasgonze** [comment]
I'm curious - are you starting with a draft PR so you can see the test results?

**Comment by spikey979** [comment]
> 



> I'm curious - are you starting with a draft PR so you can see the test results?

I always test code changes locally, but it often happens that PR falls on GitHub tests. That's why in most cases I do a draft PR to see if there is an error in my code that I can still fix. When the tests run and I estimate that the code is ready for review, I create a real PR and wait for the reviewer's decision.

**Comment by themarwhal** [comment]
@spikey979 looks like insync-check is failing?

**Comment by spikey979** [comment]
> @spikey979 looks like insync-check is failing?

yes, i'm trying to find a solution

**Comment by christinewang5** [comment]
> > @spikey979 looks like insync-check is failing?
> 
> yes, i'm trying to find a solution

Looks like you need to commit all your `go.sum` and `go.mod` files!

**Comment by spikey979** [comment]
I changed github.com/stretchr/testify v1.7.0 to v1.6.0 and committed all go.sum and go.mod files

**Comment by mstre123** [comment]
Looks like ci is still failing on this one - when you get those green please resubmit for review so we can get this pushed.

**Pull request closed without merging**
