### PR TITLE
[orc8r] support onprem v1.4 + rework ansible scripts

### PR DESCRIPTION
**Pull request by ymasmoudi**
Signed-off-by: YOUSSEF EL MASMOUDI <ymasmoudi@fb.com>

## Summary

1/ support v1.4 release.
2/ reworked scripts to have consistent variables/config
3/ Removed hardcoded values to allow better sizing of the deployments.  

## Test Plan

```
TASK [magma/orc8r : orc8r | Install/upgrade helm charts] ***************************************************************************************************************************************************************************
changed: [compute1] => (item=orc8r)
changed: [compute1] => (item=lte-orc8r)
Wednesday 28 April 2021  17:32:44 +0800 (0:03:36.870)       0:16:35.880 ******* 

TASK [magma/orc8r : orc8r | Get orc8r pod] *****************************************************************************************************************************************************************************************
changed: [compute1]
Wednesday 28 April 2021  17:32:44 +0800 (0:00:00.372)       0:16:36.253 ******* 

TASK [magma/orc8r : orc8r | Get nms pod] *******************************************************************************************************************************************************************************************
changed: [compute1]
Wednesday 28 April 2021  17:32:44 +0800 (0:00:00.427)       0:16:36.681 ******* 

TASK [magma/orc8r : orc8r | Import admin_operator cert to orc8r] *******************************************************************************************************************************************************************
changed: [compute1]
Wednesday 28 April 2021  17:32:45 +0800 (0:00:00.592)       0:16:37.273 ******* 

TASK [magma/orc8r : orc8r | Set admin password in nms] *****************************************************************************************************************************************************************************
changed: [compute1]

PLAY RECAP *************************************************************************************************************************************************************************************************************************
compute1                   : ok=677  changed=192  unreachable=0    failed=0    skipped=1146 rescued=0    ignored=1   
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

Wednesday 28 April 2021  17:32:49 +0800 (0:00:03.692)       0:16:40.965 ******* 
=============================================================================== 
magma/orc8r : orc8r | Install/upgrade helm charts ------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 216.87s
magma/mariadb : mariadb | Install/upgrade helm charts --------------------------------------------------------------------------------------------------------------------------------------------------------------------- 107.11s
container-engine/docker : ensure docker packages are installed ------------------------------------------------------------------------------------------------------------------------------------------------------------- 58.05s
kubernetes/master : kubeadm | Initialize first master ---------------------------------------------------------------------------------------------------------------------------------------------------------------------- 22.36s
download : download_container | Download image if required ----------------------------------------------------------------------------------------------------------------------------------------------------------------- 22.33s
kubernetes/preinstall : Install packages requirements ---------------------------------------------------------------------------------------------------------------------------------------------------------------------- 15.94s
download : download_container | Download image if required ----------------------------------------------------------------------------------------------------------------------------------------------------------------- 15.15s
k8s_postinstall : install nfs-common --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 12.80s
container-engine/docker : ensure docker-ce repository is enabled ----------------------------------------------------------------------------------------------------------------------------------------------------------- 10.45s
download : download_container | Download image if required ----------------------------------------------------------------------------------------------------------------------------------------------------------------- 10.23s
download : download_container | Download image if required ----------------------------------------------------------------------------------------------------------------------------------------------------------------- 10.18s
kubernetes/preinstall : Update package management cache (APT) --------------------------------------------------------------------------------------------------------------------------------------------------------------- 9.54s
download : download_container | Download image if required ------------------------------------------------------------------------------------------------------------------------------------------------------------------ 9.51s
k8s_postinstall : install ntpd ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 8.29s
download : download_container | Download image if required ------------------------------------------------------------------------------------------------------------------------------------------------------------------ 7.68s
download : download_container | Download image if required ------------------------------------------------------------------------------------------------------------------------------------------------------------------ 7.59s
magma/orc8r : orc8r | precreate persistentvolumeclaims for components ------------------------------------------------------------------------------------------------------------------------------------------------------- 7.19s
kubernetes-apps/ansible : Kubernetes Apps | Lay Down CoreDNS Template ------------------------------------------------------------------------------------------------------------------------------------------------------- 7.13s
download : download_file | Download item ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 7.06s
kubernetes-apps/ansible : Kubernetes Apps | Start Resources ----------------------------------------------------------------------------------------------------------------------------------------------------------------- 6.57s
If you did not specify passwords, you can find generated passwords here:
find: inventory/cluster.local/credentials: No such file or directory
```

Screenshot 2021-04-28 at 17 40 52

### CODE REVIEW

**Comment by mattymo** [comment]
@ymasmoudi  I already have this open https://github.com/magma/magma/pull/6399

It maintains 1.3 backward compatiblity as well. Can you close this PR and offer feedback to this other PR?

**Comment by ymasmoudi** [comment]
@mattymo Sure, I will wait for your PR to be merge then, and I will update this one with the additional change we need.
thanks for the feedback.

**Comment by mattymo** [comment]
@ymasmoudi My PR landed. Can you rebase against master and see what changes you plan to propose? Note that there are differences between orc8r for magma 1.3 and 1.4.

**Comment by ekowtaylor** [comment]
@ymasmoudi do you still plan to move forward with this?

**Pull request closed without merging**
