### PR TITLE
AGW: magmad: Fix exception on newer prometheus_client

### LINKED ISSUE #6352: [lte][agw] Prometheus client dependency is broken on latest 1.5 on Ubuntu
### Your Environment

- **Version:** 1.5.0-1619194755-2adf0235
- **Affected Component:** Access Gateway
- **Affected Subcomponent:** magmad service 
- **Deployment Environment:** bare-metal

### Describe the Issue

```
Apr 23 10:49:59 phy-u1 magmad[3302764]: Traceback (most recent call last):
Apr 23 10:49:59 phy-u1 magmad[3302764]:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
Apr 23 10:49:59 phy-u1 magmad[3302764]:     return _run_code(code, main_globals, None,
Apr 23 10:49:59 phy-u1 magmad[3302764]:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
Apr 23 10:49:59 phy-u1 magmad[3302764]:     exec(code, run_globals)
Apr 23 10:49:59 phy-u1 magmad[3302764]:   File "/usr/local/lib/python3.8/dist-packages/magma/magmad/main.py", line 40, in <module>
Apr 23 10:49:59 phy-u1 magmad[3302764]:     from magma.magmad.metrics_collector import MetricsCollector, ScrapeTarget
Apr 23 10:49:59 phy-u1 magmad[3302764]:   File "/usr/local/lib/python3.8/dist-packages/magma/magmad/metrics_collector.py", line 361, in <module>
Apr 23 10:49:59 phy-u1 magmad[3302764]:     metric: prometheus_client.core.Metric) -> [metrics_pb2.MetricFamily]:
Apr 23 10:49:59 phy-u1 magmad[3302764]: AttributeError: module 'prometheus_client' has no attribute 'core'
```

**To Reproduce**
Install latest 1.5 on ubuntu AGW and start magmad

### PR DESCRIPTION
**Pull request by pshelar**
Fix following exception on Ubuntu:
```
Apr 23 19:35:08 magma magmad[1419]: Traceback (most recent call last):
Apr 23 19:35:08 magma magmad[1419]:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
Apr 23 19:35:08 magma magmad[1419]:     return _run_code(code, main_globals, None,
Apr 23 19:35:08 magma magmad[1419]:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
Apr 23 19:35:08 magma magmad[1419]:     exec(code, run_globals)
Apr 23 19:35:08 magma magmad[1419]:   File "/usr/local/lib/python3.8/dist-packages/magma/magmad/main.py", line 40, in <module>
Apr 23 19:35:08 magma magmad[1419]:     from magma.magmad.metrics_collector import MetricsCollector, ScrapeTarget
Apr 23 19:35:08 magma magmad[1419]:   File "/usr/local/lib/python3.8/dist-packages/magma/magmad/metrics_collector.py", line 361, in <module>
Apr 23 19:35:08 magma magmad[1419]:     metric: prometheus_client.core.Metric) -> [metrics_pb2.MetricFamily]:
Apr 23 19:35:08 magma magmad[1419]: AttributeError: module 'prometheus_client' has no attribute 'core'
Apr 23 19:35:08 magma systemd[1]: magma@magmad.service: Main process exited, code=exited, status=1/FAILURE
```

Signed-off-by: Pravin B Shelar <pbshelar@fb.com>

## Test Plan
Run unit tests on Ubuntu and Debian.
Run integ tests on Ubuntu and Debian.

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by ardzoht** [comment]
can we also validate with building a package for both versions? I just want to make sure that there is no indirect versions mismatch issue on the python dependencies

**Comment by pshelar** [comment]
ubuntu package built and deploys fine:
```
root@phy-u1:~# apt install magma=1.6.0-1619216884-3bb11bf3  --dry-run
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libnetplan0 python3-decorator
Use 'apt autoremove' to remove them.
The following packages will be upgraded:
  magma
1 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Inst magma [1.5.0-1619194755-2adf0235] (1.6.0-1619216884-3bb11bf3 Artifactory:focal [amd64])
Conf magma (1.6.0-1619216884-3bb11bf3 Artifactory:focal [amd64])
```

**Comment by pshelar** [comment]
Installed debian packages built with this PR:
```
root@1vagw5:/home/magma/ss1# dpkg --list |grep magma
ii  magma                                     1.6.0-1619220302-3bb11bf3         amd64        Magma Access Gateway
ii  magma-cpp-redis                           4.3.1.2-2                         amd64        Redis C++ client library
ii  magma-libfluid                            0.1.0.6-1                         amd64        Libfluid Openflow Controller
ii  magma-sctpd                               1.6.0-1619220302-3bb11bf3         amd64        Magma SCTPD
root@1vagw5:/home/magma/ss1# ls
libopenvswitch_2.8.10-2_amd64.deb			      python3-astroid_2.4.2_all.deb	    python3-idna_2.8_all.deb		       python3-prometheus-client_0.3.1_all.deb	python3-sentry-sdk_1.0.0_all.deb
libopenvswitch-dev_2.8.10-2_amd64.deb			      python3-attrs_20.3.0_all.deb	    python3-importlib-metadata_2.1.1_all.deb   python3-protobuf_3.14.0_all.deb		python3-six_1.12.0_all.deb
magma_1.6.0-1619220302-3bb11bf3_amd64.deb		      python3-bravado-core_5.16.1_all.deb   python3-importlib-resources_3.0.0_all.deb  python3-psutil_5.6.6_amd64.deb		python3-snowflake_0.0.3_all.deb
magma-sctpd_1.6.0-1619220302-3bb11bf3_amd64.deb		      python3-certifi_2019.6.16_all.deb     python3-isort_4.3.21_all.deb	       python3-pycares_3.1.1_amd64.deb		python3-spyne_2.12.16_all.deb
oai-gtp_4.9-9_amd64.deb					      python3-cffi_1.14.5_amd64.deb	    python3-itsdangerous_1.1.0_all.deb	       python3-pycparser_2.20_all.deb		python3-stevedore_1.32.0_all.deb
openvswitch-common_2.8.10-2_amd64.deb			      python3-chardet_3.0.4_all.deb	    python3-jinja2_2.10_all.deb		       python3-pycryptodome_3.9.9_amd64.deb	python3-strict-rfc3339_0.7_all.deb
openvswitch-datapath-dkms_2.8.10-2_all.deb		      python3-click_7.1.2_all.deb	    python3-jsonpointer_2.0_all.deb	       python3-pylint_2.6.2_all.deb		python3-swagger-spec-validator_2.7.3_all.deb
openvswitch-datapath-module-4.9.0-9-amd64_2.8.10-2_amd64.deb  python3-cryptography_3.2.1_amd64.deb  python3-jsonref_0.2_all.deb		       python3-pymemoize_1.0.2_all.deb		python3-systemd-python_234_amd64.deb
openvswitch-datapath-source_2.8.10-2_all.deb		      python3-cython_0.29.1_amd64.deb	    python3-jsonschema_3.1.0_all.deb	       python3-pyroute2_0.5.14_all.deb		python3-tinyrpc_1.0.4_all.deb
openvswitch-dbg_2.8.10-2_amd64.deb			      python3-dnspython_1.16.0_all.deb	    python3-js-regex_1.0.1_all.deb	       python3-pyrsistent_0.17.3_amd64.deb	python3-toml_0.10.2_all.deb
openvswitch-pki_2.8.10-2_all.deb			      python3-docker_4.0.2_all.deb	    python3-lazy-object-proxy_1.4.3_amd64.deb  python3-pystemd_0.8.0_amd64.deb		python3-typed-ast_1.4.2_amd64.deb
openvswitch-switch_2.8.10-2_amd64.deb			      python3-envoy_0.0.3_all.deb	    python3-lxml_4.6.2_amd64.deb	       python3-python-dateutil_2.8.1_all.deb	python3-urllib3_1.25.3_all.deb
openvswitch-test_2.8.10-2_all.deb			      python3-eventlet_0.26.1_all.deb	    python3-markupsafe_1.1.1_amd64.deb	       python3-python-redis-lock_3.7.0_all.deb	python3-webcolors_1.11.1_all.deb
openvswitch-testcontroller_2.8.10-2_amd64.deb		      python3-fire_0.2.0_all.deb	    python3-mccabe_0.6.1_all.deb	       python3-pytz_2020.1_all.deb		python3-webob_1.2_all.deb
openvswitch-vtep_2.8.10-2_amd64.deb			      python3-flask_1.0.2_all.deb	    python3-monotonic_1.5_all.deb	       python3-redis_3.5.3_all.deb		python3-websocket-client_0.56.0_all.deb
ovn-central_2.8.10-2_amd64.deb				      python3-freezegun_0.3.15_all.deb	    python3-msgpack_1.0.0_amd64.deb	       python3-redis-collections_0.9.0_all.deb	python3-werkzeug_0.14_all.deb
ovn-common_2.8.10-2_amd64.deb				      python3-glob2_0.7_all.deb		    python3-netaddr_0.8.0_all.deb	       python3-repoze.lru_0.7_all.deb		python3-wrapt_1.12.1_amd64.deb
ovn-controller-vtep_2.8.10-2_amd64.deb			      python3-greenlet_0.4.16_amd64.deb     python3-netifaces_0.10.9_amd64.deb	       python3-requests_2.22.0_all.deb		python3-wsgiserver_1.3_all.deb
ovn-docker_2.8.10-2_amd64.deb				      python3-grpcio_1.36.1_amd64.deb	    python3-oslo.config_2.5.0_all.deb	       python3-rfc3987_1.3.8_all.deb		python3-zipp_1.2.0_all.deb
ovn-host_2.8.10-2_amd64.deb				      python3-h2_3.2.0_all.deb		    python3-ovs_2.6.0_amd64.deb		       python3-routes_2.4.1_all.deb		python-openvswitch_2.8.10-2_all.deb
python3-aioh2_0.2.2_all.deb				      python3-hpack_3.0.0_all.deb	    python3-pbr_5.4.5_all.deb		       python3-ryu_4.30_all.deb			td-agent-bit_1.3.2_amd64.deb
python3-argparse_1.4.0_all.deb				      python3-hyperframe_5.2.0_all.deb	    python3-priority_1.3.0_all.deb	       python3-scapy_2.4.4_all.deb
```

**Comment by pshelar** [comment]
unit tests and sanity S1AP test are working fine.

**Review by ardzoht — APPROVED** [review]

**Review by themarwhal — APPROVED** [review]

**Pull request merged**
