### PR TITLE
docs: Broken links on Magma Proposals page (magma#12203)

### PR DESCRIPTION
**Pull request by platonenkoiurii**
Signed-off-by: iurii platonenko [platonenkoyuriy@gmail.com](mailto: platonenkoyuriy@gmail.com)

### CODE REVIEW

**Review by electronjoe — APPROVED** [review]

**Review by voisey — COMMENTED** [review]
Hi @platonenkoiurii, thanks for the PR! Before we can get this merged, we need to get the required CI jobs green. To fix the "DCO check", your commits need to be signed, which can be done by following the instructions [here](https://github.com/magma/magma/wiki/Contributing-Code#signed-off-commits), and to fix the "Markdown lint check", the trailing whitespace [here](https://github.com/magma/magma/pull/12659/files#diff-aa8d61a2de1a7607f92f4e4e0f1fc8293b2db56f3a0defa9fc4b79d6af4d98d7R104) needs to be removed (more info on removing such things is available [here](https://github.com/magma/magma/wiki/Contributing-Documentation#precommit)). Could you please take care of these two things?

**Comment by platonenkoiurii** [comment]
> Hi @platonenkoiurii, thanks for the PR! Before we can get this merged, we need to get the required CI jobs green. To fix the "DCO check", your commits need to be signed, which can be done by following the instructions [here](https://github.com/magma/magma/wiki/Contributing-Code#signed-off-commits), and to fix the "Markdown lint check", the trailing whitespace [here](https://github.com/magma/magma/pull/12659/files#diff-aa8d61a2de1a7607f92f4e4e0f1fc8293b2db56f3a0defa9fc4b79d6af4d98d7R104) needs to be removed (more info on removing such things is available [here](https://github.com/magma/magma/wiki/Contributing-Documentation#precommit)). Could you please take care of these two things?

For DCO - I was able to add a comment to my commit in my own fork. correct?

**Comment by platonenkoiurii** [comment]
> Hi @platonenkoiurii, thanks for the PR! Before we can get this merged, we need to get the required CI jobs green. To fix the "DCO check", your commits need to be signed, which can be done by following the instructions [here](https://github.com/magma/magma/wiki/Contributing-Code#signed-off-commits), and to fix the "Markdown lint check", the trailing whitespace [here](https://github.com/magma/magma/pull/12659/files#diff-aa8d61a2de1a7607f92f4e4e0f1fc8293b2db56f3a0defa9fc4b79d6af4d98d7R104) needs to be removed (more info on removing such things is available [here](https://github.com/magma/magma/wiki/Contributing-Documentation#precommit)). Could you please take care of these two things?

For "Markdown lint check" - can't understand how to do it, as Idon't know where and how to run commands, specified in the instruction. My assumption is that I should Fetch to my fork from upstream, do 1 more commit with corrections, run commands and create a new PR. correct? but I don't know how to run commands for "Markdown lint check".
your guidance is appreciated.

p.s. I'm new to Github

**Comment by voisey** [comment]
> > Hi @platonenkoiurii, thanks for the PR! Before we can get this merged, we need to get the required CI jobs green. To fix the "DCO check", your commits need to be signed, which can be done by following the instructions [here](https://github.com/magma/magma/wiki/Contributing-Code#signed-off-commits), and to fix the "Markdown lint check", the trailing whitespace [here](https://github.com/magma/magma/pull/12659/files#diff-aa8d61a2de1a7607f92f4e4e0f1fc8293b2db56f3a0defa9fc4b79d6af4d98d7R104) needs to be removed (more info on removing such things is available [here](https://github.com/magma/magma/wiki/Contributing-Documentation#precommit)). Could you please take care of these two things?
> 
> For DCO - I was able to add a comment to my commit in my own fork. correct?

Yes, exactly. Note that in future you may want to checkout a branch on your fork rather than using master.

For the link check, you should indeed fetch your fork, navigate to the docs folder within the repository (something like `cd magma/docs`) and then run the command to fix the formatting `make precommit_fix`. This will automatically generate the formatting changes you need. You don't need to create a new PR though, instead you can either modify your previous commit and push to this PR or add a new commit and push to this PR.

That said, if you want to start from scratch so that you can (i) checkout to a branch rather than using master, (ii) sign-off your commit using `git commit -s` and (iii) apply the formatting changes, you are welcome to create a fresh PR.

**Comment by platonenkoiurii** [comment]
1 month passed. check cannot be run
I'm closing it.

**Pull request closed without merging**
