### PR TITLE
Fixes for timer expiry for stateless mme

### PR DESCRIPTION
**Pull request by rsarwad**
Description:
Issue #1 : While testing the Implicit detach timer with MME restart observed that UE contexts were not updated to redis DB. Because on timer expiry, imsi64 was neither received from timer module nor got from the handler function. So imsi64 was set to "INVALID_IMSI64". Only for valid imsi64 values, UE contexts are updated to DB.

Approach followed to address above issue:
1. Modified code to get imsi64 for all timers on expiry.

Issue #2: The prototype of timer start function is int timer_setup(
    uint32_t interval_sec, uint32_t interval_us, task_id_t task_id,
    int32_t instance, timer_type_t type, void* timer_arg, size_t arg_size,
    long* timer_id) 
Which expects seconds and micro-seconds to be of datatype uint32_t, but for most timers while calling timer_setup, seconds and micro-seconds were defined as long
1. Modified the datatype of duration of all timers to  to match prototype of timer start function.

Test Plan:
Executed s1ap tester sanity test suite

### CODE REVIEW

**Comment by 119Vik** [comment]
Can one of the admins verify this patch?

**Comment by ulaskozat** [comment]
during commit, have you included "-s" option for sign off? check out https://github.com/magma/community/blob/main/CONTRIBUTING.md

**Comment by ulaskozat** [comment]
In the summary, could you put more context, e.g., why the change is done in addition to what the change is?

**Review by ulaskozat — CHANGES_REQUESTED** [review]
The code changes look good to me, but summary and sign off should be taken care of.

**Pull request closed without merging**
