### PR TITLE
[Doc] Add documentation for enabling Sentry

### PR DESCRIPTION
**Pull request by themarwhal**
Signed-off-by: Marie Bremner <marwhal@fb.com>

## Summary
* Add some documentation on enabling Sentry reporting on the AGW
* Also committing a generated file `docs/docusaurus/i18n/en.json`

## Test Plan
Screen Shot 2021-04-22 at 11 27 44 AM

## Additional Information

- [ ] This change is backwards-breaking

---
This change is [Reviewable](https://reviewable.io/reviews/magma/magma/6313)

### CODE REVIEW

**Review by electronjoe — APPROVED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/magma/magma/6313)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @hcgatewood, @karthiksubraveti, and @themarwhal)

___
*[docs/docusaurus/i18n/en.json, line 18 at r1](https://reviewable.io/reviews/magma/magma/6313#-MYuSWgd7Sc5X3mMPS8L:-MYuSWgd7Sc5X3mMPS8M:bx2phh3) ([raw file](https://github.com/magma/magma/blob/cc8f44122a394f016f42506a0a4dfce799fb66b7/docs/docusaurus/i18n/en.json#L18)):*
> ```JSON
>       },
>       "contributing/contribute_ci_checks": {
>         "title": "Continuous Integration Checks"
> ```

Thanks for catching this for me! Oh my, there were a lot of missing entries.
___
*[docs/docusaurus/i18n/en.json, line 391 at r1](https://reviewable.io/reviews/magma/magma/6313#-MYuT_iz2SOXD5m-ZoYW:-MYuT_iz2SOXD5m-ZoYX:b-8y99jt) ([raw file](https://github.com/magma/magma/blob/cc8f44122a394f016f42506a0a4dfce799fb66b7/docs/docusaurus/i18n/en.json#L391)):*
> ```JSON
>         "title": "AGW Ubuntu upgrade"
>       },
>       "proposals/proposal_process": {
> ```

I *think* this is supposed to remain `proposals/p014_proposal_process`?

Thanks for catching the duplicate proposal_process in here.
___
*[docs/readmes/lte/integrate_sentry.md, line 19 at r1](https://reviewable.io/reviews/magma/magma/6313#-MYub5d-8BxKQapdQZA5:-MYub5d059U4Cfn_Du_n:bw031ka) ([raw file](https://github.com/magma/magma/blob/cc8f44122a394f016f42506a0a4dfce799fb66b7/docs/readmes/lte/integrate_sentry.md#L19)):*
> ```Markdown
> ## Enabling error reporting on an AGW
> 
> Fill out the following fields in [`control_proxy.yml`](https://github.com/magma/magma/blob/master/lte/gateway/configs/control_proxy.yml#L43) to enable Sentry reporting.
> ```

I wonder if you want to link to a specific file revision instead of Master here, so that the Line numbers aren't shifted in the future. WDYT?
___
*[docs/readmes/lte/integrate_sentry.md, line 20 at r1](https://reviewable.io/reviews/magma/magma/6313#-MYubZZdBvWVibLToRxa:-MYubZZdBvWVibLToRxb:b2veyff) ([raw file](https://github.com/magma/magma/blob/cc8f44122a394f016f42506a0a4dfce799fb66b7/docs/readmes/lte/integrate_sentry.md#L20)):*
> ```Markdown
> 
> Fill out the following fields in [`control_proxy.yml`](https://github.com/magma/magma/blob/master/lte/gateway/configs/control_proxy.yml#L43) to enable Sentry reporting.
> Reporting for Python services, MME, and SessionD will *only* be enabled if the corresponding URL fields are non-empty.
> ```

Is there supposed to be a whitespace line in markdown between various styles? E.g. before ``` here? I don't have MD linting yet for CI lol.  I wonder if you want to move this "only be enabled" bit up front in this doc so the default-no-collection is up front and center?
___
*[docs/readmes/lte/integrate_sentry.md, line 29 at r1](https://reviewable.io/reviews/magma/magma/6313#-MYubu9bDqRoRgWhSQLV:-MYubu9bDqRoRgWhSQLW:b-leqmmq) ([raw file](https://github.com/magma/magma/blob/cc8f44122a394f016f42506a0a4dfce799fb66b7/docs/readmes/lte/integrate_sentry.md#L29)):*
> ```Markdown
> # If set, /var/log/mme.log will be uploaded along MME crashreports
> sentry_upload_mme_log: false
> sentry_sample_rate: 1.0
> ```

Could you comment on what sentry_sample_rate is? What are reasonable values?
___
*[docs/readmes/lte/integrate_sentry.md, line 36 at r1](https://reviewable.io/reviews/magma/magma/6313#-MYubzzN4UG2hutEOjgE:-MYubzzN4UG2hutEOjgF:bw35vbd) ([raw file](https://github.com/magma/magma/blob/cc8f44122a394f016f42506a0a4dfce799fb66b7/docs/readmes/lte/integrate_sentry.md#L36)):*
> ```Markdown
> For more information, please refer to [this documentation provided by Sentry](https://docs.sentry.io/platforms/android/data-management/debug-files/). 
> The follwing script outlines the necessary steps.
> ```
> ```

newline whitespace I think before ```?
___
*[docs/readmes/lte/integrate_sentry.md, line 45 at r1](https://reviewable.io/reviews/magma/magma/6313#-MYucDUxDoa9Xg-BWtDm:-MYucDUxDoa9Xg-BWtDn:b-a25k1t) ([raw file](https://github.com/magma/magma/blob/cc8f44122a394f016f42506a0a4dfce799fb66b7/docs/readmes/lte/integrate_sentry.md#L45)):*
> ```Markdown
> PROJECT=""
> 
> for EXEC in $EXECS_PATHS
> ```

Is this script complete? Seems like they could use advice on how to build with -g for debug symbols etc? Maybe start from the vagrant VM ssh and walk through all steps?

**Review by themarwhal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/magma/magma/6313)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @electronjoe, @hcgatewood, @karthiksubraveti, and @themarwhal)

___
*[docs/docusaurus/i18n/en.json, line 391 at r1](https://reviewable.io/reviews/magma/magma/6313#-MYuT_iz2SOXD5m-ZoYW:-MYueR2N7Kvo_RwWp_Bk:bidaw6f) ([raw file](https://github.com/magma/magma/blob/cc8f44122a394f016f42506a0a4dfce799fb66b7/docs/docusaurus/i18n/en.json#L391)):*
<details><summary><i>Previously, electronjoe (Scott Moeller) wrote…</i></summary><blockquote>

I *think* this is supposed to remain `proposals/p014_proposal_process`?

Thanks for catching the duplicate proposal_process in here.
</blockquote></details>

I can fix the proposal doc ID to keep it at p014 : https://github.com/magma/magma/blob/master/docs/readmes/proposals/p014_proposal_process.md
(see that the id is proposal_process without 14)
1
___
*[docs/readmes/lte/integrate_sentry.md, line 19 at r1](https://reviewable.io/reviews/magma/magma/6313#-MYub5d-8BxKQapdQZA5:-MYufcm65Mi4nfKKaazn:b1x6gyq) ([raw file](https://github.com/magma/magma/blob/cc8f44122a394f016f42506a0a4dfce799fb66b7/docs/readmes/lte/integrate_sentry.md#L19)):*
<details><summary><i>Previously, electronjoe (Scott Moeller) wrote…</i></summary><blockquote>

I wonder if you want to link to a specific file revision instead of Master here, so that the Line numbers aren't shifted in the future. WDYT?
</blockquote></details>

yeah goodcall! 
___
*[docs/readmes/lte/integrate_sentry.md, line 20 at r1](https://reviewable.io/reviews/magma/magma/6313#-MYubZZdBvWVibLToRxa:-MYufk0a4Yufg4tOvcf6:b-h41yj9) ([raw file](https://github.com/magma/magma/blob/cc8f44122a394f016f42506a0a4dfce799fb66b7/docs/readmes/lte/integrate_sentry.md#L20)):*
<details><summary><i>Previously, electronjoe (Scott Moeller) wrote…</i></summary><blockquote>

Is there supposed to be a whitespace line in markdown between various styles? E.g. before ``` here? I don't have MD linting yet for CI lol.  I wonder if you want to move this "only be enabled" bit up front in this doc so the default-no-collection is up front and center?
</blockquote></details>

right, that would make sense :D 
___
*[docs/readmes/lte/integrate_sentry.md, line 29 at r1](https://reviewable.io/reviews/magma/magma/6313#-MYubu9bDqRoRgWhSQLV:-MYuhGRN7H8_tEAltGKw:b-896fix) ([raw file](https://github.com/magma/magma/blob/cc8f44122a394f016f42506a0a4dfce799fb66b7/docs/readmes/lte/integrate_sentry.md#L29)):*
<details><summary><i>Previously, electronjoe (Scott Moeller) wrote…</i></summary><blockquote>

Could you comment on what sentry_sample_rate is? What are reasonable values?
</blockquote></details>

Done.
___
*[docs/readmes/lte/integrate_sentry.md, line 36 at r1](https://reviewable.io/reviews/magma/magma/6313#-MYubzzN4UG2hutEOjgE:-MYuhH6w7Q2zsyQ93ysQ:b-896fix) ([raw file](https://github.com/magma/magma/blob/cc8f44122a394f016f42506a0a4dfce799fb66b7/docs/readmes/lte/integrate_sentry.md#L36)):*
<details><summary><i>Previously, electronjoe (Scott Moeller) wrote…</i></summary><blockquote>

newline whitespace I think before ```?
</blockquote></details>

Done.
___
*[docs/readmes/lte/integrate_sentry.md, line 45 at r1](https://reviewable.io/reviews/magma/magma/6313#-MYucDUxDoa9Xg-BWtDm:-MYuhIpxBbpieRFWqlkX:b-rwv3nq) ([raw file](https://github.com/magma/magma/blob/cc8f44122a394f016f42506a0a4dfce799fb66b7/docs/readmes/lte/integrate_sentry.md#L45)):*
<details><summary><i>Previously, electronjoe (Scott Moeller) wrote…</i></summary><blockquote>

Is this script complete? Seems like they could use advice on how to build with -g for debug symbols etc? Maybe start from the vagrant VM ssh and walk through all steps?
</blockquote></details>

`-g` is included in the build commands, unless the user fiddles around with the compiler flags. But I'll put in a sentence about how the flag is necessary.

**Review by themarwhal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/magma/magma/6313)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @electronjoe, @hcgatewood, @karthiksubraveti, and @themarwhal)

___
*[docs/docusaurus/i18n/en.json, line 391 at r1](https://reviewable.io/reviews/magma/magma/6313#-MYuT_iz2SOXD5m-ZoYW:-MYuhZHZ4TxDhHu55T-w:b-896fix) ([raw file](https://github.com/magma/magma/blob/cc8f44122a394f016f42506a0a4dfce799fb66b7/docs/docusaurus/i18n/en.json#L391)):*
<details><summary><i>Previously, themarwhal (Marie) wrote…</i></summary><blockquote>

I can fix the proposal doc ID to keep it at p014 : https://github.com/magma/magma/blob/master/docs/readmes/proposals/p014_proposal_process.md
(see that the id is proposal_process without 14)
1
</blockquote></details>

Done.

**Review by electronjoe — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/magma/magma/6313)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @electronjoe, @hcgatewood, @karthiksubraveti, and @themarwhal)

___
*[docs/docusaurus/i18n/en.json, line 391 at r1](https://reviewable.io/reviews/magma/magma/6313#-MYuT_iz2SOXD5m-ZoYW:-MYuhz032kZ1rb73NZnT:bm5i4v2) ([raw file](https://github.com/magma/magma/blob/cc8f44122a394f016f42506a0a4dfce799fb66b7/docs/docusaurus/i18n/en.json#L391)):*
<details><summary><i>Previously, themarwhal (Marie) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Whoops... I thought I checked that before commenting - but maybe I only checked the document name and not the ID.  Duplication of data man.. we have a lot of it in this process (what, like 5 places with the same string?).

**Review by electronjoe — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/magma/magma/6313)* status: all files reviewed, 1 unresolved discussion

___
*[docs/docusaurus/i18n/en.json, line 18 at r1](https://reviewable.io/reviews/magma/magma/6313#-MYuSWgd7Sc5X3mMPS8L:-MYy4fHS5HKGwlBeLwnj:bb6ywmx) ([raw file](https://github.com/magma/magma/blob/cc8f44122a394f016f42506a0a4dfce799fb66b7/docs/docusaurus/i18n/en.json#L18)):*
<details><summary><i>Previously, electronjoe (Scott Moeller) wrote…</i></summary><blockquote>

Thanks for catching this for me! Oh my, there were a lot of missing entries.
</blockquote></details>

LGTM
___
*[docs/readmes/lte/integrate_sentry.md, line 19 at r1](https://reviewable.io/reviews/magma/magma/6313#-MYub5d-8BxKQapdQZA5:-MYy5GK--OSbbvdPxMi1:bb6ywmx) ([raw file](https://github.com/magma/magma/blob/cc8f44122a394f016f42506a0a4dfce799fb66b7/docs/readmes/lte/integrate_sentry.md#L19)):*
<details><summary><i>Previously, themarwhal (Marie) wrote…</i></summary><blockquote>

yeah goodcall! 
</blockquote></details>

LGTM
___
*[docs/readmes/lte/integrate_sentry.md, line 20 at r1](https://reviewable.io/reviews/magma/magma/6313#-MYubZZdBvWVibLToRxa:-MYy5Cp17xy9cIoxOuID:bb6ywmx) ([raw file](https://github.com/magma/magma/blob/cc8f44122a394f016f42506a0a4dfce799fb66b7/docs/readmes/lte/integrate_sentry.md#L20)):*
<details><summary><i>Previously, themarwhal (Marie) wrote…</i></summary><blockquote>

right, that would make sense :D 
</blockquote></details>

LGTM
___
*[docs/readmes/lte/integrate_sentry.md, line 29 at r1](https://reviewable.io/reviews/magma/magma/6313#-MYubu9bDqRoRgWhSQLV:-MYy5BaK6o87Pr47QXK8:bb6ywmx) ([raw file](https://github.com/magma/magma/blob/cc8f44122a394f016f42506a0a4dfce799fb66b7/docs/readmes/lte/integrate_sentry.md#L29)):*
<details><summary><i>Previously, themarwhal (Marie) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM
___
*[docs/readmes/lte/integrate_sentry.md, line 36 at r1](https://reviewable.io/reviews/magma/magma/6313#-MYubzzN4UG2hutEOjgE:-MYy5Jx_5Il_TC1dBjfH:bb6ywmx) ([raw file](https://github.com/magma/magma/blob/cc8f44122a394f016f42506a0a4dfce799fb66b7/docs/readmes/lte/integrate_sentry.md#L36)):*
<details><summary><i>Previously, themarwhal (Marie) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM
___
*[docs/readmes/lte/integrate_sentry.md, line 45 at r1](https://reviewable.io/reviews/magma/magma/6313#-MYucDUxDoa9Xg-BWtDm:-MYy5S1eAz-deCXRIhvI:b2izl49) ([raw file](https://github.com/magma/magma/blob/cc8f44122a394f016f42506a0a4dfce799fb66b7/docs/readmes/lte/integrate_sentry.md#L45)):*
<details><summary><i>Previously, themarwhal (Marie) wrote…</i></summary><blockquote>

`-g` is included in the build commands, unless the user fiddles around with the compiler flags. But I'll put in a sentence about how the flag is necessary. 
</blockquote></details>

I think my general point was that it's unclear to me what steps you have to carry out before running this script. But maybe this process (the build process) is well documented elsewhere? Can you link here?
___
*[docs/readmes/proposals/p014_proposal_process.md, line 3 at r2](https://reviewable.io/reviews/magma/magma/6313#-MYy5dK79Xg_axxwYrv2:-MYy5dK79Xg_axxwYrv3:b-20v9sz) ([raw file](https://github.com/magma/magma/blob/a665020590fc514c00440d7d9bbda62591481867/docs/readmes/proposals/p014_proposal_process.md#L3)):*
> ```Markdown
> ---
> id: p014_proposal_process
> id: proposal_process
> ```

BTW, UGH I did this LOL

**Pull request merged**
