### PR TITLE
[orc8r][NMS][helm] Updated the service name for orc8r API in NMS helm chart

### PR DESCRIPTION
**Pull request by ShubhamTatvamasi**
Signed-off-by: Shubham Tatvamasi <shubhamtatvamasi@gmail.com>

## Summary

Updated the service name of orc8r API in NMS helm chart.

## Test Plan

Get the latest orc8r API service:
```bash
kubectl get svc orc8r-nginx-proxy -n orc8r
```
> namespace can differ

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by karthiksubraveti — CHANGES_REQUESTED** [review]
Thanks for the change. 

Following chart versions have to be bumped up as well
-> orc8r/cloud/helm/orc8r/Chart.yaml
as shown here -> https://github.com/magma/magma/pull/4982/files 

Also update the orc8r chart version here
orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf

As shown here - https://github.com/magma/magma/pull/4988/files

**Comment by ShubhamTatvamasi** [comment]
Updated the Charts version on orc8r.

**Review by mpgermano — CHANGES_REQUESTED** [review]
Thanks for this. Looks good. Can you regenerate the lock file for the orc8r chart:
```
cd magma/orc8r/cloud/helm/orc8r
helm dependency update
```

**Comment by ShubhamTatvamasi** [comment]
Updated Chart.lock

**Review by mpgermano — APPROVED** [review]

**Review by karthiksubraveti — APPROVED** [review]

**Pull request merged**
