### PR TITLE
[5G: MVC][Sctpd][Sctp] 5g Association

### PR DESCRIPTION
**Pull request by sandeepkmall**
## Summary

 
Sctpd & Sctp changes for 5G communication. 

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by Aitezazzahid — APPROVED** [review]

**Comment by ulaskozat** [comment]
Please add the test plan.

**Comment by ulaskozat** [comment]
It looks like a number of checks are failing, please address the issues. If this PR is the replacement for another PR, close the other PR.

**Comment by sandeepkmall** [comment]
> It looks like a number of checks are failing, please address the issues. If this PR is the replacement for another PR, close the other PR.

https://github.com/magma/magma/pull/2534 is closed now.

**Comment by ssanadhya** [comment]
@sandeepkmall , for the failing `insync-checkin` test, please run `build.py -g` under `orc8r/cloud/docker/` directory and commit the generated ".go" files in this PR.

**Comment by ulaskozat** [comment]
can you rebase and make sure that the tests pass?

**Pull request closed without merging**
