### PR TITLE
docs(orc8r): Adds how-to guide for deploying orc8r with Juju

### PR DESCRIPTION
**Pull request by gruyaume**
## Summary

This PR contains the same code as https://github.com/magma/magma/pull/13008.
Adds documentation to deploy orc8r using Juju.

### CODE REVIEW

**Comment by Neudrino** [comment]
FYI: https://docs.magmacore.org/docs/next/docs/docs_overview#howto

**Comment by voisey** [comment]
Hi @gruyaume, thanks for this. It seems your last commit is missing the sign off - could you please add this and rebase while doing so? Then I think we can merge :slightly_smiling_face:

**Comment by gruyaume** [comment]
> Hi @gruyaume, thanks for this. It seems your last commit is missing the sign off - could you please add this and rebase while doing so? Then I think we can merge slightly_smiling_face

Should be fixed now, hopefully...

**Review by voisey — APPROVED** [review]

**Comment by maxhbr** [comment]
Sorry to be annoying, but `Check Rebase` is red and that prevents merge, can you please rebase ;)

**Comment by gruyaume** [comment]
> Sorry to be annoying, but `Check Rebase` is red and that prevents merge, can you please rebase ;)

Sure I just rebased and now this PR contains 95 commits (still only my 3 files changed though). I'm not sure if this was the expected behaviour.

**Comment by sebathomas** [comment]
Normally, this shouldn't happen. Maybe you accidentally merged instead of rebasing? Why do you get the commit "[Merge remote-tracking branch 'origin/dev-juju' into dev-juju](https://github.com/magma/magma/pull/13161/commits/32a30689d7b310e6896de6dd873296093b932422)"?

**Comment by gruyaume** [comment]
> Normally, this shouldn't happen. Maybe you accidentally merged instead of rebasing? Why do you get the commit "[Merge remote-tracking branch 'origin/dev-juju' into dev-juju](https://github.com/magma/magma/pull/13161/commits/32a30689d7b310e6896de6dd873296093b932422)"?

Yeah I managed to fix this, thank you!

**Comment by voisey** [comment]
Thanks for fixing this @gruyaume! I've set auto-merge so this will get merged once the Jenkins job passes

**Pull request merged**
