### PR TITLE
feat: Magma Domain Proxy - Domain Proxy application

### PR DESCRIPTION
**Pull request by m-trojanowski**
Signed-off-by: Marcin Trojanowski <marcin.trojanowski@freedomfi.com>

[WIP]: Magma Domain Proxy

## Summary
As concluded in https://github.com/magma/magma/pull/10230
This set of PRs is a proposal of a merge of Domain Proxy development into Magma codebase.

As discussed in a community meeting with @talkhasib , @hcgatewood, @jpad-freedomfi, @aswin-alexander, @bbarritt and others, this PR is a first step of discussion on how to include the ongoing development of vendor neutral Domain Proxy code into Magma's codebase.

The PR consists of a few commit's, each commit intended to target a specific section of magma code and its ownership.
Please review and comment if this division makes logical sense. We could either proceed with having one PR with such commits, or we can issue individual PRs per each section/domain.

Currently we have 5 PRs in this set which breaks code in somewhat more reviewable chunks:
1) Helm charts integration - this development has already been reviewed by @hcgatewood 
2) Orchestrator deployment integration
3) Domain Proxy: AGW side - integration with AGW/enodebd (LTE module) based on Baicells 436Q eNB
4) Domain Proxy: ORC8R side - domain proxy microservices that interact with AGW/enodebd and SAS server
5) Github workflows

The Domain Proxy part presented here, with minor alternations done due to rebase onto magmas master, has been fully tested in a local lab - helm, deployment, DProxy in orc8r interface with AGW, Baicells 436Q eNB able to be fully configured.

The code is now capable of acquiring and maintaining a SAS grant on behalf of a Baicells 436Q and fully configure it for transmission via TR069.

### CODE REVIEW

**Comment by ardzoht** [comment]
@m-trojanowski thanks for adding the details of the splitted PRs plan and their content. This PR however looks really large for providing the most meaningful review, is there any way this could be splitted as well? e.g. separating `dp/cloud/go` `dp/cloud/python` and `dp/tools` 

Of course if there's a requirement for merging these together for dependency/breakage concerns, we can separate them in a different way. thoughts?

**Comment by xbend** [comment]
@ardzoht 
Thanks for the feedback. During our meeting with codeowners we decided to split the Domain Proxy PRs this way. (Originally we had one PR with 5 commits but we were advised to have 1 PR per commit)

Separating the code further will make it even more difficult to have the PRs merged correctly and all together - and you are right that the partial merges make no sense in the sense of dependency and breakage.

Secondly, eventually the Domain Proxy ownership will fall onto us, who developed it. We initially thought that the community could take a look at high level code issues, super obvious mistakes and so on. Code essense will be very hard to explain in review blocks as the funcionality is pretty complex.

Please keep in mind that those Domain Proxy PRs here are a one time deal - we introduce a whole new feature with complex functionality, and so the code is large.
Further development will be significantly smaller as we will introduce smaller changes.
@hcgatewood FYI

**Review by hcgatewood — APPROVED** [review]
Gave it a skim. As discussed, the application-level code is intended to be code-owned by FF, so my review here is a stamp rather than a codeowner approval

**Comment by xbend** [comment]
@hcgatewood @emakeev 
We have updated the PR to pass the static code analysis tools in the CI.
We only have a problem now with the codecov and c/c++ codecov CI runs (As seen in the last check run), but on those results I fall back to your expertise.

**Comment by ardzoht** [comment]
@xbend There is an unrelated failure on the MME unit test check given that this PR is not touching any code under that module, I manually triggered a retry on the job to check if it's not a flake.

**Comment by ardzoht** [comment]
@xbend This is now ready to merge, and it has required approvals, let me know if you need help merging it to close this one.

**Comment by xbend** [comment]
@ardzoht 
Unfortunately we do not yet have authority to complete a merge.
Effectively at some point, freedomfi devs should get maintainer status for this DProxy code.

As for the merge, it would be ideal for us that the Domain Proxy related PRs (this, #10528, #10529, #10530 and #10531) are merged together as much as possible.
#10530 and #10531 CI success depends on this one, so this has to be merged first. Ideal situation would be that all PRs get the `LGTM` approvals, so that we can quickly merge and ensure that CI dependencies are quickly resolved for the dependent PRs.

**Pull request merged**
