### PR TITLE
feat(ci): Add federated integ test for HSS

### PR DESCRIPTION
**Pull request by orion-belt**
Signed-off-by: kharade <rohan.kharade@openairinterface.org>

## Summary
Merge after https://github.com/magma/magma/pull/13781

This PR adds Federated Integ Test  to validate HSS s6a interface. Here we are reusing existing  [lte-integ-tests](https://github.com/magma/magma/tree/master/lte/gateway/python/integ_tests/s1aptests) in fedrated mode.
#### Following tests are added in this PR which leverages HSS s6a interface over federated gateway -
```bash
test_attach_service_without_mac.py
test_attach_detach_with_mme_restart.py
test_attach_mme_restart_detach_multi_ue.py
test_attach_detach_looped.py
test_attach_ipv4v6_pdn_type.py
test_standalone_pdn_conn_req.py
test_attach_detach_dedicated_multi_ue.py
test_attach_detach_dedicated_bearer_deactivation_invalid_imsi.py
```
## Test Plan

We are reusing some of existing and relevant tests from  lte-integ-tests. The [sheet attached](https://docs.google.com/spreadsheets/d/1oI1FvX1AFaYQDuH85oMJsCu7X20tox248mXsuCFes0c/edit#gid=0) describes the priority and relevancy of tests. Please feel free to update sheet accordingly.

Following tests are already introduced in master 
```bash
test_attach_auth_failure.py
test_no_auth_response.py
test_nas_non_delivery_for_auth.py
test_sctp_abort_after_auth_req.py
test_sctp_shutdown_after_auth_req.py
test_no_auth_resp_with_mme_restart_reattach.py
test_send_error_ind_for_dl_nas_with_auth_req.py
test_attach_auth_mac_failure.py
test_no_auth_response_with_mme_restart.py
test_no_security_mode_complete.py
test_no_attach_complete.py
test_attach_detach_security_algo_eea0_eia0.py
test_attach_detach_security_algo_eea1_eia1.py
test_attach_detach_security_algo_eea2_eia2.py
test_attach_security_mode_reject.py
test_attach_missing_imsi.py
test_duplicate_attach.py
test_attach_emergency.py
test_attach_detach_after_ue_context_release.py
test_attach_esm_information_wrong_apn.py
test_attach_detach_secondary_pdn_invalid_apn.py
test_standalone_pdn_conn_req_with_apn_correction.py
```

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by pruthvihebbani** [comment]
Can you please mention what tests were done and attach the result under test plan?

**Comment by orion-belt** [comment]
> Can you please mention what tests were done and attach the result under test plan?

I have updated description of test plan. Waiting for [fed test fix PR](https://github.com/magma/magma/pull/13781) to be merged so that I can attach workflow test result here.

**Review by pruthvihebbani — APPROVED** [review]
LGTM

**Comment by orion-belt** [comment]
@pruthvihebbani 
Please find latest run for the new tests 
https://github.com/orion-belt/magma/actions/runs/2991306152

**Review by pruthvihebbani — APPROVED** [review]

**Pull request merged**
