### PR TITLE
chore(xwf): Remove the Express WiFi directory since code is not being maintained

### PR DESCRIPTION
**Pull request by ssanadhya**
Signed-off-by: Shruti Sanadhya <ssanadhya@fb.com>

## Summary

Support for Express WiFi with Magma is not being maintained any more, hence cleaning up this code.

Once this PR is merged, we will remove the [approvers-xwf](https://github.com/orgs/magma/teams/approvers-xwf) team

## Test Plan

N/A

### CODE REVIEW

**Review by crasu — APPROVED** [review]

**Review by maxhbr — APPROVED** [review]
LGTM. Always good to get rid of code!

**Review by LKreutzer — APPROVED** [review]
If within scope: the line ` "./xwf/gateway/deploy"` in `bazel/scripts/check_py_bazel.sh` could also be removed in this PR. 

Thanks for the clean up!

**Review by LKreutzer — APPROVED** [review]

**Review by crasu — APPROVED** [review]

**Review by LKreutzer — APPROVED** [review]

**Comment by LKreutzer** [comment]
> If within scope: the line ` "./xwf/gateway/deploy"` in `bazel/scripts/check_py_bazel.sh` could also be removed in this PR.

@crasu pushed a commit on this PR with this change, but it seems it was overwritten by the force push. Can we add this change again?

**Review by maxhbr — APPROVED** [review]
Changes to Codeowners file look good

**Review by aharonnovo — APPROVED** [review]

**Pull request merged**
