### PR TITLE
fix(agw): Updated AGW Install script branch to v1.8 (#13996) [backport to v1.8]

### PR DESCRIPTION
**Pull request by MagmaCIBot**
# Backport

This will backport the following commits from `master` to `v1.8`:
 - [fix(agw): Updated AGW Install script branch to v1.8 (#13996)](https://github.com/magma/magma/pull/13996)

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

### CODE REVIEW

**Review by sebathomas — APPROVED** [review]

**Review by voisey — APPROVED** [review]

**Review by panyogesh — APPROVED** [review]
LGTM

**Comment by ShubhamTatvamasi** [comment]
@tmdzk `agw-workflow` and `Bazel Build & Test` tests are failing, what should we do here?

**Comment by sebathomas** [comment]
Looks like the same issue we had on master, it's caused by an upgrade of a third-party dependency. See #13946.

**Comment by tmdzk** [comment]
Let's focus on merging that and getting everything else fixed. But those changes aren't breaking master 

My 2c

**Comment by tmdzk** [comment]
Force backporting it

**Pull request merged**
