### PR TITLE
fix(agw): updated debian repo for 1.8.0 release

### PR DESCRIPTION
**Pull request by ShubhamTatvamasi**
Signed-off-by: Shubham Tatvamasi <shubhamtatvamasi@gmail.com>

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by m-govind — APPROVED** [review]
Looks good to me.

**Review by panyogesh — APPROVED** [review]

**Review by maxhbr — CHANGES_REQUESTED** [review]
This change should not go on master

**Comment by maxhbr** [comment]
This change implies, that magma installations would start installing 1.8.0 from testing registry as the latest release?

**Comment by maxhbr** [comment]
Yes, close that and go directly to v1.8

**Comment by ShubhamTatvamasi** [comment]
> Yes, close that and go directly to v1.8

Okay

**Pull request closed without merging**
