### PR TITLE
refactor(orc8r): Remove old northbound listSubscribers handler

### LINKED ISSUE #8359: Remove old northbound listSubscribers handler
## Prerequisites 

- [ ] Go through the prerequisites section in the magma doc to install all dependencies: https://docs.magmacore.org/docs/next/basics/prerequisites
- [ ] Try building / running the Orc8r by following: https://docs.magmacore.org/docs/next/basics/quick_start_guide#terminal-tab-2-build-orchestrator
- [ ] Try building / running the NMS: https://docs.magmacore.org/docs/next/basics/quick_start_guide#using-the-nms-ui

## Action

Old handler: https://github.com/magma/magma/blob/50c1b7f34342c63f861baa56275b45bfb41b45c0/lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers.go#L136-L149

New handler: https://github.com/magma/magma/blob/50c1b7f34342c63f861baa56275b45bfb41b45c0/lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers.go#L189-L213

We don't use the old handler anymore, so can remove it in favor of the new handler

## Validation Steps
1. Run all Orc8r unit tests: https://docs.magmacore.org/docs/next/orc8r/dev_testing
2. Regenerate Magma <-> NMS API Bindings.js: https://docs.magmacore.org/docs/next/orc8r/dev_testing#pre-build-code-generation
3. Bring up the NMS locally to check everything compiles

## Followup task
https://github.com/magma/magma/issues/8662

### PR DESCRIPTION
**Pull request by RhnSharma**
Signed-off-by: Rohan Sharma <rhnsharma5113@gmail.com>

Fixes #8359

Hi @hcgatewood, how does this look?
Let me know if this needs any changes.
Thanks

## Summary
Removed the old listSubscribers handler from `lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers.go` because it is not used anymore.

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by hcgatewood** [comment]
Hey @RhnSharma! Thanks for opening this PR, super excited to have your contribution

I think there are 3 things we'll need to get this merged

1. Fix compilation failure. This will probably also then cause some tests to fail, which you can either remove or update to use the v2 endpoint. Here's the Orc8r testing overview: https://magma.github.io/magma/docs/next/orc8r/dev_testing
2. Update the swagger.yml to remove the old endpoint definition: https://github.com/magma/magma/blob/master/lte/cloud/go/services/subscriberdb/obsidian/models/swagger.v1.yml#L43-L85
3. Sync with @andreilee to ensure this won't break the NMS (our UI)

Let me know if you have any questions, I'm available on Slack as well

**Comment by quentinDERORY** [comment]
@hcgatewood, @RhnSharma  This line https://github.com/magma/magma/blob/e4b9d5a072a0a8ba475f736e3063f43e269398ca/lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers.go#L73 makes the cloud workflow ci pipeline break as it's still referencing the deleted function. Make sure to remove it.

**Review by hcgatewood — CHANGES_REQUESTED** [review]
Clearing my review queue. See my comments above 🙂

**Comment by ekowtaylor** [comment]
@RhnSharma , @hcgatewood any plans to move this forward?

**Comment by hcgatewood** [comment]
Closing due to inactivity

**Pull request closed without merging**
