### PR TITLE
[feg] In this PR we bring in FeG helm chart with kubevirt support.

### PR DESCRIPTION
**Pull request by reddydodda**
## Summary

Whats part of this PR: 

1. Add new helm chart for FeG with Kubevirt support

2. Rename current chart dir to feg-virtlet

## Additional Information

- [* ] This change is backwards-breaking

Signed-off-by: reddydodda <reddydodda@gmail.com>

### CODE REVIEW

**Review by mpgermano — CHANGES_REQUESTED** [review]
It looks like the only change needed is the deployment template. Can we continue to use one helm chart and have a kubevirt deployment template and a virtlet deployment template? We can set which one to use based on the values. This will be more easily maintained in the future.

**Comment by reddydodda** [comment]
@mpgermano  good idea .. let me work on that.

**Comment by reddydodda** [comment]
@mpgermano  please review FeG chart. if this structure looks good I will make changes to cwf.

**Comment by sudhikan** [comment]
> It looks like the only change needed is the deployment template. Can we continue to use one helm chart and have a kubevirt deployment template and a virtlet deployment template? We can set which one to use based on the values. This will be more easily maintained in the future.

hey @mpgermano - I don't foresee using virtlet due to sr-iov limitations and netplan corruption issues we've seen in the past... thoughts on just abandoning Virtlet altogether?

**Comment by reddydodda** [comment]
@mpgermano  @sudhikan  whats final plan for these charts? do we need to have 2 separate charts now and purge virtlet chart once all deployments migrate to kubevirt ?

**Comment by mpgermano** [comment]
Cool let's just go with kubevirt then. @reddydodda You can remove the virtlet deployment. Looks good otherwise

**Review by mpgermano — APPROVED** [review]

**Pull request merged**
