### PR TITLE
fix(orc8r): Upgrade docker tags on helm charts

### PR DESCRIPTION
**Pull request by ShubhamTatvamasi**
Signed-off-by: Shubham Tatvamasi <shubhamtatvamasi@gmail.com>

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by ShubhamTatvamasi** [comment]
Hi @tmdzk, we have to upgrade docker tags in our helm charts. Should we also upgrade helm versions or just docker tags in values.yaml is enough? Then we can re-release helm charts with the latest docker tags.

**Comment by tmdzk** [comment]
> Hi @tmdzk, we have to upgrade docker tags in our helm charts. Should we also upgrade helm versions or just docker tags in values.yaml is enough? Then we can re-release helm charts with the latest docker tags.

we should do both

**Comment by ShubhamTatvamasi** [comment]
> > Hi @tmdzk, we have to upgrade docker tags in our helm charts. Should we also upgrade helm versions or just docker tags in values.yaml is enough? Then we can re-release helm charts with the latest docker tags.
> 
> we should do both

Okay, on it.

**Comment by ShubhamTatvamasi** [comment]
Hi @tmdzk, now helm chart version is also updated.

**Review by tmdzk — APPROVED** [review]

**Comment by tmdzk** [comment]
We need to backport to v1.7 right? @ShubhamTatvamasi

**Comment by ShubhamTatvamasi** [comment]
> 

Yes @tmdzk, we have to backport this to v1.7 branch also. Should I create another PR for that?

**Review by maxhbr — APPROVED** [review]
Changes look sensible

**Pull request merged**
