### PR TITLE
[Stateless_MME] [Bug_Fix] Fixed stateless test for multi ue with attach_restart_attach_restart_detach

### LINKED ISSUE #3397: [agw][stateless] Stress testing with S1ap tests
- Reliability: Run each service restart test case multiple times
- Scalability: 
-- Increase number of UEs in existing stateless tests, i.e. restart MME after every attach
-- Attach multiple UEs, restart MME and then detach all UEs
-- Attach one UE, restart MME, attach another UE, restart MME, and so on, then start detaching UEs with MME restart after each detach

### PR DESCRIPTION
**Pull request by VinashakAnkitAman**
## Title
[Stateless_MME] [Bug_Fix] Fixed stateless test for multi UE with attach_restart_attach_restart_detach

## Summary
The test case was getting stuck during detach when running the following scenario:
Steps in action:
        1-Attach
        2-MmeRestart + wait for 30 seconds
        3-Repeat step 1 and 2 in loop for all UEs
        4-Detach
        5-Repeat step 4 in loop for all UEs
The reason was that the mme_teid_s11 value was obtained using ue_mm_context pointer and getting same value after every MME restart and this was causing the overwriting of data on same index for all the UEs. Therefore after 1st UE detach the data was cleared and the next UE detach was failing, causing the S1APTester to stuck waiting for UE context release command message. This PR fixes the issue.

Referring to Magma Issue : #3397 

## Test Plan
Verified with Sanity and ran a new test case to run above scenario.

Signed-off-by: VinashakAnkitAman <ankit.aman@radisys.com>

### CODE REVIEW

**Review by ssanadhya — APPROVED** [review]

**Comment by ssanadhya** [comment]
RestartIntegrationTests

**Comment by ssanadhya** [comment]
@VinashakAnkitAman , as this PR is changing the `mme_nas_state.proto` file, could you please run `build.py -g` from `magma/orc8r/cloud/docker` to generate the Go bindings for the proto too. That should fix the failure in `insync-checkin` CI check.

**Review by ssanadhya — CHANGES_REQUESTED** [review]
Changes in PR #3968 address this issue with a simpler logic.

**Comment by VinashakAnkitAman** [comment]
The issue is not observed after taking the changes from the PR #3968. Closing the issue.

**Pull request closed without merging**
