### PR TITLE
Revert "Remove unrelated network types from Magma NMS"

### PR DESCRIPTION
**Pull request by karthiksubraveti**
This reverts commit d1667ad46a1926053762505413265e991c6e5278.

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by Scott8440** [comment]
Should we remove the rhino stuff and anything that isn't relevant anymore?

**Comment by karthiksubraveti** [comment]
> Should we remove the rhino stuff and anything that isn't relevant anymore?

Yes. But I want to remove that in a separate PR. I thought it might be better to revert this initially and later remove Rhino and other networks which are no longer being supported.

**Comment by Scott8440** [comment]
Can you test that a mesh network will load and add a screenshot? Just want to make sure before we push this

**Comment by karthiksubraveti** [comment]
> Can you test that a mesh network will load and add a screenshot? Just want to make sure before we push this

Screen Shot 2020-09-18 at 3 06 31 PM

**Review by Scott8440 — APPROVED** [review]
good stat padding ;)

**Pull request merged**
