### PR TITLE
fix(agw): packaging of python dep

### LINKED ISSUE #10144: Missing subscriberdb folder after install
When doing `apt install magma` the installed package seems to be missing a new folder`subscription` on `/usr/local/lib/python3.8/dist-packages/magma/subscriberdb`. 

That folder was introduced in this PR https://github.com/magma/magma/pull/9775

On the deb package we can see there is no folder `subscription` when we do 
```
magma@ubuntuAGW:/var/cache/apt/archives$ sudo dpkg-deb -c magma_1.7.0-1636062920-b403d7da_amd64.deb | grep -e "subscriberdb/subscription"
```

The folder and files under `subscription` should be included on the deb package

http://github.com/magma/magma/blob/55996da47db74f21505c1fbeff08adb98f3fc20d/lte/gateway/python/magma/subscriberdb/subscription/__init__.py#L11-L11

### PR DESCRIPTION
**Pull request by quentinDERORY**
Signed-off-by: quentinDERORY <15911421+quentinDERORY@users.noreply.github.com>

## Summary

MIssing package folder in agw python dep

## Test Plan

will test packages

### CODE REVIEW

**Review by pshelar — APPROVED** [review]
Thanks!

**Comment by uri200** [comment]
btw, isn't it a way to make this script to recursively include any package under a specific folder ?

I havent reviewed this but something like https://newbedev.com/how-to-add-package-data-recursively-in-python-setup-py

**Review by ulaskozat — APPROVED** [review]
LGTM

**Comment by ulaskozat** [comment]
cc @panyogesh

**Comment by quentinDERORY** [comment]
Waiting for ci to complete checks. There is an issue with GitHub actions right now ! (ticket opened with github https://support.github.com/ticket/personal/0/1385354)

**Pull request merged**
