### PR TITLE
fix(agw): Modified code to remove dependency from common state manager for spgw task

### PR DESCRIPTION
**Pull request by rsarwad**
## Summary
fix(agw): Modified code to remove dependency from common state manager for spgw task
## Test Plan
Executed s1ap sanity test suite and unit test cases

### CODE REVIEW

**Review by LKreutzer — COMMENTED** [review]
Please add a note on why the test needs to be deleted.

**Comment by nstng** [comment]
Will review after  #14810 is merged and PR is rebased.

**Comment by panyogesh** [comment]
@rsarwad : Most of the changes are already integrated. We are planning to go ahead and close the PR. Let us know your throughts.

**Comment by panyogesh** [comment]
@rsarwad : We are planning to mark this PR as closed. Hope it should be fine.

**Comment by Sathyaj27** [comment]
Closing this PR

**Pull request closed without merging**
