### PR TITLE
[docs] Cut v1.3.0 version on docs

### PR DESCRIPTION
**Pull request by xjtian**
Signed-off-by: Jacky Tian <xjtian@fb.com>

## Summary

- `yarn run version 1.3.0`

## Test Plan

- Deployed locally

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by xjtian** [comment]
awaiting another AGW artifact version bump

**Comment by xjtian** [comment]
Note to self: will need to update migration docs after #3100 lands

**Comment by xjtian** [comment]
Just kidding we're not targeting 3100 for the release anymore

**Review by hcgatewood — APPROVED** [review]
Lgtm

**Pull request merged**
