### PR TITLE
Test td agent

### LINKED ISSUE #4816: [CDR][EventD] Add re-try logic to EventD in case of failure
## Logging pipeline and potential failure points
* GW Service → EventD (Within AGW)
    * via GRPC
    * Failure is propagated back to service
    * Possible failure causes
        * GRPC connection error (rare)
        * Event validation error (Probably due to misconfiguration)
* EventD → FluentBit (Within AGW)
    * TCP
    * Failure is propagated back to the original GW service
    * Possible failure causes
        * FluentBit is not enabled (Config issue)
* FluentBit → FluentD (AGW -> Orc8r)
    * TLS
    * Failure is ignored 
    * Possible failure causes
        * FluentD / Orc8r unreachable 

In order to reduce the likelihood of events getting lost due to connection error, we will add a configuration to enable retry logic in FluentBit.

### PR DESCRIPTION
**Pull request by themarwhal**
## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by 119Vik** [comment]
RestartCWAGTests

**Comment by 119Vik** [comment]
RestartCWAGTests

**Comment by andreilee** [comment]
The `retry_on_failure` property should be in the event definitions rather than the event registries. Would there be a case where that property would be different between events on an LTE gateway, or CWF gateway?

**Comment by themarwhal** [comment]
@andreilee I'm not sure if it would make sense for the retry-on-failure flag to be inside the definition as it's a static configuration for each event.

**Pull request closed without merging**
