### PR TITLE
Update config.yml

### PR DESCRIPTION
**Pull request by AyliD**
Added Building of xwf go radius to cwag-deploy and created dependency of publishing images based on xwfm tests

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by AyliD — COMMENTED** [review]
After fixing yaml file to validate processing

$ circleci config validate /tmp/config.yaml
Config file at /tmp/config.yaml is valid.

**Review by AyliD — COMMENTED** [review]
After fixing yaml file to validate processing

$ circleci config validate /tmp/config.yaml
Config file at /tmp/config.yaml is valid.

also making xwfm test to run only on master cause on env vars dependencies.

**Review by tmdzk — APPROVED** [review]

**Comment by tmdzk** [comment]
@AyliD can you sign your commits please ? This [job](https://github.com/magma/magma/pull/2091/checks?check_run_id=917928663) is required to merge

**Comment by mpgermano** [comment]
Similar functionality was recently merged. Closing.

**Pull request closed without merging**
