### PR TITLE
build(orc8r): fix mongo driver dependency

### PR DESCRIPTION
**Pull request by nikolakn**
Signed-off-by: Nikola Knezevic <nkcodeplus@gmail.com>

## Summary

update go-swagger@v0.21.0 to go-swagger@v0.26.0

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by themarwhal** [comment]
Hey @nikolakn ! Is there an issue that describes why we want to upgrade it specifically? Is the current version not compatible with something? If you could update the summary or attach an issue that would be great :).

**Comment by nikolakn** [comment]
Hi @themarwhal , this is PR for this ticket: https://github.com/magma/magma/issues/10017
we are still learning workflow and this PR will probably be closed.

**Comment by themarwhal** [comment]
> Hi @themarwhal , this is PR for this ticket: #10017
> we are still learning workflow and this PR will probably be closed.

Great! thanks for linking :)

**Comment by lucasgonze** [comment]
We need to learn how to interpret these test results:

"28 cancelled, 32 skipped, 2 expected, 4 neutral, and 4 successful checks "

There were no failures. The cancellations, skips and neutrals are weaknesses in the tests. I don't know what "expected" means.

@themarwhal how would you interpret these? What is the social convention for acceptance based on test results?

**Comment by quentinDERORY** [comment]
> We need to learn how to interpret these test results:
> 
> "28 cancelled, 32 skipped, 2 expected, 4 neutral, and 4 successful checks "
> 
> There were no failures. The cancellations, skips and neutrals are weaknesses in the tests. I don't know what "expected" means.
> 
> @themarwhal how would you interpret these? What is the social convention for acceptance based on test results?

There was a github action incident on Friday last week, we had to cancel all jobs to fix it... Can you amend your last commit and repush to trigger everything again?

**Comment by themarwhal** [comment]
> We need to learn how to interpret these test results:
> 
> "28 cancelled, 32 skipped, 2 expected, 4 neutral, and 4 successful checks "
> 
> There were no failures. The cancellations, skips and neutrals are weaknesses in the tests. I don't know what "expected" means.
> 
> @themarwhal how would you interpret these? What is the social convention for acceptance based on test results?

Can you try rebasing onto latest master and pushing again? I think there was a GitHub Actions outage a few days ago, so maybe this PR was affected.

**Comment by electronjoe** [comment]
Looks like the rebase got crossed somehow - as  the PR is now quite broad?

**Comment by nikolakn** [comment]
> Looks like the rebase got crossed somehow - as the PR is now quite broad?

I will close PR and create new one

**Pull request closed without merging**
