### PR TITLE
feat(orc8r): Context propagation in entity loading configurator functions

### PR DESCRIPTION
**Pull request by xjtian**
## Summary

Context propgation in the rest of configurator client API

## Test Plan

make test

## Additional Information

- [ ] This change is backwards-breaking

Signed-off-by: Jacky Tian <jacky@xjtian.com>

### CODE REVIEW

**Comment by andreilee** [comment]
Is there more context on what we're going to do with this?

**Comment by xjtian** [comment]
> Is there more context on what we're going to do with this?

This is necessary setup work for distributed tracing so you can propagate tracing headers and analyze spans.

**Review by andreilee — APPROVED** [review]

**Review by themarwhal — APPROVED** [review]

**Review by hcgatewood — APPROVED** [review]
Lgtm, need to fix conflicts

**Comment by xjtian** [comment]
@hcgatewood rebased on master

**Comment by andreilee** [comment]
Looks like there might need to be another rebase - see `insync checkin job`

**Comment by xjtian** [comment]
Fixed

**Pull request merged**
