### PR TITLE
chore: update validator to >= 13.7.0

### PR DESCRIPTION
**Pull request by lucasgonze**
chore: update validator to >= 13.7.0

## Summary

Upgrade @fbcnms/{sequelize-models,platform-server} to pick up updates that (transitively) bump `validator` package.

## Test Plan

cd nms; yarn run test

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by themarwhal** [comment]
Hi @lucasgonze ! Please only label a PR as `ready2merge` once it has been approved and passes all checks.

**Comment by lucasgonze** [comment]
> Hi @lucasgonze ! Please only label a PR as `ready2merge` once it has been approved and passes all checks.

Hi @themarwhal. The failures are spurious and are not related to the content.

* The Check-rebase failure is caused by time waiting for merge. A PR submitter has a limited ability to influence this.
* The first nms-workflow failure is this bug: https://github.com/magma/magma/issues/11221
* The second nms-workflow failure is also a CI bug (`Service "magmalte" uses an undefined secret file "/home/runner/work/magma/magma/.cache/test_certs/admin_operator.pem"`)

**Comment by themarwhal** [comment]
Sorry, I should have been more specific. I am unable to merge the PR unless all checks marked as required are passing. The check rebase job can be ignored in this case as it is not a mandatory check. However, the NMS failures are. 

We try to process PRs marked as ready2merge as often as we can to help move PRs along. This PR cannot be merged as it is missing approvals by the NMS reviewers (@andreilee / @HannaFar ) and is failing mandatory checks.  I would appreciate it if you can add back the label once it's been reviewed and passes the checks. 

If you would like the PR to be merged as soon as it is reviewed, please leave a note indicating that to the NMS maintainers. Otherwise, we'll try to get the PR merged within 1-2 business days once the label is added back.

Thanks!

**Comment by lucasgonze** [comment]
So ready2merge is for items that have been approved but not merged - is that right?

**Comment by themarwhal** [comment]
> So ready2merge is for items that have been approved but not merged - is that right?

Yes, that is correct. :)

**Review by andreilee — APPROVED** [review]

**Pull request merged**
