### PR TITLE
[SessionD][AAA][MME] Deprecate CreateSession fields that are no longer used

### PR DESCRIPTION
**Pull request by themarwhal**
## Summary
Remove proto fileds in CreateSessionRequest and LocalCreateSessionRequest that are no longer are used. The removed fields have been migrated into either CommonSessionContext or RatSpecificContext.

## Test Plan
SessionD/MME unit tests
S1AP test
CWF IntegTest

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by uri200 — APPROVED** [review]
LGTM

**Review by ssanadhya — APPROVED** [review]
Changes in lte/gateway/c/oai/lib/pcef/pcef_handlers.cpp LGTM

**Review by emakeev — APPROVED** [review]

**Review by ulaskozat — APPROVED** [review]
LGTM

**Review by hcgatewood — APPROVED** [review]
Cloud changes are generated, lgtm

**Pull request merged**
