### PR TITLE
chore(agw): Move script-only dependencies to scripts folders

### LINKED ISSUE #12754: Move python module code to script folders
Python files that are not used in the modules they are defined in should be moved to the respective script folders: `(lte|orc8r)/gateway/python/scripts/`
This includes:

-   "./orc8r/gateway/python/magma/common/health/docker_health_service.py"
-   "./orc8r/gateway/python/magma/common/health/health_service.py"
-   "./orc8r/gateway/python/magma/common/health/entities.py"
-   "./lte/gateway/python/magma/health/health_service.py"
-   "./lte/gateway/python/magma/health/entities.py"
-   "./lte/gateway/python/magma/pipelined/pg_set_session_msg.py"

### PR DESCRIPTION
**Pull request by jheidbrink**
## Summary

Move Python files that are imported from scripts but not from Python services to the scripts folder.

## Test Plan

Executed files ending with `_cli.py`in the `{lte,orc8r}/gateway/python/scripts` folders.

### CODE REVIEW

**Comment by jheidbrink** [comment]
Closing, this was only meant to be opened after another PR

**Comment by jheidbrink** [comment]
I had to remove the `__init__.py`s, otherwise when running `~/magma/lte/gateway/python/scripts$ ./agw_health_cli.py` I get
```
Traceback (most recent call last):
  File "/home/vagrant/build/python/bin/health_cli.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/vagrant/magma/orc8r/gateway/python/scripts/health_cli.py", line 19, in <module>
    from scripts.docker_health_service import DockerHealthChecker
ModuleNotFoundError: No module named 'scripts.docker_health_service'
```

**Review by LKreutzer — COMMENTED** [review]
In pairing

**Review by nstng — APPROVED** [review]
CI/Bazel changes LGTM

**Review by Neudrino — APPROVED** [review]

**Review by sebathomas — APPROVED** [review]

**Pull request merged**
