### PR TITLE
fix(amf): Fix for NG setup failure on N1 link restoration 

### PR DESCRIPTION
**Pull request by Sujay-Radtonics**
## Summary

When N1 link is removed and inserted back, it did not get restored. There was a NG setup failure. 
The reason for failure was that gNB state in AGW was in RESETTING state. 
When N1 link is removed, SCTP link down notification is seen. At this point all the connected UEs on this gnb associations needs to be context cleaned and put into IDLE state.  When all UEs info are cleaned up, gNB state will be changed from RESETTING to INIT. Post that NGAP init will be successful. 

Fixes :
During SCTP down notification, UE context was not cleaned up due to 
1. Mismatch in arguments used in call of amf_app_handle_ngap_ue_context_release () in amf_app_handle_gnb_deregister_ind()
2. In function ngap_remove_ue(), gnb_ue_id used to cleanup hash tables instead of amf_ue_id which is the key for the tables
3. In amf_app_handle_ngap_ue_context_release() function, context release calls not done for NGAP_SCTP_SHUTDOWN_OR_RESET without which proper cleanup does not happen in AMF and NGAP.

## Test Plan

   Tested with N1 link failure condition with BTI radio and AGW. 
image

### CODE REVIEW

**Review by panyogesh — APPROVED** [review]
LGTM

**Comment by MoritzThomasHuebner** [comment]
The `amf_procedures_test` is currently failing. See: https://github.com/magma/magma/actions/runs/4316617710/jobs/7532682108

**Comment by Sujay-Radtonics** [comment]
@panyogesh, @MoritzThomasHuebner - Yes, I will check the failure and update.

**Comment by Krishnavamsi-wavelabs** [comment]
Hi @Sujay-Radtonics,
As mentioned in the Summary, When N1 link is removed, SCTP link down notification is seen. At this point all the connected UEs on this gnb associations needs to be context cleaned and put into IDLE state.
but here in UNIT TEST, expected_mm_state and expected_cm_state, where it was incorrectly set to REGISTERED_CONNECTED and M5GCM_IDLE. Here is the patch for corrected states.
[n1.docx](https://github.com/magma/magma/files/12866772/n1.docx)

**Pull request merged**
