### PR TITLE
[SessionD] Remove TERMINATION_SCHEDULED fsm state

### PR DESCRIPTION
**Pull request by themarwhal**
## Summary
We don't need a dedicated state for pending termination. If SessionD restarts, we can simply re-check whether a termination is needed or not.

## Test Plan
make precommit_sm

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by uri200** [comment]
Isn't this state useful in case we receive REauth for a session that is scheduled for termination?

Maybe we should add that functionality to `update_session_credits_and_rules `?

**Comment by themarwhal** [comment]
@uri200 So we actually don't support cancellation of the termination scheduling. The only reason we don't reject the session on init right away is to give some time for the phone to switch from Wifi -> LTE. So in reality I don't think we need to support a ReAuth durning this time period. The state currently there only for the case where sessiond crashes during the scheduled period, and this we can do without a state.

**Comment by uri200** [comment]
Oh I was not saying to support reauth. On the contrary, I just wanted to make sure that if something comes from the core while we are waiting for the session to be terminated, it will be ignored

**Review by uri200 — APPROVED** [review]

**Comment by themarwhal** [comment]
@uri200 Ah I understand! Yes since the termination is scheduled we will terminate no matter what.

**Pull request merged**
