### PR TITLE
Format cmakelist files consistently

### PR DESCRIPTION
**Pull request by amarpad**
Format cmakelist files consistently

Tab: 4 spaces
Indentation: 2
Continuing Indentation: 4

No-op change, outside just making file formats consistent

Signed-off-by: Amar Padmanabhan <amarpadmanabhan@fb.com>

### CODE REVIEW

**Review by themarwhal — APPROVED** [review]
lgtm!

**Comment by themarwhal** [comment]
Is there a particular tool you used to make this happen?

**Comment by electronjoe** [comment]
> Is there a particular tool you used to make this happen?

I think Amar may be using `cmake_format` - he had discussed this with me but I'm not sure. https://github.com/cheshirekow/cmake_format

**Comment by amarpad** [comment]
> > Is there a particular tool you used to make this happen?
> 
> I think Amar may be using `cmake_format` - he had discussed this with me but I'm not sure. https://github.com/cheshirekow/cmake_format

Yeah I used that but its already 1000+ file change, didn't want to add cmake_format to the build too. Its a no-op beyond just fixing formatting.

**Pull request merged**
