### PR TITLE
Fixed the wrong path to hosts in README.md to reset the cluster

### PR DESCRIPTION
**Pull request by diorgesl**
Signed-off-by: Diorges Rocha diorges@gis.net.br

## Additional Information

### CODE REVIEW

**Review by mattymo — APPROVED** [review]

**Review by rdefosse — APPROVED** [review]

**Review by rdefosse — CHANGES_REQUESTED** [review]
`DCO Check` is failing.

@diorgesl 

this SHALL be fixed before merging.

**Comment by ekowtaylor** [comment]
@diorgesl, @rdefosse  any plans to move this forward?

**Comment by rdefosse** [comment]
> 
> 
> @diorgesl, @rdefosse any plans to move this forward?

@ekowtaylor 

The DCO check is still failing and it requires for the contributor (@diorgesl ) to re-commit properly.

Regards
Raphael

**Comment by ekowtaylor** [comment]
@diorgesl can you help implement the needed changes so this PR can be merged?

**Pull request closed without merging**
