### PR TITLE
chore: Test int test job

### PR DESCRIPTION
**Pull request by jwagantall**
Signed-off-by: Jessica Wagantall <jwagantall@linuxfoundation.org>

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by jwagantall** [comment]
RestartCWAGTests

**Comment by jwagantall** [comment]
RestartCWAGTests

**Review by quentinDERORY — CHANGES_REQUESTED** [review]
Let's not modify anything until we have the job working in the new jenkins.
And ultimately I think we will simply delete these scripts from there as they will be in the ci-management repo

**Comment by jwagantall** [comment]
testing to see if my build passes with the same additional stage you added in your workflow. but having issues with the triggers... let me check why this one is not triggering.. :/

**Comment by jwagantall** [comment]
I will leave for now the clean env stage.. until after we switch over to the new Jenkins

**Comment by ekowtaylor** [comment]
@jwagantall any plans to move forward with this PR?

**Comment by jwagantall** [comment]
Thank you!.. this was just a test PR.. it is no longer needed. 

Closing it now.

**Pull request closed without merging**
