### PR TITLE
docs: apply correct Markdown syntax for links

### PR DESCRIPTION
**Pull request by mpfirrmann**
Signed-off-by: Marco Pfirrmann <marco.pfirrmann@tngtech.com>

## Summary

Markdown liner [failed on #14815](https://github.com/magma/magma/actions/runs/3873244911/jobs/6603044885). Separate PR because this is unrelated to the changes there. The link to the Grafana dashboards was adapted to point to the current location.

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by LKreutzer — APPROVED** [review]

**Comment by LKreutzer** [comment]
I also noticed this, but why does this only show up now? I do not see any recent change in this file.

**Comment by mpfirrmann** [comment]
> I also noticed this, but why does this only show up now? I do not see any recent change in this file.

It came up in the checks for #14815 which edits the file, but not merged yet.

**Comment by LKreutzer** [comment]
> > I also noticed this, but why does this only show up now? I do not see any recent change in this file.
> 
> It came up in the checks for #14815 which edits the file, but not merged yet.

Yes, it also came up on https://github.com/magma/magma/pull/14809, but why does it show up now? Did we update anything regarding the Markdown linter or so?

**Comment by LKreutzer** [comment]
I am guessing the reason is this change https://github.com/DavidAnson/markdownlint/commit/5a4cf179c42646a0ad48c3f9522fe324849d73ba. I will see if we can fix the version.

**Pull request merged**
