### PR TITLE
refactor: Replace all usages of ent with the SQL implementation

### PR DESCRIPTION
**Pull request by reginawang3495**
## Summary
Replace all usages of ent with the SQL implementation

## Test Plan

- run `cd ${MAGMA_ROOT}/orc8r/cloud/docker && ./build.py -t ; noti`
- followed [the Quick Start Guide](https://magma.github.io/magma/docs/next/basics/quick_start_guide) up until being able to run `https://localhost:9443/swagger/v1/ui`

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by hcgatewood — CHANGES_REQUESTED** [review]
Lgtm! Two things then gtg

1. Fix cloud lint failures
2. Spin up local dev orc8r, make some swagger ui requests, then watch the logs after 5-10 minutes to make sure there aren't any error logs or service restarts, just to double check

**Comment by reginawang3495** [comment]
Did both!

**Review by themarwhal — COMMENTED** [review]
deferring the final review to @hcgatewood (stamping so that you have approvals for feg/)

**Review by themarwhal — APPROVED** [review]

**Review by hcgatewood — APPROVED** [review]
Lgtm, waiting on #9541 before we merge

**Comment by reginawang3495** [comment]
Finished merging, waiting for checks to pass

**Pull request merged**
