### PR TITLE
[docs][feg] Adding FFWA setup guide

### PR DESCRIPTION
**Pull request by joary**
[docs][feg]

## Summary

Added Federated-FWA Setup Guide

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by themarwhal — APPROVED** [review]
thank you very much :)

**Review by uri200 — APPROVED** [review]

**Comment by uri200** [comment]
👍

**Comment by uri200** [comment]
I think you have to commit signed and push force it again
```
git co -b ffwa_setup_guide
git commit --amend -s    
git push --force origin ffwa_setup_guide
```

For future commits remember to add the `-s` flag so they are signed. Also if you do some changes through github, the change will not be signed, so you will end up having to pushforce it.

**Comment by xjtian** [comment]
Docs are trunk-only, don't add the apply-v1.3 label

**Pull request merged**
