### PR TITLE
docs: Readme for GTP Ext Header Commit Details

### PR DESCRIPTION
**Pull request by prabinakpattnaik**
Signed-off-by: prabina pattnaik <prabinak@wavelabs.ai>

## Summary
Readme for GTP Ext header for QFI support commit details.
The OVS changes PR details (#10556 ).

## Additional Information
Logs:
Table 0 flow entries:

```
(python) vagrant@magma-dev-focal:~/magma/lte/gateway/python/scripts$ sudo ovs-ofctl -O OpenFlow13 dump-flows gtp_br0 table=0
 cookie=0x0, duration=24.707s, table=0, n_packets=0, n_bytes=0, priority=65503,tun_id=0x80000000,qfi=9,in_port=gtp0 actions=set_field:02:00:00:00:00:01->eth_src,set_field:ff:ff:ff:ff:ff:ff->eth_dst,set_field:0->reg9,set_field:0x181c9->metadata,resubmit(,1)
 cookie=0x0, duration=24.680s, table=0, n_packets=0, n_bytes=0, priority=65503,ip,in_port=LOCAL,nw_dst=192.168.128.11 actions=set_field:0x2710->tun_id,set_field:192.168.60.16->tun_dst,set_field:0x8000->reg8,set_field:oam->tun_flags,set_field:0x9->qfi,set_field:0x181c9->metadata,resubmit(,1)
 cookie=0x0, duration=24.680s, table=0, n_packets=0, n_bytes=0, priority=65503,ip,in_port=mtr0,nw_dst=192.168.128.11 actions=set_field:0x2710->tun_id,set_field:192.168.60.16->tun_dst,set_field:0x8000->reg8,set_field:oam->tun_flags,set_field:0x9->qfi,set_field:0x181c9->metadata,resubmit(,1)
 cookie=0x0, duration=24.680s, table=0, n_packets=0, n_bytes=0, priority=65503,arp,in_port=LOCAL,arp_tpa=192.168.128.11 actions=set_field:0x181c9->metadata,resubmit(,1)
 cookie=0x0, duration=24.680s, table=0, n_packets=0, n_bytes=0, priority=65503,arp,in_port=mtr0,arp_tpa=192.168.128.11 actions=set_field:0x181c9->metadata,resubmit(,1)
 cookie=0x0, duration=64981.449s, table=0, n_packets=27, n_bytes=1890, priority=10,in_port=ipfix0 actions=goto_table:201
 cookie=0x0, duration=64976.292s, table=0, n_packets=0, n_bytes=0, priority=0,in_port=ipfix0 actions=resubmit(,201)
 cookie=0x0, duration=64976.292s, table=0, n_packets=23, n_bytes=1610, priority=0,in_port="li_port" actions=resubmit(,202)
 cookie=0x0, duration=64976.292s, table=0, n_packets=206, n_bytes=15712, priority=0 actions=resubmit(,1)
```

### CODE REVIEW

**Comment by maxhbr** [comment]
What I was suggesting in the meeting is, to have a table that matches **a set of patches / patch-level** to **a pinned file (by version or even by hash) in artifactory**. So, if someone stumbles over a package in artifactory, it should be possible to map it to the patches+sources that were used.

**Comment by maxhbr** [comment]
I would expect something like:

| OVS upstream version | Artifact | Artifact Hash | Used code | Used patches | uploaded by | date |
| --- | --- | --- | --- | --- | --- | --- |
| 2.15 | openvswitch-common_2.15.4-9_amd64.deb | `f045...764a` | https://github.com/magma/magma/commit/d6025236f7d518629d412346bd9ee82ffa07a907 | everything up to `0024-QFI-support-in-OVS.patch` | @prabinakpattnaik | 2022-07-05 |

**Review by maxhbr — APPROVED** [review]
I think that table has the necessary columns. Once the final hash is defined, it can be merged

**Review by maxhbr — CHANGES_REQUESTED** [review]
Artifact hash column should specify which algorithm was used

**Comment by voisey** [comment]
FYI the reviewdog markdown lint complaints that are currently here can be ignored as they were broken but have now been fixed via https://github.com/magma/magma/pull/13227. That said, rebasing might lead to updated complaints.

**Review by maxhbr — CHANGES_REQUESTED** [review]
Patch files are not treated as immutable and are modified afterwards (see https://github.com/magma/magma/pull/13281/files), this undermines this whole documentation effort and we need to find some alternative or something stricter.

**Comment by nstng** [comment]
Hi, is this PR still in progress or has this become obsolete?

**Comment by nstng** [comment]
> Hi, is this PR still in progress or has this become obsolete?

I will close this for now - please reopen, if this is still relevant.

**Pull request closed without merging**
