### PR TITLE
fix(agw): create mme_ip parameter

### PR DESCRIPTION
**Pull request by hakeen0618**
Summary
Support agw enodebdetailConfiguration add a new parameter mme_ip.

Additional Information

### CODE REVIEW

**Comment by hakeen0618** [comment]
because some error is in this ci

**Comment by hakeen0618** [comment]
update the eslint error

**Comment by hakeen0618** [comment]
debug the eslint file

**Comment by ulaskozat** [comment]
What is the purpose of this PR? The summary provides no useful context.

**Comment by hakeen0618** [comment]
Summary
Support agw enodebdetailConfiguration add a new parameter mme_ip.


Additional Information

**Comment by hakeen0618** [comment]
> What is the purpose of this PR? The summary provides no useful context.
This PR added a enodedConfiguration parameter mme_ip, modify the ui , data model sending and config.

**Comment by hcgatewood** [comment]
Hey @hakeen0618 thanks for taking the time to open this PR! Unfortunately until we have a convincing summary (including reason for the addition), we'll have to defer the PR. So I'll go ahead and close this PR for now

If you want to deploy Magma with this change, just a note that you can still achieve this by building and running Magma directly from your fork 🙂

**Pull request closed without merging**
