### PR TITLE
refactor: remove job queue impl reindexer

### PR DESCRIPTION
**Pull request by reginawang3495**
## Summary
- remove reindexer's nonsingleton version
- rename reindexer's singleton version to be the default reindexer
- remove all dependencies correlated with the nonsingleton reindexer that is no longer being used

## Test Plan
- [x] run `orc8r` tests on intellij
- [x] deploy on dev env and validate it works
    - [x] deploy and see right services spun up
    - [x] validate manually 

**Test Steps:**
1. `./build.py` in `orc8r/docker`
2. `./run.py`
3.  Check that `orc8r_worker` is successfully running
     - `docker-compose exec controller bash`
     - `supervisorctl`
4. Exit out and make sure it's reindexing properly
     - `docker exec -it orc8r_postgres_1 psql -U magma_dev`
     - `select * from indexer_versions`
     - `update indexer_versions set version_actual=0;`
     - `select` should look like ` lte          |              0 |               1` to ` lte          |              1 |               1` within a minute

- [ ] deploy helm charts and validate it works
    - [ ] deploy and see right services spun up
    - [ ] validate reindexing manually 
   

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by reginawang3495** [comment]
Next:
- https://github.com/magma/magma/issues/10293
- https://github.com/magma/magma/issues/10295

This will be a huge PR that will be split into 4 or 5 pull requests when it is more close to being merged

**Comment by andreilee** [comment]
Are you planning on running those items in the test plan after this pull request has been merged?

**Comment by reginawang3495** [comment]
Nope! Before + I also have a few other things in mind for this PR before splitting it up into ~4
- https://github.com/magma/magma/issues/10295
- https://github.com/magma/magma/issues/10293

**Comment by reginawang3495** [comment]
@andreilee 
Nope! Before + I also have a few other things in mind for this PR before splitting it up into ~4
- this PR into 2
- https://github.com/magma/magma/issues/10295
- https://github.com/magma/magma/issues/10293

**Comment by reginawang3495** [comment]
I've manually tested this on dev and it works -- I'd just merge this in if helm chart works! The other two listed issues can potentially be bootcamp tasks :)

**Comment by sebathomas** [comment]
@reginawang3495 @uri200 @hcgatewood Was this abandoned because there was something wrong or just because there was no time to finish or test it? Currently looking into TODO comments and wondering about the status of the two follow-up tickets #10293 and #10295.

**Pull request closed without merging**
