### PR TITLE
chore(orc8r): Removed thanos acl variable from terraform

### PR DESCRIPTION
**Pull request by christinewang5**
Removed the thanos variable bc it was causing an issue when deploying to dev and thanos itself is turned off 

image

### CODE REVIEW

**Review by arunuke — COMMENTED** [review]
The larger question is - do we want to completely remove all Thanos variables (as this fix currently shows) or remove just the acl variable from the thanos terraform file (which, according to the error message, is automatically set based on the applied configuration)

Copying @hcgatewood in case he has a preference on one over the other. the removal of 'acl' appears to be the simpler fix, but removing thanos because it's not used could be our long term direction as well.

**Review by hcgatewood — COMMENTED** [review]
I could be wrong but I don't think this will fix the problem (?). Feel free to correct me if you validated this

Instead of removing the variables, basically it seems like there's a line in our thanos tf file(s) that is deprecated, and we need to remove that specific line. cc @arunuke per his comment in the Slack 

P.S. next week I'll go through and make sure no one is using this, then I'll remove the whole thing 🙂

**Comment by hcgatewood** [comment]
Right just seeing @arunuke's comment. Yeah we just want to remove the ACL line for now 👍👍

**Comment by arunuke** [comment]
This is some vulcan level mind-meld @hcgatewood :-).

I propose we make a change just to the 'acl' variable in the tf file (ie, completely remove it since it is automatically set) for this PR.

**Comment by christinewang5** [comment]
Hey just deleted only the acl variable. Kind of understood the Slack comment but this makes sense, thank you 😊

**Review by arunuke — APPROVED** [review]
LGTM !!

**Review by hcgatewood — APPROVED** [review]

**Review by ShubhamTatvamasi — APPROVED** [review]

**Pull request merged**
