### PR TITLE
chore(mme): Fix include of cpp file

### LINKED ISSUE #11710: Fix for cpp incudes
Source files are included in other files, replacing them by header files.

### PR DESCRIPTION
**Pull request by electronjoe**
Works towards #9714.

It's not clear to me that this unit test actually compiles (I'm
struggling to do so even with fixes).

Signed-off-by: Scott Moeller <electronjoe@gmail.com>

### CODE REVIEW

**Review by themarwhal — APPROVED** [review]

**Comment by themarwhal** [comment]
Looks like there's another one:
https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/magma/magma%24+%23include.*c%22&patternType=regexp
Screen Shot 2022-02-18 at 9 21 20 AM

**Comment by ulaskozat** [comment]
cc @panyogesh @Kaleem-Wavelabs @GANESH-WAVELABS

**Review by ulaskozat — APPROVED** [review]
LGTM

**Comment by ulaskozat** [comment]
Looks like this was done in the name of including some static definitions in the cpp files. @panyogesh @GANESH-WAVELABS  can you steer the fixed for this?

**Review by ulaskozat — CHANGES_REQUESTED** [review]
Looks like static function `paa_to_address_info` is grabbed from there. Needs to move its declaration to a common header file and remove static.

**Comment by panyogesh** [comment]
> Looks like static function `paa_to_address_info` is grabbed from there. Needs to move its declaration to a common header file and remove static.

Sure. Will address the issue.

**Comment by ulaskozat** [comment]
> > Looks like static function `paa_to_address_info` is grabbed from there. Needs to move its declaration to a common header file and remove static.
> 
> Sure. Will address the issue.

also see @themarwhal's comment on another case where c file appears in include statement.

**Comment by electronjoe** [comment]
> Looks like there's another one:

I'm fixing this one now too, thanks

**Comment by electronjoe** [comment]
> Sure. Will address the issue.

OK, seems there are two issues here (two files with #include of .c).

I'll close this PR and let @panyogesh Steer a fix. Can you please file a GH issue for these and link it to this closed PR for me to track?

**Pull request closed without merging**
