### PR TITLE
chore(cwg): upgrade operator-framework/operator-sdk from v0.16.0 to v0.19.4

### PR DESCRIPTION
**Pull request by spikey979**
chore(cwg): upgrade operator-framework/operator-sdk from v0.16.0 to v0.19.4

## Summary

PR is for issue: https://github.com/magma/magma/issues/10018

There is an issue in the kubernetes package version, and proposed fix is to upgrade k8s.io/kubernetes to version 1.19.15 or later. This package isn't used in .go file directly, but in other packages (e.g. github.com/operator-framework/operator-sdk). 

This is chain of dependencies for kubernetes package:
**magma/cwf/k8s/cwf_operator ->**
github.com/operator-framework/operator-sdk@v0.16.0 ->
k8s.io/**kubernetes**@v1.16.2

**magma/cwf/k8s/cwf_operator ->**
github.com/operator-framework/operator-sdk@v0.16.0 ->
github.com/operator-framework/operator-registry@v1.5.7 ->
github.com/operator-framework/operator-lifecycle-manager@v0.0.0 -> k8s.io/**kubernetes**@v1.16.0

**magma/cwf/k8s/cwf_operator ->**
github.com/operator-framework/operator-sdk@v0.16.0 ->
github.com/operator-framework/api@v0.0.0 ->
github.com/operator-framework/operator-registry@v1.5.3 ->
github.com/operator-framework/operator-lifecycle-manager@v0.0.0 ->
k8s.io/**kubernetes**@v1.16.0

**magma/cwf/k8s/cwf_operator ->**
github.com/operator-framework/operator-sdk@v0.16.0 ->
github.com/operator-framework/api@v0.0.0 ->
github.com/operator-framework/operator-lifecycle-manager@v0.0.0 ->
k8s.io/**kubernetes**@v1.16.0

**magma/cwf/k8s/cwf_operator ->**
helm.sh/helm/v3@v3.1.2 ->
github.com/deislabs/oras@v0.7.0 ->
github.com/Microsoft/hcsshim@v0.8.6 ->
k8s.io/**kubernetes**@v1.13.0

I upgraded operator-framework/operator-sdk version from v0.16.0 to v0.19.4 and built the code without errors. So there is no more dependencies for kubernetes package in code.

### CODE REVIEW

**Comment by themarwhal** [comment]
Looks like the cwf operator check is failing: https://github.com/magma/magma/runs/4392228887?check_suite_focus=true

**Comment by spikey979** [comment]
It seems that my idea isn’t a good one after all. I will research it and try to find another solution…

**Comment by themarwhal** [comment]
@spikey979 Is this still up to date?

**Comment by themarwhal** [comment]
Removing myself as a reviewer to suppress notifications. @spikey979, please close the PR if it's out of date. Thanks :)

**Pull request closed without merging**
