### PR TITLE
fix(orc8r): Rename lib_errors to lib_merrors

### PR DESCRIPTION
**Pull request by spikey979**
fix(orc8r): Rename lib_errors to lib_merrors

## Summary

 I renamed package orc8r/lib/go/errors to orc8r/lib/go/merrors and removed all the occasions where we perform that alias.

## Test Plan

ran /magma/feg/gateway/docker/ ./build.py -c and /magma/orc8r/cloud/docker/  ./build.py -c

Tihs is PR for: https://github.com/magma/magma/issues/9827

### CODE REVIEW

**Review by hcgatewood — APPROVED** [review]
💯

**Review by themarwhal — APPROVED** [review]

**Review by mstre123 — APPROVED** [review]
lgtm once the ci checks are handled

**Review by themarwhal — APPROVED** [review]

**Comment by lucasgonze** [comment]
@spikey979 Before we can mark this ready2merge, all required tests have to pass. (Unless you can show the failure isn't related to your changes, I believe).

**Comment by spikey979** [comment]
There were a lot of changes in this PR that I didn't make. I presume someone else's commits merged with mine. I couldn't fix it so I closed PR and will create a new one.

**Pull request closed without merging**
