### PR TITLE
[nms] Switch NMS docker to use Postgres, deprecate usage of MariaDB

### LINKED ISSUE #2896: NMS is not able to work with Postgres 9.4+
### Environment

- Magma 1.2
- NMS
- @fbcnms/sequelize-models/index.js

### Describe the Issue

In case NMS deployed with Postgres DB each attempt to login leads to failure.
In scope of auth/express.js following SQL request is generated :
`**SELECT "id", "name", "tabs", "csvCharset", "customDomains", "networkIDs", "ssoSelectedType", "ssoCert", "ssoEntrypoint", "ssoIssuer", "ssoOidcClientID", "ssoOidcClientSecret", "ssoOidcConfigurationURL", "createdAt", "updatedAt" FROM "Organizations" AS "Organization" WHERE (SELECT 1 FROM json_each("customDomains")WHERE json_each.value = 'master.nms.yourdomain.com') IS NOT NULL LIMIT 1;**`
Following error is raised:
`[auth/express.js] error: Error getting organization operator does not exist: json = unknown`

Bug is in the function which responsible for jsonArrayContains check
```
export function jsonArrayContains(column: string, value: string) {
  if (
    sequelize.getDialect() === 'mysql' ||
    sequelize.getDialect() === 'mariadb'
  ) {
    return Sequelize.fn('JSON_CONTAINS', Sequelize.col(column), `"${value}"`);
  } else {
    // sqlite
    const escapedColumn = sequelize
      .getQueryInterface()
      .quoteIdentifier(column, true);
    const innerQuery = Sequelize.literal(
      **`(SELECT 1 FROM json_each(${escapedColumn})` +
        `WHERE json_each.value = ${sequelize.escape(value)})`,**
    );
    return Sequelize.where(innerQuery, 'IS', Sequelize.literal('NOT NULL'));
  }
}
```

**Expected behavior**
NMS works with Postgres as good as with MySQL

For the Postgres following query will work:
**SELECT “id”, “name”, “tabs”, “csvCharset”, “customDomains”, “networkIDs”, “ssoSelectedType”, “ssoCert”, “ssoEntrypoint”, “ssoIssuer”, “ssoOidcClientID”, “ssoOidcClientSecret”, “ssoOidcConfigurationURL”, “createdAt”, “updatedAt” FROM “Organizations” AS “Organization” WHERE “customDomains”::jsonb ? ‘master.nms.yourdomain.com’;**

### LINKED ISSUE #5237: [NMS] Change docker NMS to use Postgres instead of MariaDB

### PR DESCRIPTION
**Pull request by andreilee**
Signed-off-by: Andrei Lee <andreilee@fb.com>

## Summary

This pull request changes the development docker setup of Magma NMS to use Postgres instead of MariaDB. This has required changes to fbc-js-core `express-middleware` and `sequelize-models`, for which the requirements have been updated to `^0.1.1`, for both those dependencies. MariaDB will no longer run, and Postgres will now run by default.

Development usage of Postgres ensures that the development setup of NMS will mirror the future production setups of NMS with perhaps AWS and terraform.

## Test Plan

Sanity checked by visiting NMS organizations page and a network on local developer NMS.

## Additional Information

- [ ] This change is backwards-breaking
-->

### CODE REVIEW

**Comment by Scott8440** [comment]
Should you update the helm chart values for nms? The current default dialect is mysql

**Comment by ShubhamTatvamasi** [comment]
We might also needing some alternate for `db_setup.sql.tpl` for bare metal deployment.
https://github.com/magma/magma/blob/v1.4/orc8r/cloud/deploy/bare-metal/db_setup.sql.tpl

**Comment by mattymo** [comment]
@andreilee Did you check that this works? https://github.com/magma/magma/issues/2896 has been open since September

**Comment by andreilee** [comment]
This is just for the development setup using docker. Helm chart values to be changed in a later PR

**Review by Scott8440 — APPROVED** [review]

**Pull request merged**
