### PR TITLE
fix(nms): remove hard-coded secret

### PR DESCRIPTION
**Pull request by lucasgonze**
Fixes https://github.com/magma/magma/security/code-scanning/120

## Summary

See:
* https://github.com/magma/magma/security/code-scanning/120
* https://github.com/magma/security/issues/148

## Test Plan

I verify CI tests passed. Unless I have created a syntax error, there shouldn't be any other point of breakage.

## Additional Information

- [ ] This change is backwards-breaking

There may be developers using this string for debugging.

## Security Considerations

Improves security by removing an attack vector.

### CODE REVIEW

**Review by maxhbr — APPROVED** [review]
Looks reasonable

**Comment by lucasgonze** [comment]
Todo: consider throwing a fatal error if the secret is not set.

**Comment by lucasgonze** [comment]
After taking this pretty far, I have realized that it is wrong from an architectural point of view. What should happen is that the app should refuse to start when process.env.SESSION_TOKEN is blank.

**Comment by lucasgonze** [comment]
Curiouser and curiouser: there is no code in Magma to set the SESSION_TOKEN variable.

```
(base) M1-Air-2086:magma lucasgonze$ find . -type f -exec grep SESSION_TOKEN "{}" \; -print 2>/dev/null
export AWS_SESSION_TOKEN="<your-session-token>"
The `sessionToken` property and `AWS_SESSION_TOKEN` environment variable are optional for signing
./docs/docusaurus/node_modules/aws4/README.md
    sessionToken: env.AWS_SESSION_TOKEN,
./docs/docusaurus/node_modules/aws4/aws4.js
export AWS_SESSION_TOKEN="<your-session-token>"
The `sessionToken` property and `AWS_SESSION_TOKEN` environment variable are optional for signing
./nms/node_modules/aws4/README.md
    sessionToken: env.AWS_SESSION_TOKEN,
./nms/node_modules/aws4/aws4.js
    sessionToken: env.AWS_SESSION_TOKEN,
./nms/node_modules/yarn/lib/cli.js
    sessionToken: process.env.SESSION_TOKEN
./nms/server/app.ts
```

**Comment by lucasgonze** [comment]
Documentation:

https://magma.github.io/magma/docs/1.5.X/nms/architecture_overview

image

**Comment by lucasgonze** [comment]
Further investigation is here: https://github.com/magma/security/issues/161

**Pull request closed without merging**
