### PR TITLE
chore(sessiond): Update all include paths to be fully specified

### PR DESCRIPTION
**Pull request by electronjoe**
## Summary

To be clear, this PR strictly maps include paths and has no intended functional impact.

This PR is the first of many intended to migrate our C/C++ codebase to full repo-relative paths. See #9861.

## Process

This PR was generated by useing [this go binary](https://gist.github.com/electronjoe/dce83fcb6b9171dd3668f76a961b9cd1) executed as follows:

```bash
go run /tmp/pathify.go -root /workspaces/magma/ -target /workspaces/magma/lte/gateway/c/core/oai/tasks/ -dry_run=false -target_filter ".h,.c,.cpp"
```

Additionally some CMake project changes were required. Namely I added `$MAGMA_ROOT` to the include path for the `session_manager/CMakeLists.txt` top level file

## Test Plan

All session_manager builds and tests pass - compilation success is an overwhelming indicator of correct include modifications.

Signed-off-by: Scott Moeller <electronjoe@gmail.com>

### CODE REVIEW

**Review by themarwhal — APPROVED** [review]
lgtm!

**Review by themarwhal — APPROVED** [review]

**Comment by uri200** [comment]
Will this break the debugger on clion for sessiond?

**Comment by uri200** [comment]
I pulled the PR and test are not able to build anymore on clion

Autocompletion on test is gone too. That seems to be exclusively an issue on the `test` folder. Files at root level seems to handle the change just fine

image


Relative paths work though

image


error given 

```
====================[ Build | local_enforcer_test | Debug-Remote-host_default ]====
/usr/bin/cmake --build /tmp/tmp.gwrtnbl0lJ/cmake-build-debug-remote-host_default --target local_enforcer_test -- -j 12
[ 97%] Built target SESSION_MANAGER
[ 98%] Built target SESSIOND_TEST_LIB
[ 98%] Linking CXX executable local_enforcer_test
/usr/bin/ld: CMakeFiles/local_enforcer_test.dir/test_local_enforcer.cpp.o: in function `void __gnu_cxx::new_allocator<magma::lte::MeteringReporter>::construct<magma::lte::MeteringReporter>(magma::lte::MeteringReporter*)':
/usr/include/c++/9/ext/new_allocator.h:147: undefined reference to `magma::lte::MeteringReporter::MeteringReporter()'
/usr/bin/ld: ../libSESSION_MANAGER.a(SessionStore.cpp.o): in function `magma::lte::SessionStore::update_sessions(std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, magma::SessionStateUpdateCriteria, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, magma::SessionStateUpdateCriteria> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, magma::SessionStateUpdateCriteria, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, magma::SessionStateUpdateCriteria> > > > > > const&)':
/tmp/tmp.gwrtnbl0lJ/SessionStore.cpp:191: undefined reference to `magma::lte::MeteringReporter::report_usage(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, magma::SessionStateUpdateCriteria&)'
/usr/bin/ld: ../libSESSION_MANAGER.a(SessionStore.cpp.o): in function `magma::lte::SessionStore::initialize_metering_counter()':
/tmp/tmp.gwrtnbl0lJ/SessionStore.cpp:213: undefined reference to `magma::lte::MeteringReporter::initialize_usage(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, magma::TotalCreditUsage)'
collect2: error: ld returned 1 exit status
make[3]: *** [test/CMakeFiles/local_enforcer_test.dir/build.make:88: test/local_enforcer_test] Error 1
make[2]: *** [CMakeFiles/Makefile2:468: test/CMakeFiles/local_enforcer_test.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:475: test/CMakeFiles/local_enforcer_test.dir/rule] Error 2
make: *** [Makefile:285: local_enforcer_test] Error 2


```

**Comment by electronjoe** [comment]
> Will this break the debugger on clion for sessiond?

I have no way of testing this - but I should very much doubt it.  At most I expect Clion to require a new include path (MAGMA_ROOT) be specified (and more likely nothing has to be done to support).

**Comment by uri200** [comment]
ok it looks like it does also break root directory. 

image

**Comment by themarwhal** [comment]
> ok it looks like it does also break root directory.
> 
> image

hmmm that's unfortunate. Is it because we choose the SessionD CMake to be the project root? (not sure if we do that but maybe?)

**Comment by electronjoe** [comment]
Thanks for the heads up @uri200.

I'm somewhat impatient to get this cleanup PR merged as it is blocking / involved in the `orc8r/...` pathify cleanup - and I have a lot of these PRs to land to migrate or code base to absolute includes.

To clarify the situation:

1. The Clion workflow builds and runs tests under this PR (I verified manually in clean env), but autocomplete / jump to code is broken (and given the convoluted CLion actions in VM dev, it is unclear how to fix this)
1. I re-tested @themarwhal [VSCode + Bazel work](https://github.com/magma/magma/blob/master/experimental/bazel-base/VSCodeBazel.md) for `sessiond` and it supports {gdb use, autocomplete, jump to code except proto}
1. I put a meeting on our calendars to demo that workflow for you @uri200 (tomorrow)

**Pull request closed without merging**
