### PR TITLE
docs(agw): Add KB AGW health check

### PR DESCRIPTION
**Pull request by wallyrb**
Signed-off-by: Wally Rodriguez B <wallyrb@fb.com>

## Summary

- Add KB to perform AGW healt check and move to Troubleshooting section

## Test Plan

tested locally

image

### CODE REVIEW

**Comment by ekowtaylor** [comment]
@wallyrb is a review all that is required?

**Comment by wallyrb** [comment]
> @wallyrb is a review all that is required?

Hey @ekowtaylor thanks for flagging. Yes. I have resolved some conflicts since the PR is  old and update the content. Is ready to be reviewed

**Review by electronjoe — APPROVED** [review]

**Comment by electronjoe** [comment]
Thanks for the documentation @wallyrb !

**Comment by ekowtaylor** [comment]
@Scott8440  can you please get this merged?

**Pull request merged**
