### PR TITLE
fix(ci): Join the qfi test to resolve test interdependency issue

### PR DESCRIPTION
**Pull request by crasu**
## Summary

The test_qfi_set_tunnel_flows and test_qfi_delete_tunnel_flows were interdependent before. This Pull request tries to resolve this issue. Added the qfi to the delete call. Before the test_qfi_delete_tunnel_flows did not fail, even when now tunnel flows were deleted.

## Test Plan

Ran the sudo test locally.

LTE Integ test: https://github.com/crasu/magma/actions/workflows/lte-integ-test.yml

## Additional Information
- Added the qfi to the delete call in order to make it delete the correct flow.
- Made sure flows are really deleted.
- Removed all pkg counters from the test as the test is not generating traffic

### CODE REVIEW

**Comment by crasu** [comment]
@prabinakpattnaik Could you have a look if this makes sense to you funtionallity wise. Thank you!

**Review by sebathomas — APPROVED** [review]
I think this improves the test. :+1:

Might it even make sense to have a third snapshot, and attempt to delete another qfi first to assert that this doesn't delete the rule?

**Comment by nstng** [comment]
Hi @prabinakpattnaik are you interested in reviewing this yourself? If not, let me know, than I will have a look. :)

**Comment by crasu** [comment]
> Hi @prabinakpattnaik are you interested in reviewing this yourself? If not, let me know, than I will have a look. :)
@nstng Could you have a look?

**Review by nstng — APPROVED** [review]
LGTM

**Comment by crasu** [comment]
@VinashakAnkitAman This needs agw integ approval as well even if it is not an agw integ test ....

**Pull request merged**
