### PR TITLE
fix(orc8r): Formatted terraform files

### PR DESCRIPTION
**Pull request by ShubhamTatvamasi**
Signed-off-by: Shubham Tatvamasi <shubhamtatvamasi@gmail.com>

## Summary

Formatted terraform scripts with the following command:
```bash
terraform fmt
```

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by themarwhal — APPROVED** [review]
Looks great! Is this something that we can create a CI check for to enforce it for future changes?

**Comment by ShubhamTatvamasi** [comment]
> Looks great! Is this something that we can create a CI check for to enforce it for future changes?

Yes, we can create a CI job for this. Let me create an issue for this.

**Comment by ShubhamTatvamasi** [comment]
Created an issue for CI job https://github.com/magma/magma/issues/11996

**Review by hcgatewood — COMMENTED** [review]
I don't know that this adds a lot of value unless we make it a CI required check. That's what we did e.g. with Markdown linting. How do you feel about this order

1. This PR
2. Add optional CI check that runs on all PRs
3. Final PR that fixes any new fmt issues + make CI check required

**Review by hcgatewood — APPROVED** [review]

**Comment by ShubhamTatvamasi** [comment]
> I don't know that this adds a lot of value unless we make it a CI required check. That's what we did e.g. with Markdown linting. How do you feel about this order
> 
> 1. This PR
> 2. Add optional CI check that runs on all PRs
> 3. Final PR that fixes any new fmt issues + make CI check required

Sounds great.

**Pull request merged**
