### PR TITLE
feat(nms): Out-of order import of fileds in subscriber upload

### PR DESCRIPTION
**Pull request by panyogesh**
Fix
  Maps the fileds during subscriber addition in correct order.
  IMSI should be starting field followed by subscriber Name.
  Issue reported #14607.

Test
  Uploaded the file exported and all subscriber entries are reflected
  in NMS as well as AGW.

Signed-off-by: Yogesh Pandey <yogesh@wavelabs.ai>

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by panyogesh** [comment]
Issue-Snapshot-Susbscriber-Import
After-Fix-Subscriber-Snapshot

**Comment by sebathomas** [comment]
I don't think this is consistent with the way subscribers are exported at the moment. I just tried it on v1.8 and the generated csv has the name in the first column and the IMSI in the second column.

```
"Name","IMSI","Auth Key","Auth OPC","Service","Forbidden Network Types","Data Plan","Active APNs"
"test_name","IMSI001010000000002","00112233445566778899aabbccddeeff","63bfa50ee6523365ff14c1f45f88737d","ACTIVE",,"default",
```

Do we know when the column order was changed?

I think if we change the import, we need to change the export as well in order to be consistent.

**Comment by panyogesh** [comment]
> I don't think this is consistent with the way subscribers are exported at the moment. I just tried it on v1.8 and the generated csv has the name in the first column and the IMSI in the second column.
> 
> ```
> "Name","IMSI","Auth Key","Auth OPC","Service","Forbidden Network Types","Data Plan","Active APNs"
> "test_name","IMSI001010000000002","00112233445566778899aabbccddeeff","63bfa50ee6523365ff14c1f45f88737d","ACTIVE",,"default",
> ```
> 
> Do we know when the column order was changed?
> 
> I think if we change the import, we need to change the export as well in order to be consistent.

Let me double check.  Attaching the failure case for import

**Comment by panyogesh** [comment]
Issue Logs
Issue-Snapshot-Susbscriber-Import

**Comment by panyogesh** [comment]
Comments mentioned are correct. I guess 1.5 subscriber snapshot getting generated needs to be re-looked.

**Pull request closed without merging**
