### PR TITLE
chore(agw): Update Vscode c++ preferences

### PR DESCRIPTION
**Pull request by ssanadhya**
Signed-off-by: Shruti Sanadhya <ssanadhya@fb.com>

## Summary

Update include path in VSCode C++ preferences

## Test Plan

None

### CODE REVIEW

**Review by ardzoht — APPROVED** [review]
lgtm

**Comment by themarwhal** [comment]
Hey @ssanadhya! just curious, were you making this change to fix something? (I wasn't exactly sure how this file was used so I was wondering what behavior this changed :) )

**Comment by ardzoht** [comment]
> Hey @ssanadhya! just curious, were you making this change to fix something? (I wasn't exactly sure how this file was used so I was wondering what behavior this changed :) )

@themarwhal We made this update to the directories to fix some header includes getting resolved on VScode (most of them related with MME tasks code)

**Comment by themarwhal** [comment]
> > Hey @ssanadhya! just curious, were you making this change to fix something? (I wasn't exactly sure how this file was used so I was wondering what behavior this changed :) )
> 
> @themarwhal We made this update to the directories to fix some header includes getting resolved on VScode (most of them related with MME tasks code)

sounds good! thanks for updating. I still don't really understand how that file is used or by what extension but whatever works is great :D

**Pull request merged**
