### PR TITLE
[AGW] Ubuntu box using snapshot and ovi conversion

### PR DESCRIPTION
**Pull request by tmdzk**
Signed-off-by: Timothée Dzik <timdzik@fb.com>

[AGW] Ubuntu box using snapshot and ovi conversion

## Summary

[AGW] Ubuntu box using snapshot and ovi conversion

## Test Plan
 cd lte/gateway && vagrant up

### CODE REVIEW

**Comment by themarwhal** [comment]
lte integ test run on this PR rebased onto master: https://app.circleci.com/pipelines/github/magma/magma/26608/workflows/15a0ff4f-a1c4-4d06-890a-fbe240254b29/jobs/284724

**Comment by tmdzk** [comment]
> lte integ test run on this PR rebased onto master: https://app.circleci.com/pipelines/github/magma/magma/26608/workflows/15a0ff4f-a1c4-4d06-890a-fbe240254b29/jobs/284724

Looks good. let's wait and 🙏 
@themarwhal

**Review by themarwhal — APPROVED** [review]
https://app.circleci.com/pipelines/github/magma/magma/26608/workflows/15a0ff4f-a1c4-4d06-890a-fbe240254b29/jobs/284724 

the job failed but the test seemed to pass. So I think we are OK.

**Comment by themarwhal** [comment]
I'll re-run it just in case: https://app.circleci.com/pipelines/github/magma/magma/26608/workflows/7e9227ab-0871-4757-b00a-4ef8aca20d13/jobs/284942

**Comment by themarwhal** [comment]
Screen Shot 2021-06-21 at 1 48 51 PM
ci is green but there is an issue with github somehow.

**Review by karthiksubraveti — APPROVED** [review]

**Pull request merged**
