### PR TITLE
fix(orc8r): lowercase orc8r service names

### PR DESCRIPTION
**Pull request by spikey979**
fix(orc8r): lowercase orc8r service names

## Summary
In this files:
- fbinternal/cloud/go/services/download/download.go
- fbinternal/cloud/go/services/fbinternal/doc.go
- fbinternal/cloud/go/services/testcontroller/defs.go
- fbinternal/cloud/go/services/vpnservice/client_api.go
- feg/cloud/go/services/basic_acct/definitions.go
- feg/cloud/go/services/feg_relay/feg_relay.go
- feg/gateway/services/aaa/base_acct/client_api.go
- feg/gateway/services/radiusd/doc.go
- lte/cloud/go/services/lte/doc.go
- lte/cloud/go/services/policydb/client_api.go
- lte/cloud/go/services/smsd/const.go
- orc8r/cloud/go/services/accessd/client_api.go
- orc8r/cloud/go/services/analytics/doc.go
- orc8r/cloud/go/services/bootstrapper/const.go
- orc8r/cloud/go/services/certifier/client_api.go
- orc8r/cloud/go/services/configurator/doc.go
- orc8r/cloud/go/services/ctraced/doc.go
- orc8r/cloud/go/services/device/doc.go
- orc8r/cloud/go/services/directoryd/client_api.go
- orc8r/cloud/go/services/dispatcher/client_api.go
- orc8r/cloud/go/services/eventd/doc.go
- orc8r/cloud/go/services/metricsd/doc.go
- orc8r/cloud/go/services/state/doc.go
- orc8r/cloud/go/services/streamer/doc.go
- orc8r/gateway/go/directoryd/client_api.go

service names in Go code are standardized to all-lowercase.

This is for issue:
https://github.com/magma/magma/issues/9829

## Test Plan
I ran unit tests in: /magma/orc8r/cloud/docker/  ./build.py -c

### CODE REVIEW

**Review by themarwhal — APPROVED** [review]

**Review by hcgatewood — APPROVED** [review]
Thanks for the fix! I'd say wait till tomorrow, rebase onto latest master, then re-push to see if we can get the flaky checks to pass

**Comment by themarwhal** [comment]
Hey @spikey979 it looks like the isync check is failing. https://magma.github.io/magma/docs/next/contributing/contribute_ci_checks for docs on resolving required checks.

**Comment by themarwhal** [comment]
Removing the `ready2merge` label until the insync check / merge conflict is resolved.

**Comment by spikey979** [comment]
Due to problems with CI tests, I created a new PR: https://github.com/magma/magma/pull/11896

**Pull request closed without merging**
