### PR TITLE
chore: bazel is upgraded to version 5

### LINKED ISSUE #8457: techdebt: upgrade protobuf and migrate C++ protobuf library usage of `status.error_message()` to `status.message()`
The protobuf team has deprecated the `error_messasge` method sometime between the latest release ( https://github.com/protocolbuffers/protobuf/releases/tag/v3.17.3) and release 3.15.0 (https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0)

Our dev VM uses protobuf version 3.6.1 (From Jul 31, 2018)

We currently have 55 instances of C++ code that uses this method: https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/magma/magma%24+.error_message%28%29&patternType=literal

We should upgrade protobuf and migrate to the new method as we're unable to upgrade a few other dependencies that depend on protobuf.

This can be easily done once/if we migrate to bazel.

### PR DESCRIPTION
**Pull request by nstng**
Signed-off-by: Nils Semmelrock <nils.semmelrock@tngtech.com>

## Summary

In this change bazel is upgraded to the current 5 version. This includes
* upgrading rules_proto_grpc from 3.1.1 to 4.1.1 (see https://github.com/bazelbuild/bazel/issues 13811)
  * rules_proto_grpc ships with protobuf 3.19.1 (former 3.15.3) - protobuf 3.19.1 has deprecated `status.error_message()` (see also #8457).
  * This was relevant in one place - in a similar situation in `orc8r/gateway/c/common/config/MConfigLoader.cpp` `status.ToString()` is used. This is changed here as well.
  * Note: in the make build protobuf 3.6.1 is used. It is clear that it is not a good pattern to use different protobuf versions for make and Bazel builds, but 3.6.1 is just too old for Bazel -> the version used with make should be upgraded.
* Using new mechanics for java configuration.

Note: this change also fixes the broken/unstable bazel coverage job, e.g. https://github.com/magma/magma/runs/6793542418?check_suite_focus=true (see also #12926). We switched recently to bazel remote caches and there was a bug with bazel coverage in combination with these caches in bazel 4 that was fixed in bazel 5.

## Test Plan

CI

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Review by jheidbrink — APPROVED** [review]

**Review by vktng — APPROVED** [review]
LGTM.

**Review by LKreutzer — COMMENTED** [review]
Interesting to see that the [build all](https://github.com/magma/magma/runs/6795382618?check_suite_focus=true) with v5 takes >30min and there are few (~30%) remote cache hits `1838 remote cache hit, 1797 internal, 3642 processwrapper-sandbox` but it might be that the bazel version somehow affects some of the hashes?

**Comment by LKreutzer** [comment]
FYI: bazel 5 profiles contain additional information e.g. about the CPU and RAM: 

Screenshot from 2022-06-10 15-22-23

**Comment by nstng** [comment]
> Interesting to see that the [build all](https://github.com/magma/magma/runs/6795382618?check_suite_focus=true) with v5 takes >30min and there are few (~30%) remote cache hits `1838 remote cache hit, 1797 internal, 3642 processwrapper-sandbox` but it might be that the bazel version somehow affects some of the hashes?

grpc and protobuf (and dependencies) where upgraded here - I am actually surprised that we have 30% cache hits.

**Review by LKreutzer — APPROVED** [review]
:partying_face: :tada: :seedling:

**Review by themarwhal — APPROVED** [review]

**Pull request merged**
