### PR TITLE
feat(pipelined): Enforcement functionality for 5G changes back.

### PR DESCRIPTION
**Pull request by prabinakpattnaik**
## Summary

Enforcement functionality for 5G changes back.

## Test Plan

Verified the functionality with Stub and all UT tests of pipelined verified.
These changes are part of #2783 and along with failed UT TCs fixed:
test_rule_deactivation - test_enforcement_stats.EnforcementStatsTest
test_rule_reactivation - test_enforcement_stats.EnforcementStatsTest

## Additional Information

Signed-off-by: prabina pattnaik prabinak@wavelabs.ai

### CODE REVIEW

**Review by koolzz — APPROVED** [review]
No changes beside the unit test fixes right?

**Comment by prabinakpattnaik** [comment]
> No changes beside the unit test fixes right?

Yes. It's only UT fixes extra.

**Comment by koolzz** [comment]
looks like some tests are failing, rerunning

**Comment by prabinakpattnaik** [comment]
> looks like some tests are failing, rerunning

Yes, getting below error for all checks:

Resolving liblfds.org (liblfds.org)... 84.200.110.123
Connecting to liblfds.org (liblfds.org)|84.200.110.123|:443... connected.
ERROR: no certificate subject alternative name matches
	requested host name 'liblfds.org'.
To connect to liblfds.org insecurely, use `--no-check-certificate'.
The command '/bin/sh -c wget --progress=dot:giga https://liblfds.org/downloads/liblfds%20release%207.1.0%20source.tar.bz2  &&     tar -xf liblfds\ release\ 7.1.0\ source.tar.bz2  &&     cd liblfds/liblfds7.1.0/liblfds710/build/gcc_gnumake/ &&     make -j"$(nproc)" &&     make ar_install &&     cd / &&     rm -rf liblfds' returned a non-zero code: 5

Error: Process completed with exit code 5.

**Pull request merged**
