### PR TITLE
Revert "feat(agw): IPv6 data path support (#11926)"

### PR DESCRIPTION
**Pull request by nstng**
This reverts commit 2eae88c48ff0118601e2854027c91e8a6149c1c4.

## Summary

looks like #11926 breaks the master build-all workflow - see https://github.com/magma/magma/runs/6704655581?check_suite_focus=true

Should #11926 be reverted for now?

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by sebathomas** [comment]
Looks like the job was green in the PR of #11926. Is it because it wasn't rebased?

**Comment by nstng** [comment]
> Looks like the job was green in the PR of #11926. Is it because it wasn't rebased?

In `build_all.yml` the job `agw-build` is guared by `github.repository_owner == 'magma'`. It is only executed on master.

**Review by ssanadhya — APPROVED** [review]
Let's fix CI before merging this

**Comment by ssanadhya** [comment]
@pruthvihebbani , could you please look into this failure https://github.com/magma/magma/runs/6704655581?check_suite_focus=true from PR #11926 ? Specifically:

```
==> magma: Clearing any previously set network interfaces...
The IP address configured for the host-only network is not within the
allowed ranges. Please update the address used to be within the allowed
ranges and run the command again.
  Address: 3001::10
  Ranges: 192.168.0.0/16
Valid ranges can be modified in the /etc/vbox/networks.conf file. For
more information including valid format see:
 [ https://www.virtualbox.org/manual/ch06.html#network_hoston](https://www.virtualbox.org/manual/ch06.html#network_hostonly)
```

Did `vagrant destroy magma` and `vagrant up magma` work in your local setup? Did you have to modify `/etc/vbox/networks.conf` on your host machine before creating the new VM?

**Comment by pruthvihebbani** [comment]
Yes I have destroyed multiple times without making any other changes. It has always worked.

**Comment by ssanadhya** [comment]
> Yes I have destroyed multiple times in my local setup without making any other changes. It has always worked.

@sebathomas , can you help debug this build failure? @pruthvihebbani needs to add Ipv6 network interfaces to `magma_dev` VM as part of #11926, by modifying the Vagrantfile. This is working in her local setup but not in CI.

**Comment by nstng** [comment]
@pruthvihebbani This can be reproduced locally with a newer virtualbox version. For me it failed with 6.1.34 and did not fail with 6.1.26. See https://stackoverflow.com/questions/70704093/the-ip-address-configured-for-the-host-only-network-is-not-within-the-allowed-ra. In the workflow files I checked this is setup for ipv4 in a step "Open up network interfaces for VM". I assume this needs be adapted for your ipv6 ip. Also iirc this is part of the gettin started documentation and should be adapted there too.

**Comment by pruthvihebbani** [comment]
I upgraded vbox to version 6.1.34. I am still not able to reproduce the error. On my local Ubuntu 18.04 host I am able to successfully bringup magma_dev vm after destroying and also able to execute ipv6 data test. Does this mean this error is specific to macOS?
magma vm after vbox upgrade
image
image
s

**Comment by sebathomas** [comment]
That's strange. Maybe you already have an entry in `/etc/vbox/networks.conf` in your local system?

**Comment by nstng** [comment]
> Does this mean this error is specific to macOS?
I was able to reproduce it on Ubuntu 20.04 (and @jheidbrink on nixos).

**Comment by pruthvihebbani** [comment]
> 

In my local system /etc/vbox/ folder is empty. I dont have networks.conf this file at all.

**Comment by pruthvihebbani** [comment]
> > Does this mean this error is specific to macOS?
> 
> I was able to reproduce it on Ubuntu 20.04 (and @jheidbrink on nixos).

Can you share the contents of /etc/vbox/networks.conf file? I will create it in my local system and check if I can recreate the  issue

**Comment by nstng** [comment]
just for the record: discussion continued offline

**Pull request merged**
