### PR TITLE
chore(mme): unused test mobility client is removed

### LINKED ISSUE #11785: Explore failing //lte/gateway/c/core/oai/test/mobility_client:mobility_client_test
Aside from not using Google Test (conversion is GH Issue #11660), this unit test appears to be failing in Bazel test with output:

```
1 exec ${PAGER:-/usr/bin/less} "$0" || exit 1                                      
   2 Executing tests from //lte/gateway/c/core/oai/test/mobility_client:mobility_client_test
   3 -----------------------------------------------------------------------------    
   4 Allocating IP address...                                                         
   5 GetIPv4AddressForSubscriber fails with code 14, msg: failed to connect to all addresses
   6 get_ipv4_address_for_subscriber error 14 for sid 0002                            
   7 [libprotobuf FATAL external/protobuf/src/google/protobuf/repeated_field.h:1733] CHECK failed: (index) < (current_size_):·
   8 terminate called after throwing an instance of 'google::protobuf::FatalException'
   9   what():  CHECK failed: (index) < (current_size_):·    
```

It is not clear to me that this unit test is executing in our present `make test_oai` regime?

## Reproduction

- If you have access to GitHub Codespaces
- Go over to my [Bazel prototype branch](https://github.com/electronjoe/magma/tree/pr-giant-bazel-mme-rebase) (~4 PRs on master today)
- Click on the Green colored `Code` drop down button
- Select the `Codespaces` toggle
- Select `New Codespace` and when asked select 16 core (why not!)
- This will spin up a GitHub codespace that contains my branch
- Once the codespace is up (vs code in browswer) in the terminal window type `bazel test //lte/gateway/c/core/oai/test/mobility_client:mobility_client_test --test_output=errors` and hit enter. This triggers a bazel build of all necessary components to run the mobility_client:mobility_client_test, then runs the test

### LINKED ISSUE #11834: mme: Fix up mobility_client_test and add it back into the unit test suite
## Summary
Test in question: [test_mobility_client.cpp](https://github.com/magma/magma/blob/master/lte/gateway/c/core/oai/test/mobility_client/test_mobility_client.cpp)

This test does not get run at all with our current CMake configuration. It's missing a `add_test` command in the CMake file.

https://github.com/magma/magma/blob/35a0417f4a4436e59b486d060bf0b8f88ab4674e/lte/gateway/c/core/oai/test/mobility_client/CMakeLists.txt#L10-L19
## Actions needed
We should either re-enable this test quickly, or mark it as dead in a way that's clear for future developers.  (or remove it https://github.com/magma/magma/pull/11837)

## Instructions on running the test with Bazel (likely quicker than iterating with CMake)
Reach out to @electronjoe or @themarwhal or #bazel on Slack for help :D
(copied from https://github.com/magma/magma/issues/11785)
- If you have access to GitHub Codespaces
- Go over to my [Bazel prototype branch](https://github.com/electronjoe/magma/tree/pr-giant-bazel-mme-rebase) (~4 PRs on master today)
- Click on the Green colored `Code` drop down button
- Select the `Codespaces` toggle
- Select `New Codespace` and when asked select 16 core (why not!)
- This will spin up a GitHub codespace that contains my branch
- Once the codespace is up (vs code in browswer) in the terminal window type `bazel test //lte/gateway/c/core/oai/test/mobility_client:mobility_client_test --test_output=errors` and hit enter. This triggers a bazel build of all necessary components to run the mobility_client:mobility_client_test, then runs the test

### PR DESCRIPTION
**Pull request by LKreutzer**
Signed-off-by: Lars Kreutzer <lars.kreutzer@tngtech.com>

## Summary

- Unused test mobility client is removed
  - `test_mobility_client.cpp` has been commented out in `CMakeLists.txt` for >3 years
  - Note: If commented in still not working due to missing `rpc_client_test`

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by themarwhal** [comment]
Related: https://github.com/magma/magma/issues/11834

**Review by Neudrino — APPROVED** [review]
:broom:

**Review by themarwhal — APPROVED** [review]

**Comment by ulaskozat** [comment]
@ardzoht what do you say?

**Comment by ardzoht** [comment]
These can be safely removed, I think these were used in conjunction with magma services running (as the tests themselves expect a gRPC response), to make these work we would need to mock the gRPC service stub which require additional changes to the C++ protobuf generation.

Also important to note that these are not being counted for our testing coverage so there will not be a change on there at all.

**Review by ardzoht — APPROVED** [review]
lgtm

**Review by lionelgo — APPROVED** [review]

**Pull request merged**
