### PR TITLE
fix(agw): Modified code to fix the issue 14244

### LINKED ISSUE #14244: De/Serialization errors during running integ tests
### Describe the Issue

After merging [13728](https://github.com/magma/magma/pull/13728) we are getting de/serialization error messages while running integ tests. The messages do not cause the test to fail but do clutter the tests output.

### Your Environment

- Happens on current CI or dev vm
- Example from CI: https://github.com/magma/magma/actions/runs/3264233654/jobs/5364550125#step:10:7324

#### Screenshots

` [libprotobuf ERROR google/protobuf/wire_format_lite.cc:618] String field 'io.prometheus.client.LabelPair.value' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.`

### PR DESCRIPTION
**Pull request by rsarwad**
## Summary
Closes https://github.com/magma/magma/pull/14244 

Modified code to read enb_name in character array format as expected by API, set_guage(). Since enb_name, read from proto files was in string format was resulting into serialization and de-serialization errors.
The PR provides fixes for the issue, https://github.com/magma/magma/pull/14244

## Test Plan
Executed s1ap sanity test suite and unit test cases

### CODE REVIEW

**Review by crasu — APPROVED** [review]
Code change looks good. Could you run the lte integ tests with this change from your repo to prove the error message is gone.

**Comment by rsarwad** [comment]
> Code change looks good. Could you run the lte integ tests with this change from your repo to prove the error message is gone.

Yes @crasu Locally verified that the protobuf error messages are not seen. But while I was self reviewing I got to know that similar changes are needed at some other places. Modified the code and again kept for executing "lte integ_tests". Let you know once that is completed

**Comment by rsarwad** [comment]
> > Code change looks good. Could you run the lte integ tests with this change from your repo to prove the error message is gone.
> 
> Yes @crasu Locally verified that the protobuf error messages are not seen. But while I was self reviewing I got to know that similar changes are needed at some other places. Modified the code and again kept for executing "lte integ_tests". Let you know once that is completed

@crasu, "lte integ_tests" completed successfully in local setup

**Review by ajahl — APPROVED** [review]

**Review by ssanadhya — APPROVED** [review]
Lgtm

**Pull request merged**
