### PR TITLE
docs: Cloudstrapper Installation Instructions

### PR DESCRIPTION
**Pull request by jaredmullane**
Signed-off-by: Jared Mullane <jmullane@fb.com>

## Summary

This provides instructions for how to deploy Magma via AWS Cloudstrapper. 

## Test Plan

create_docusaurus_website.sh
Screen Shot 2021-09-28 at 3 17 07 PM

### CODE REVIEW

**Review by hcgatewood — CHANGES_REQUESTED** [review]
Thanks for adding this Jared! I'll let @arunuke review for the cloudstrapper content

My docs input is please move this from "basics" to "deploy > orc8r" section+subsection, as that's a better fit

**Comment by jaredmullane** [comment]
Thanks as always @hcgatewood ! Cloudstrapper contains installs both AGW and the Orc8r with minimum setup/commands so that is why I was thinking of putting it in the "Getting Started" section. Open to discuss more about breaking it up.

**Comment by hcgatewood** [comment]
Ah true. Then deploy > general probably makes the most sense

**Comment by jaredmullane** [comment]
@hcgatewood @arunuke created a new PR for this here with it under "Deploy > General": https://github.com/magma/magma/pull/9389

**Pull request closed without merging**
