### PR TITLE
style: apply formatting script to all Python files except few PipelienD files / XWF

### PR DESCRIPTION
**Pull request by themarwhal**
Signed-off-by: Marie Bremner <marwhal@fb.com>

## This PR should not affect any logic, just formatting

At the request of Nick, I ommitted any files touched in this PR to avoid merge conflicts: https://github.com/magma/magma/pull/5625

## Summary
Second attempt at https://github.com/magma/magma/pull/7400 , messed it up after doing all the validation so I had to revert. 

validating integration test runs on CI
lte: https://app.circleci.com/pipelines/github/magma/magma/28414/workflows/56a1f05e-21a3-4e1e-a40f-31ea3313000b/jobs/315950
cwf: https://app.circleci.com/pipelines/github/magma/magma/28414/workflows/707f019a-fc40-4ad5-ba0a-feb0672130c5/jobs/315947

Screen Shot 2021-07-10 at 6 31 56 PM

## Steps I Ran
Now that I've committed formatted changes for all services, time to format the rest of python files in the directory.

Once all files are formatted initially, we should no longer get noisy PRs with additional formatting changes.

Ran the following (exact commands ran in the precommit script and the github action check)
```bash
for i in `find . -name "*.py" -type f`; do
    echo $i;
    isort $i;
    autopep8 --select W291,W293,E2,E3 -r --in-place  $i;
    add-trailing-comma --py35-plus $i;
done
./precommit -f -d # to validate the script
```

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by mstre123** [comment]
noob question but does the pre commit script or something else have a formatter in it?

**Comment by themarwhal** [comment]
> noob question but does the pre commit script or something else have a formatter in it?

See here on doc for the precommit script we have: https://github.com/magma/magma/tree/master/lte/gateway/docker/python-precommit

We have a script that runs the linter / formatter on any python file.

**Review by tmdzk — APPROVED** [review]

**Review by pshelar — APPROVED** [review]
do we have any documentation about coding style config for python IDEs? It would be nice to add it if not.
change looks good to me.

**Comment by themarwhal** [comment]
> do we have any documentation about coding style config for python IDEs? It would be nice to add it if not.
> change looks good to me.

@pshelar there are some one liners about VScode and INtellij in the coding conventions doc: https://docs.magmacore.org/docs/next/contributing/contribute_conventions#python

Lmk if there are other IDEs we should consider as well.

**Review by ardzoht — APPROVED** [review]

**Review by uri200 — APPROVED** [review]

**Review by 119Vik — APPROVED** [review]

**Pull request merged**
