### PR TITLE
chore(orc8r): Merge combine_swagger and swaggergen executables #5425

### LINKED ISSUE #5425: Merge combine_swagger and swaggergen executables
The `combine_swagger` and `swaggergen` tools are strongly related and share a lot of functionality. Merging these tools as separate sub-commands under a single executable would reduce final container image size, as well as providing improved conceptual cohesion.

### PR DESCRIPTION
**Pull request by nikolakn**
## Summary

The combine_swagger and swaggergen tools are strongly related and share a lot of functionality. Merging these tools as separate sub-commands under a single executable would reduce final container image size, as well as provide improved conceptual cohesion.

## how I tested
in magma/orc8r/cloud
running: make fullgen
that use those command runs without errors

[Edit @nstng] Closes #5425

### CODE REVIEW

**Review by hcgatewood — COMMENTED** [review]
Awesome! Initial skim looks reasonable. Main thing is: can you flesh out the "how I tested" part of the PR description, since these files are CLIs and we don't have great automated test coverage for them yet

**Comment by nikolakn** [comment]
> Awesome! Initial skim looks reasonable. Main thing is: can you flesh out the "how I tested" part of the PR description, since these files are CLIs and we don't have great automated test coverage for them yet

Thank you,  [magma/orc8r/cloud]$  make fullgen and also  [magma/orc8r/cloud/docker]$ ./build.py --all 
I also don't have any other way to test  it except running those commands that use swaggergen

**Review by hcgatewood — APPROVED** [review]
Seems good to me

**Comment by hcgatewood** [comment]
@nikolakn I went ahead and enabled auto-merge for you. Looks like there's a merge conflict

**Comment by nikolakn** [comment]
> @nikolakn I went ahead and enabled auto-merge for you. Looks like there's a merge conflict

 @hcgatewood  Thank you, merge conflict is fixed.

**Review by mstre123 — APPROVED** [review]
lgtm

**Pull request merged**
