### PR TITLE
[Pipelined]Fix IPv6 Restart Flow Recovery

### PR DESCRIPTION
**Pull request by koolzz**
Signed-off-by: Nick Yurchenko <koolzz@fb.com>

## Summary

Discovered that we don't properly recover ipv6 flows. This pr fixes that

## Additional Information

- [ ] This change is backwards-breaking

### CODE REVIEW

**Comment by pshelar** [comment]
I guess there is no test to validate IPv6 recovery, can we add it?

**Comment by koolzz** [comment]
> I guess there is no test to validate IPv6 recovery, can we add it?

Added

**Comment by koolzz** [comment]
> I guess there is no test to validate IPv6 recovery, can we add it?

added

**Review by pshelar — APPROVED** [review]
Thanks!

**Pull request merged**
