### PR TITLE
test(agw): New testcase to test multiple partial TAI lists and automate adding of TAIs in mme.conf.template

### PR DESCRIPTION
**Pull request by pruthvihebbani**
test(agw): New testcase to test multiple partial TAI lists and automate adding of TAIs in mme.conf.template

## Summary

This PR has the following:
1. Addeda new testcase to test TAU with TACs belonging to different partial TAI lists
2. Automate adding of multiple TAIs into mme.conf.template before executing sanity suite
3. Added TAU TCs in PR: #8937  to sanity suite

## Test Plan

- Verified s1aptester sanity suite
- Verified test_tau_mixed_partial_lists.py TC is working fine on multiple runs

### CODE REVIEW

**Review by ulaskozat — APPROVED** [review]
LGTM

**Comment by ulaskozat** [comment]
@pruthvihebbani you need to rebase and submit as lint-clang-format is now a required test. you can check the failed file and do in the dev vm: `clang-format --style=file -i path/to/file1 path/to/file2`

**Comment by pruthvihebbani** [comment]
@ulaskozat I don't see any error related to clang formatting. I think its already addressed in this PR: https://github.com/magma/magma/pull/9183

**Comment by ulaskozat** [comment]
> @ulaskozat I don't see any error related to clang formatting. I think its already addressed in this PR: #9183

sounds good, merged the PR.

**Pull request merged**
