### PR TITLE
refactor(orc8r): Directoryd service security changes

### PR DESCRIPTION
**Pull request by tej-wavelabs**
## Summary
This PR deals with the segregation of `directoryd` internal gRPC servicers implementation.

These changes are part of the ongoing work which details the distinction between Orc8r-internal gRPC endpoints vs. external, gateway-oriented gRPC endpoints.

- `directoryd.proto` previously in `orc8r/lib/go/protos` splitted
- `directoryd.proto` for controller service `DirectoryLookup` moved to service scope in `orc8r/cloud/go/services/directoryd/protos`
- `directoryd.proto` for gateway service `GatewayDirectoryService` stays in global scope at `orc8r/lib/go/protos`
- Servicers and helper files moved to `orc8r/cloud/go/services/directoryd/servicers/protected`
- Imports and references updated

This PR was done as part of requirement by @hcgatewood [RemoveGatewayAccess toOrc8r-InternalEndpoints](https://drive.google.com/file/d/1NO6Qd6rU80xPh0Sb0mKWlSfDt0JbeVIT/view)

## Test Plan

All unit tests passed
No UTs added or removed

### CODE REVIEW

**Review by uri200 — CHANGES_REQUESTED** [review]
we need evidence this is really required

**Comment by hcgatewood** [comment]
> we need evidence this is really required

Hey @uri200! Thanks for reviewing. In this case, this PR is part of a larger effort to improve Orc8r security -- DM me offline for more info. Specifically for this PR, this is one of the areas where we're clarifying which gRPC servicers are Orc8r-internal vs. Orc8r<>gateway, as a prereq for the next step

Context if interested: https://fb.quip.com/Bb6cA6G9rRIx

**Review by hcgatewood — CHANGES_REQUESTED** [review]
Lgtm, just one nit before merging: instead of using "lib_protos", let's just have that one be "protos", and when necessary, we can alias the directoryd protos as "directoryd_protos"

Oh also looks like need to rebase

Content with everything else 👍

**Comment by uri200** [comment]
This is impacting many services so should have been brought to a bigger audience. I still think we are just moving files back and forth without any real benefit. 

Please take a look at this 
https://github.com/magma/magma/discussions/11205

**Comment by hcgatewood** [comment]
> This is impacting many services so should have been brought to a bigger audience. I still think we are just moving files back and forth without any real benefit.
> 
> Please take a look at this #11205

Hey @uri200 thanks for the input. The plan was communicated widely within the team, including at multiple team meetings and with TPMs, EMs, etc. Happy to set up 1-1 time to discuss ideas on how to better communicate these types of changes in the future 🙂

**Review by uri200 — APPROVED** [review]

**Comment by tej-wavelabs** [comment]
Created new PR due to issues with Github Checks. https://github.com/magma/magma/pull/11412

**Pull request closed without merging**
