### PR TITLE
revert(agw): Inject state sync interval from orc8r into agw (#8…

### PR DESCRIPTION
**Pull request by electronjoe**
This reverts commit b6fb403ae42a1f8dfde3aef8682941cdd9d32322.

Backporting from Master.

Signed-off-by: Scott Harrison Moeller <smoeller@fb.com>

### CODE REVIEW

**Review by ardzoht — APPROVED** [review]

**Review by themarwhal — APPROVED** [review]

**Comment by electronjoe** [comment]
Appears to be failing for a slew of docker related issues unrelated to PR?

**Comment by themarwhal** [comment]
@electronjoe I think the *-build jobs failling is OK as they don't really work for non master branches. They try to deploy pre-commit. The NMS tests seem to be failing on other commits on branch 1.7. I'm not sure why though.

**Comment by ekowtaylor** [comment]
Who is merging this?

**Comment by electronjoe** [comment]
> Who is merging this?

I lack the ability to force merge (which I do have on Master...). 

So I am unable to overcome these CI failures.

**Pull request merged**
