### PR TITLE
Update AGW hardware requirements

### PR DESCRIPTION
**Pull request by shaddi**
## Summary

Updates recommended AGW specs in the project documentation.

## Test Plan

n/a

### CODE REVIEW

**Review by ulaskozat — APPROVED** [review]
LGTM

**Review by ulaskozat — APPROVED** [review]
LGTM

**Review by hcgatewood — APPROVED** [review]

**Review by themarwhal — APPROVED** [review]

**Comment by themarwhal** [comment]
@shaddi should I merge this?

**Comment by shaddi** [comment]
Yes please!

**Pull request merged**
