### PR TITLE
fix(monitord): Register operational states callback correctly

### LINKED ISSUE #10163: Frequent Sentry Error: TypeError: 'list' object is not callable
Sentry Issue: [LAB-AGWS-PYTHON-24](https://sentry.io/organizations/lf-9c/issues/2770941608/?referrer=github_integration)

```
TypeError: 'list' object is not callable
  File "grpc/_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/usr/local/lib/python3.8/dist-packages/magma/common/service.py", line 429, in GetOperationalStates
    states = self._get_operational_states_cb()

Exception calling application: 'list' object is not callable
```

### PR DESCRIPTION
**Pull request by sebathomas**
fixes #10163

## Summary

Pass function call instead of function return value as callback.

## Context

Instead of registering a function as callback, the code passed
the return value of the called function to the callback. This
led to an error whenever GetOperationalStates was called for
monitord. It is one of the most frequent issues in Sentry when
it is enabled for Python services.

https://sentry.io/organizations/lf-9c/issues/2770941608/?project=5759591

## Test Plan

Executed GetOperationalStates locally.

### CODE REVIEW

**Comment by themarwhal** [comment]
@sebathomas  For completness, can we file an GitHub issue through Sentry and then link that here?

**Comment by sebathomas** [comment]
> @sebathomas For completness, can we file an GitHub issue through Sentry. And then link that here?
:+1: 

#10163.

**Comment by themarwhal** [comment]
Going to amend the commit and push to see if GHA no triggering is a permission issue.

**Comment by themarwhal** [comment]
Hmm I feel like it is a permission issue somehow... @quentinDERORY / @tmdzk any clue on what might be happening here? It looks like whenever @sebathomas creates a PR no actions get triggered. But if I push to his branch, it seems to. (This PR is another example of this: https://github.com/magma/magma/pull/9974)

**Comment by themarwhal** [comment]
@sebathomas It seems like the Python Format Check is failing. You can resolve it by following the steps described here: https://docs.magmacore.org/docs/next/lte/dev_unit_testing#format-agw

**Review by themarwhal — APPROVED** [review]
LGTM! Thanks for catching the issue and addressing it.

**Comment by sebathomas** [comment]
@themarwhal Thank you for the review! Looks like my push for the formatting fix broke the CI again. :confused:

**Comment by themarwhal** [comment]
> @themarwhal Thank you for the review! Looks like my push for the formatting fix broke the CI again. 😕

What are the exact commands you ran to update the PR?

This is what I've been doing
```
➜  magma git:(only-deploy-agw-after-integ-run) ✗ git remote -v
origin	git@github.com:themarwhal/magma.git (fetch)
origin	git@github.com:themarwhal/magma.git (push)
sebathomas	https://github.com/sebathomas/magma.git (fetch)
sebathomas	https://github.com/sebathomas/magma.git (push)
upstream	git@github.com:magma/magma.git (fetch)
upstream	git@github.com:magma/magma.git (push)

git checkout sebathomas/monitord_operational_states_callback
git branch -f monitord_operational_states_callback
git checkout monitord_operational_states_callback
git commit --amend --signoff --allow-empty
git push -f sebathomas monitord_operational_states_callback

```

**Comment by sebathomas** [comment]
```
$ git remote -v
origin  git@github.com:sebathomas/magma.git (fetch)
origin  git@github.com:sebathomas/magma.git (push)
upstream        git@github.com:magma/magma.git (fetch)
upstream        git@github.com:magma/magma.git (push)
$ git cola (UI tool to do the amend / sign-off)
$ git push -f
```

**Review by ardzoht — APPROVED** [review]
lgtm

**Review by Neudrino — APPROVED** [review]

**Comment by sebathomas** [comment]
Rebased again to fix CI style issues in monitord main.
https://github.com/magma/magma/runs/4141052636?check_suite_focus=true

**Pull request merged**
